// Page 10: Methodology & Disclaimer
// How the model works, data sources, factors considered, legal disclaimer

import { pageHeader, pageFooter, COLORS, formatDate, escapeHtml } from '../helpers';
import type { PDFReportData, ReportMeta } from '../types';

export function renderMethodologyPage(data: PDFReportData, meta: ReportMeta): string {
  const modifierNames = data.result.modifiers.map(m => m.name);

  return `
    <div class="report-page">
      ${pageHeader(10, meta.pageCount, 'Deal Valuation Report')}

      <div class="section-title-lg">Methodology & Disclaimer</div>

      <!-- Two-column layout -->
      <div class="grid-2" style="margin-bottom: 20px;">
        <!-- Left: How the Model Works -->
        <div>
          <div class="section-title">How the Model Works</div>
          <div class="card" style="font-size: 10px; color: ${COLORS.gray700}; line-height: 1.7;">
            <p style="margin-bottom: 8px;">
              The Ambrosia Deal Benchmarker uses a proprietary multi-factor valuation model calibrated against 200+ publicly disclosed pharmaceutical licensing transactions from 2019-2025.
            </p>
            <p style="margin-bottom: 8px;">
              <strong>Base Valuation:</strong> Initial deal value ranges are established using therapeutic area-specific benchmarks derived from actual transaction data, stratified by development phase.
            </p>
            <p style="margin-bottom: 8px;">
              <strong>Modifier System:</strong> The base valuation is adjusted through a series of multiplicative modifiers reflecting asset-specific characteristics including modality, indication, competitive landscape, and data quality.
            </p>
            <p>
              <strong>Sensitivity Analysis:</strong> Each input parameter is systematically varied while holding others constant to quantify marginal impact on deal value, identifying the highest-leverage negotiation levers.
            </p>
          </div>
        </div>

        <!-- Right: About the Model -->
        <div>
          <div class="section-title">About the Model</div>
          <div class="card" style="font-size: 10px; color: ${COLORS.gray700}; line-height: 1.7;">
            <p style="margin-bottom: 8px;">
              <strong>Parameters:</strong> ${modifierNames.length + 5} input variables across asset profile, competitive dynamics, and deal structure factors.
            </p>
            <p style="margin-bottom: 8px;">
              <strong>Coverage:</strong> Oncology (solid tumor + hematology), Neurology (CNS), and Immunology/Autoimmune therapeutic areas.
            </p>
            <p style="margin-bottom: 8px;">
              <strong>Data Sources:</strong> SEC EDGAR filings, ClinicalTrials.gov, company press releases, analyst reports, and proprietary deal databases.
            </p>
            <p style="margin-bottom: 8px;">
              <strong>AI Analysis:</strong> Strategic narrative and negotiation playbook powered by Claude (Anthropic), providing contextual intelligence beyond quantitative benchmarks.
            </p>
            <p>
              <strong>Update Frequency:</strong> Model benchmarks updated quarterly. Real-time deal tracking via SEC EDGAR integration.
            </p>
          </div>
        </div>
      </div>

      <!-- Factors Considered -->
      <div style="margin-bottom: 20px;">
        <div class="section-title">Factors Considered in This Analysis</div>
        <div class="card">
          <div style="display: flex; flex-wrap: wrap; gap: 6px;">
            ${modifierNames.map(name => `<span class="badge badge-gray">${escapeHtml(name)}</span>`).join('')}
            <span class="badge badge-gray">Phase</span>
            <span class="badge badge-gray">Territory</span>
            <span class="badge badge-gray">Competitive Position</span>
            <span class="badge badge-gray">Data Quality</span>
            <span class="badge badge-gray">Therapeutic Area</span>
          </div>
        </div>
      </div>

      <!-- Full-width Disclaimer -->
      <div class="disclaimer-box">
        <div style="font-weight: 600; margin-bottom: 6px; font-size: 10px; color: ${COLORS.gray600};">IMPORTANT DISCLAIMER</div>
        <p style="margin-bottom: 6px;">
          This report is generated by the Ambrosia Deal Benchmarker, a quantitative modeling tool provided by Ambrosia Ventures LLC for informational purposes only. The valuations, ranges, and strategic recommendations contained herein are estimates derived from historical deal data and algorithmic modeling. They do not constitute financial advice, investment recommendations, or professional valuation opinions.
        </p>
        <p style="margin-bottom: 6px;">
          Actual deal terms are influenced by numerous factors not captured in this model, including but not limited to: proprietary clinical data, management quality, IP landscape, regulatory interactions, manufacturing complexity, market dynamics, and negotiation dynamics. Users should engage qualified financial and legal advisors before making any deal-related decisions.
        </p>
        <p>
          AI-generated content (strategic analysis, negotiation playbook) is produced by large language models and may contain inaccuracies. All AI-generated sections are clearly labeled. This report is confidential and intended solely for the use of the addressee. Unauthorized distribution is prohibited.
        </p>
      </div>

      <!-- Footer -->
      <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 20px; padding-top: 12px; border-top: 1px solid ${COLORS.gray200};">
        <div style="display: flex; align-items: center; gap: 8px;">
          <div style="width: 20px; height: 20px; background: linear-gradient(135deg, ${COLORS.teal}, ${COLORS.cyan}); border-radius: 4px;"></div>
          <span style="font-size: 10px; font-weight: 600; color: ${COLORS.gray500};">Ambrosia Ventures</span>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 9px; color: ${COLORS.gray400};">calculator.ambrosiaventures.co</div>
          <div style="font-size: 9px; color: ${COLORS.gray400};">Report ID: ${meta.reportId} &middot; &copy; ${new Date().getFullYear()} Ambrosia Ventures LLC</div>
        </div>
      </div>

      ${pageFooter(meta.reportId)}
    </div>
  `;
}
