// Page: Negotiation Playbook — AI-generated negotiation strategy summary

import { pageHeader, pageFooter, COLORS, escapeHtml } from '../helpers';
import type { PDFReportData, ReportMeta } from '../types';

export function renderNegotiationPage(data: PDFReportData, meta: ReportMeta): string {
  const playbook = data.playbookData;

  // If no playbook data, render a placeholder
  if (!playbook) {
    return `
      <div class="report-page">
        ${pageHeader(12, meta.pageCount, 'Negotiation Strategy')}

        <div class="section-title">NEGOTIATION PLAYBOOK</div>
        <div class="section-title-lg">AI Negotiation Strategy</div>

        <div class="callout" style="margin-top: 24px;">
          <strong>Not Available:</strong> The AI Negotiation Playbook was not generated for this analysis.
          Visit calculator.ambrosiaventures.co to generate an AI-powered negotiation strategy tailored to your deal parameters.
        </div>

        ${pageFooter(meta.reportId)}
      </div>
    `;
  }

  const { sections, keyCaveats } = playbook;
  const sectionOrder: { key: keyof typeof sections; icon: string; color: string }[] = [
    { key: 'openingPosition', icon: '01', color: COLORS.teal },
    { key: 'structureStrategy', icon: '02', color: COLORS.blue },
    { key: 'royaltyFloor', icon: '03', color: COLORS.purple },
  ];

  const sectionCards = sectionOrder.map(({ key, icon, color }) => {
    const section = sections[key];
    if (!section) return '';

    const bulletsHtml = section.bullets.length > 0
      ? `<ul style="margin: 6px 0 0 0; padding-left: 14px; list-style: disc;">
           ${section.bullets.slice(0, 2).map(b => `<li style="font-size: 10px; color: ${COLORS.gray600}; line-height: 1.6; margin-bottom: 3px;">${escapeHtml(b)}</li>`).join('')}
         </ul>`
      : '';

    return `
      <div style="margin-bottom: 16px; page-break-inside: avoid;">
        <div style="display: flex; align-items: flex-start; gap: 12px;">
          <div style="flex-shrink: 0; width: 30px; height: 30px; border-radius: 6px; background: ${color}; display: flex; align-items: center; justify-content: center;">
            <span style="font-size: 10px; font-weight: 700; color: white;">${icon}</span>
          </div>
          <div style="flex: 1;">
            <div style="font-size: 11px; font-weight: 700; color: ${COLORS.navy}; margin-bottom: 4px;">${escapeHtml(section.title)}</div>
            <div style="font-size: 10px; color: ${COLORS.gray500}; line-height: 1.6;">${escapeHtml(section.content.length > 180 ? section.content.substring(0, 180) + '...' : section.content)}</div>
            ${bulletsHtml}
            ${section.highlight ? `
              <div style="margin-top: 6px; padding: 5px 8px; background: ${color}10; border-left: 2px solid ${color}; border-radius: 0 3px 3px 0;">
                <span style="font-size: 9px; font-weight: 700; color: ${color}; text-transform: uppercase; letter-spacing: 0.05em;">Key Insight:</span>
                <span style="font-size: 10px; color: ${COLORS.gray600}; margin-left: 4px;">${escapeHtml(section.highlight)}</span>
              </div>
            ` : ''}
          </div>
        </div>
      </div>
    `;
  }).join('');

  const caveatsHtml = keyCaveats.length > 0
    ? `<div class="callout-amber" style="margin-top: 12px;">
         <strong>Key Caveats:</strong>
         <ul style="margin: 4px 0 0 0; padding-left: 14px; list-style: disc;">
           ${keyCaveats.slice(0, 3).map(c => `<li style="font-size: 10px; line-height: 1.5;">${escapeHtml(c)}</li>`).join('')}
         </ul>
       </div>`
    : '';

  return `
    <div class="report-page">
      ${pageHeader(12, meta.pageCount, 'Negotiation Strategy')}

      <div class="section-title">NEGOTIATION PLAYBOOK</div>
      <div class="section-title-lg">AI Negotiation Strategy</div>

      <p style="font-size: 11px; color: ${COLORS.gray500}; line-height: 1.6; margin-bottom: 18px;">
        AI-generated strategy based on comparable deal structures and market dynamics.
      </p>

      ${sectionCards}
      ${caveatsHtml}

      <div style="margin-top: 12px; padding: 6px 10px; background: ${COLORS.gray50}; border-radius: 4px; border: 1px solid ${COLORS.gray200};">
        <span style="font-size: 9px; color: ${COLORS.gray400};">
          Generated by Ambrosia AI on ${escapeHtml(playbook.generatedAt || 'N/A')}. This playbook is for informational
          purposes only and should not substitute for professional legal or business counsel.
        </span>
      </div>

      ${pageFooter(meta.reportId)}
    </div>
  `;
}
