import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { verifyAdminAuth } from '@/lib/admin-auth';

// Company profiles for cardiovascular, infectious disease, ophthalmology, and women's health
const allCompanies = [
  // ==========================================
  // CARDIOVASCULAR COMPANIES
  // ==========================================
  {
    name: 'Alnylam Pharmaceuticals',
    name_variations: ['Alnylam', 'Alnylam Pharma'],
    ticker: 'ALNY',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['rnai', 'aso'],
    modalities_primary: ['rnai'],
    indications_active: ['cardiovascular', 'rare_disease', 'metabolic'],
    indications_specific: ['attr_amyloidosis', 'hypertension', 'hypercholesterolemia'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 18,
    avg_upfront_usd: 310000000,
    median_upfront_usd: 310000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['RNAi_cardiovascular', 'TTR_amyloidosis', 'hypertension', 'Lp(a)'],
    data_quality_score: 90,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Cytokinetics',
    name_variations: ['Cytokinetics Inc'],
    ticker: 'CYTK',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hcm', 'heart_failure', 'als'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 8,
    avg_upfront_usd: 52700000,
    median_upfront_usd: 52700000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['cardiac_myosin', 'heart_failure', 'HCM', 'muscle_biology'],
    data_quality_score: 85,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'BridgeBio Pharma',
    name_variations: ['BridgeBio'],
    ticker: 'BBIO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'rare_disease'],
    indications_specific: ['attr_cardiomyopathy', 'genetic_diseases'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 12,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['ATTR_cardiomyopathy', 'genetic_medicines', 'cardiovascular'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Tenaya Therapeutics',
    name_variations: ['Tenaya'],
    ticker: 'TNYA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'small_molecule'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular'],
    indications_specific: ['genetic_cardiomyopathy', 'heart_failure'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 68000000,
    median_upfront_usd: 68000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['cardiac_gene_therapy', 'MYBPC3', 'cardiomyopathy'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Verve Therapeutics',
    name_variations: ['Verve'],
    ticker: 'VERV',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular'],
    indications_specific: ['familial_hypercholesterolemia', 'atherosclerosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_1',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 60000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['base_editing', 'PCSK9', 'cardiovascular_gene_editing'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'NewAmsterdam Pharma',
    name_variations: ['NewAmsterdam'],
    ticker: 'NAMS',
    company_type: 'mid_biotech',
    hq_country: 'NL',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hypercholesterolemia', 'dyslipidemia'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['CETP_inhibition', 'obicetrapib', 'lipid_lowering'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Ionis Pharmaceuticals',
    name_variations: ['Ionis', 'Ionis Pharma'],
    ticker: 'IONS',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['aso', 'rnai'],
    modalities_primary: ['aso'],
    indications_active: ['cardiovascular', 'neurology', 'rare_disease'],
    indications_specific: ['Lp_a', 'ApoC3', 'TTR', 'huntingtons'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 25,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['antisense', 'cardiovascular', 'Lp(a)', 'ApoC-III'],
    data_quality_score: 90,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Anthos Therapeutics',
    name_variations: ['Anthos'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['cardiovascular'],
    indications_specific: ['atrial_fibrillation', 'anticoagulation'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 900000000,
    median_upfront_usd: 900000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['Factor_XI', 'anticoagulation', 'abelacimab'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Rocket Pharmaceuticals',
    name_variations: ['Rocket Pharma'],
    ticker: 'RCKT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular', 'rare_disease'],
    indications_specific: ['danon_disease', 'fanconi_anemia', 'lad1'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 6,
    avg_upfront_usd: 45000000,
    median_upfront_usd: 45000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['cardiac_gene_therapy', 'rare_disease', 'lentiviral'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // INFECTIOUS DISEASE COMPANIES
  // ==========================================
  {
    name: 'Gilead Sciences',
    name_variations: ['Gilead'],
    ticker: 'GILD',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'rnai'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease', 'oncology', 'inflammation'],
    indications_specific: ['hiv', 'hepatitis_b', 'hepatitis_c', 'covid'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 45,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['HIV_long_acting', 'hepatitis_B_cure', 'oncology_cell_therapy', 'inflammation'],
    data_quality_score: 95,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'ViiV Healthcare',
    name_variations: ['ViiV', 'ViiV Healthcare (GSK/Pfizer/Shionogi)'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hiv_treatment', 'hiv_prevention'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 20,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['long_acting_HIV', 'cabotegravir', 'HIV_cure'],
    data_quality_score: 85,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Shionogi',
    name_variations: ['Shionogi & Co'],
    ticker: '4507',
    company_type: 'mid_pharma',
    hq_country: 'JP',
    modalities_active: ['small_molecule', 'antibiotic'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['amr_bacterial', 'covid', 'influenza'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 10,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 75000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['antimicrobial_resistance', 'cefiderocol', 'antiviral'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Vir Biotechnology',
    name_variations: ['Vir Bio', 'Vir'],
    ticker: 'VIR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'rnai', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b', 'hepatitis_d', 'influenza', 'covid'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 12,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['HBV_functional_cure', 'elebsiran', 'hepatitis_D', 'pan_viral'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Moderna',
    name_variations: ['Moderna Inc', 'Moderna Therapeutics'],
    ticker: 'MRNA',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['mrna'],
    modalities_primary: ['mrna'],
    indications_active: ['infectious_disease', 'oncology', 'rare_disease'],
    indications_specific: ['rsv', 'covid', 'flu', 'cmv', 'cancer_vaccines'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 35,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['mRNA_vaccines', 'RSV', 'flu_covid_combo', 'cancer_immunology'],
    data_quality_score: 90,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Paratek Pharmaceuticals',
    name_variations: ['Paratek', 'Paratek Pharma'],
    ticker: 'PRTK',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['bacterial_skin_infections', 'pneumonia', 'amr'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 15000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['omadacycline', 'AMR', 'novel_antibiotics'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Assembly Biosciences',
    name_variations: ['Assembly Bio'],
    ticker: 'ASMB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['HBV_capsid', 'hepatitis_B_cure', 'core_protein_allosteric_modulator'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // OPHTHALMOLOGY COMPANIES
  // ==========================================
  {
    name: 'Alcon',
    name_variations: ['Alcon Inc', 'Alcon Laboratories'],
    ticker: 'ALC',
    company_type: 'large_pharma',
    hq_country: 'CH',
    modalities_active: ['small_molecule', 'medical_device'],
    modalities_primary: ['small_molecule'],
    indications_active: ['ophthalmology'],
    indications_specific: ['glaucoma', 'dry_eye', 'cataracts', 'retinal'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 20,
    avg_upfront_usd: 25000000,
    median_upfront_usd: 25000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['surgical_ophthalmology', 'dry_eye', 'glaucoma', 'contact_lens'],
    data_quality_score: 85,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Bausch + Lomb',
    name_variations: ['Bausch Lomb', 'B+L', 'Bausch & Lomb'],
    ticker: 'BLCO',
    company_type: 'large_pharma',
    hq_country: 'CA',
    modalities_active: ['small_molecule', 'medical_device'],
    modalities_primary: ['small_molecule'],
    indications_active: ['ophthalmology'],
    indications_specific: ['dry_eye', 'glaucoma', 'retinal', 'myopia'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 15,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['eye_health', 'surgical', 'vision_care', 'pharma_eye'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Apellis Pharmaceuticals',
    name_variations: ['Apellis', 'Apellis Pharma'],
    ticker: 'APLS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['complement_inhibitor'],
    modalities_primary: ['complement_inhibitor'],
    indications_active: ['ophthalmology', 'hematology'],
    indications_specific: ['geographic_atrophy', 'pnh', 'complement_disorders'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 8,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['complement_C3', 'geographic_atrophy', 'SYFOVRE', 'retinal_diseases'],
    data_quality_score: 85,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Ocugen',
    name_variations: ['Ocugen Inc'],
    ticker: 'OCGN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology'],
    indications_specific: ['retinitis_pigmentosa', 'inherited_retinal_diseases'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 8000000,
    median_upfront_usd: 8000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['ocular_gene_therapy', 'modifier_gene_therapy', 'retinal_disease'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'MeiraGTx',
    name_variations: ['MeiraGTx Holdings'],
    ticker: 'MGTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology', 'neurology'],
    indications_specific: ['xlrp', 'achromatopsia', 'parkinsons'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 6,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['ocular_gene_therapy', 'AAV', 'inherited_retinal_disease'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Beacon Therapeutics',
    name_variations: ['Beacon'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology'],
    indications_specific: ['retinitis_pigmentosa', 'inherited_retinal_diseases'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['retinal_gene_therapy', 'XLRP', 'AAV_optimization'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Aldeyra Therapeutics',
    name_variations: ['Aldeyra'],
    ticker: 'ALDX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['ophthalmology'],
    indications_specific: ['dry_eye_disease', 'retinal_inflammation'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['reproxalap', 'RASP_inhibitor', 'dry_eye', 'ocular_inflammation'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // WOMEN'S HEALTH COMPANIES
  // ==========================================
  {
    name: 'Organon',
    name_variations: ['Organon & Co'],
    ticker: 'OGN',
    company_type: 'mid_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'medical_device'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive', 'fertility'],
    indications_specific: ['contraception', 'fertility', 'endometriosis', 'menopause'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 10,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 75000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['womens_health', 'contraception', 'fertility', 'biosimilars'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Dare Bioscience',
    name_variations: ['Dare Bio', 'Dare'],
    ticker: 'DARE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'medical_device'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['contraception', 'menopause', 'vulvovaginal'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 12000000,
    median_upfront_usd: 12000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['womens_health', 'non_hormonal', 'contraception', 'menopause'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Neurocrine Biosciences',
    name_variations: ['Neurocrine', 'Neurocrine Bio'],
    ticker: 'NBIX',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['neurology', 'reproductive'],
    indications_specific: ['tardive_dyskinesia', 'endometriosis', 'uterine_fibroids', 'cah'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 15,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 60000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['neuropsychiatry', 'endocrinology', 'movement_disorders', 'womens_health'],
    data_quality_score: 85,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'TherapeuticsMD',
    name_variations: ['TherapeuticsMD Inc', 'TxMD'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['hormone_therapy'],
    modalities_primary: ['hormone_therapy'],
    indications_active: ['reproductive'],
    indications_specific: ['menopause', 'contraception', 'vulvovaginal_atrophy'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['hormone_therapy', 'Bijuva', 'Annovera', 'menopause_management'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Myovant Sciences',
    name_variations: ['Myovant', 'Myovant/Sumitomo'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive', 'oncology'],
    indications_specific: ['uterine_fibroids', 'endometriosis', 'prostate_cancer'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 5,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['relugolix', 'MYFEMBREE', 'ORGOVYX', 'GnRH_antagonist'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Ferring Pharmaceuticals',
    name_variations: ['Ferring', 'Ferring Pharma'],
    ticker: null,
    company_type: 'mid_pharma',
    hq_country: 'CH',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['reproductive', 'gastroenterology'],
    indications_specific: ['fertility', 'ivf', 'preterm_labor', 'endometriosis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 12,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['reproductive_medicine', 'fertility', 'microbiome', 'urology'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // ADDITIONAL CARDIOVASCULAR COMPANIES
  // ==========================================
  {
    name: 'Kardigan',
    name_variations: ['Kardigan Inc'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['dilated_cardiomyopathy', 'heart_failure'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 300000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['cardiac_myosin_activation', 'danicamtiv', 'genetic_DCM'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Vasa Therapeutics',
    name_variations: ['Vasa'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hfpef', 'heart_failure'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['MMP_inhibition', 'HFpEF', 'cardiac_fibrosis'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Edwards Lifesciences',
    name_variations: ['Edwards', 'Edwards LS'],
    ticker: 'EW',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['medical_device'],
    modalities_primary: ['medical_device'],
    indications_active: ['cardiovascular'],
    indications_specific: ['aortic_stenosis', 'heart_valve_disease', 'critical_care'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 30,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['TAVR', 'structural_heart', 'critical_care_monitoring'],
    data_quality_score: 90,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Cardurion Pharmaceuticals',
    name_variations: ['Cardurion'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['heart_failure', 'cardiac_remodeling'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['PDE9_inhibition', 'heart_failure', 'BMS_partnership'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Renova Therapeutics',
    name_variations: ['Renova'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular'],
    indications_specific: ['congestive_heart_failure'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['AC6_gene_therapy', 'heart_failure', 'adenylyl_cyclase'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Insilico Medicine',
    name_variations: ['Insilico'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'HK',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology', 'immunology'],
    indications_specific: ['idiopathic_pulmonary_fibrosis', 'cardiovascular_fibrosis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['AI_drug_discovery', 'fibrosis', 'TNIK_inhibitor'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // ADDITIONAL INFECTIOUS DISEASE COMPANIES
  // ==========================================
  {
    name: 'Cidara Therapeutics',
    name_variations: ['Cidara'],
    ticker: 'CDTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'conjugate'],
    modalities_primary: ['conjugate'],
    indications_active: ['infectious_disease'],
    indications_specific: ['influenza', 'antifungal'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 840000000,
    median_upfront_usd: 840000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['drug_Fc_conjugates', 'long_acting_antivirals', 'antifungals'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Entasis Therapeutics',
    name_variations: ['Entasis'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['gram_negative_infections', 'gonorrhea', 'amr'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['AMR', 'gram_negative', 'novel_antibiotics', 'zoliflodacin'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Qpex Biopharma',
    name_variations: ['Qpex'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['mdr_gram_negative', 'carbapenem_resistant'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['beta_lactamase_inhibitor', 'QPX7728', 'AMR'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Genevant Sciences',
    name_variations: ['Genevant'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'CA',
    modalities_active: ['mrna', 'lipid_nanoparticle'],
    modalities_primary: ['lipid_nanoparticle'],
    indications_active: ['infectious_disease', 'oncology'],
    indications_specific: ['vaccines', 'respiratory_infections'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 120000000,
    median_upfront_usd: 120000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['LNP_delivery', 'saRNA', 'mRNA_therapeutics'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Nabriva Therapeutics',
    name_variations: ['Nabriva'],
    ticker: 'NBRV',
    company_type: 'mid_biotech',
    hq_country: 'IE',
    modalities_active: ['antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['cabp', 'skin_infections', 'mrsa'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['lefamulin', 'novel_antibiotics', 'CABP'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Emergent BioSolutions',
    name_variations: ['Emergent', 'Emergent Bio'],
    ticker: 'EBS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['vaccine', 'antibody'],
    modalities_primary: ['vaccine'],
    indications_active: ['infectious_disease'],
    indications_specific: ['anthrax', 'smallpox', 'biodefense', 'opioid_overdose'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['biodefense', 'NARCAN', 'CDMO_services', 'vaccines'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Dynavax Technologies',
    name_variations: ['Dynavax'],
    ticker: 'DVAX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['vaccine', 'adjuvant'],
    modalities_primary: ['adjuvant'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b', 'plague', 'adjuvant_partnerships'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['CpG_1018_adjuvant', 'HEPLISAV_B', 'adjuvant_licensing'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // ADDITIONAL OPHTHALMOLOGY COMPANIES
  // ==========================================
  {
    name: 'Adverum Biotechnologies',
    name_variations: ['Adverum', 'Adverum Bio'],
    ticker: 'ADVM',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology'],
    indications_specific: ['wet_amd', 'diabetic_macular_edema'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['ixo_vec', 'wet_AMD_gene_therapy', 'intravitreal_delivery'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'REGENXBIO',
    name_variations: ['REGENX', 'RegenxBio'],
    ticker: 'RGNX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology', 'neurology', 'metabolic'],
    indications_specific: ['wet_amd', 'diabetic_retinopathy', 'mps_I', 'mps_II'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 8,
    avg_upfront_usd: 370000000,
    median_upfront_usd: 370000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['NAV_AAV_platform', 'retinal_gene_therapy', 'AbbVie_partnership'],
    data_quality_score: 80,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'EyeBio',
    name_variations: ['Eye Bio'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['bispecific'],
    modalities_primary: ['bispecific'],
    indications_active: ['ophthalmology'],
    indications_specific: ['wet_amd', 'dme', 'retinal_vein_occlusion'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 1300000000,
    median_upfront_usd: 1300000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti_VEGF_bispecific', 'next_gen_retinal', 'Merck_acquisition'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Belite Bio',
    name_variations: ['Belite'],
    ticker: 'BLTE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['ophthalmology'],
    indications_specific: ['geographic_atrophy', 'stargardt_disease'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 80000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['tinlarebant', 'RBP4_antagonist', 'geographic_atrophy'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Atsena Therapeutics',
    name_variations: ['Atsena'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['ophthalmology'],
    indications_specific: ['leber_congenital_amaurosis', 'x_linked_retinoschisis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['ATSN_201', 'inherited_retinal_disease', 'LCA1'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Outlook Therapeutics',
    name_variations: ['Outlook'],
    ticker: 'OTLK',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['mab'],
    modalities_primary: ['mab'],
    indications_active: ['ophthalmology'],
    indications_specific: ['wet_amd', 'retinal_vein_occlusion'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['bevacizumab_ophthalmic', 'anti_VEGF_biosimilar'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // ADDITIONAL WOMEN'S HEALTH COMPANIES
  // ==========================================
  {
    name: 'Gameto',
    name_variations: ['Gameto Inc'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['cell_therapy'],
    modalities_primary: ['cell_therapy'],
    indications_active: ['reproductive'],
    indications_specific: ['ivf', 'menopause', 'ovarian_aging'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['Fertilo', 'Ameno', 'ovarian_support_cells', 'egg_maturation'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Gesynta Pharma',
    name_variations: ['Gesynta'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'SE',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['endometriosis_pain', 'inflammation'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 1,
    avg_upfront_usd: 27000000,
    median_upfront_usd: 27000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['vipoglanstat', 'PGES1_inhibition', 'non_hormonal_endometriosis'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Hope Medicine',
    name_variations: ['Hope Med'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'CN',
    modalities_active: ['mab'],
    modalities_primary: ['mab'],
    indications_active: ['reproductive'],
    indications_specific: ['endometriosis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 60000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['HMI_115', 'endometriosis_mab', 'immune_modulation'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Hera Biotech',
    name_variations: ['Hera'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['diagnostic'],
    modalities_primary: ['diagnostic'],
    indications_active: ['reproductive'],
    indications_specific: ['endometriosis_diagnosis', 'cervical_cancer_diagnosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['herafem', 'endometriosis_diagnostics', 'non_surgical_detection'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Theramex',
    name_variations: ['Theramex HQ'],
    ticker: null,
    company_type: 'mid_pharma',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'hormone_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['endometriosis', 'menopause', 'osteoporosis', 'contraception'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['europe', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 50000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['YSELTY_linzagolix', 'womens_health_portfolio', 'endometriosis'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Celmatix Therapeutics',
    name_variations: ['Celmatix'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['ovarian_aging', 'infertility', 'endometriosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_1',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['AMHR2_agonist', 'FSH_receptor_agonist', 'JNK_inhibitor', 'ovarian_aging'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Obseva',
    name_variations: ['ObsEva SA'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'CH',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['preterm_labor', 'endometriosis', 'ivf_support'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['nolasiban', 'preterm_labor', 'oxytocin_receptor_antagonist'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'YourChoice Therapeutics',
    name_variations: ['YourChoice'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['reproductive'],
    indications_specific: ['male_contraception', 'contraception'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 1,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['hormone_free_male_contraception', 'non_hormonal'],
    data_quality_score: 55,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
];

export const maxDuration = 300;
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const authError = await verifyAdminAuth(request);
    if (authError) return authError;

    const supabase = createServiceClient();

    const results = {
      created: [] as string[],
      updated: [] as string[],
      failed: [] as string[],
    };

    // Process in batches of 10
    for (let i = 0; i < allCompanies.length; i += 10) {
      const batch = allCompanies.slice(i, i + 10);

      for (const company of batch) {
        const companyData = {
          ...company,
          updated_at: new Date().toISOString(),
        };

        const { error: insertError } = await supabase
          .from('companies')
          .insert(companyData);

        if (insertError) {
          if (insertError.code === '23505') {
            const { error: retryError } = await supabase
              .from('companies')
              .update(companyData)
              .eq('name', company.name);

            if (retryError) {
              console.error(`[seed-expanded] Update failed for ${company.name}:`, retryError);
              results.failed.push(`Failed to process: ${company.name}`);
            } else {
              results.updated.push(company.name);
            }
          } else {
            console.error(`[seed-expanded] Insert failed for ${company.name}:`, insertError);
            results.failed.push(`Failed to process: ${company.name}`);
          }
        } else {
          results.created.push(company.name);
        }
      }
    }

    return NextResponse.json({
      success: true,
      summary: {
        total_processed: allCompanies.length,
        updated: results.updated.length,
        created: results.created.length,
        failed: results.failed.length,
      },
      details: results,
    });

  } catch (error) {
    console.error('Seed expanded companies error:', error);
    return NextResponse.json(
      { error: 'Failed to seed company data' },
      { status: 500 }
    );
  }
}
