/**
 * Daily competitor intelligence cron job.
 * Fetches RSS feeds from biopharma news sources, deduplicates, analyzes
 * relevance via Claude, stores results, and sends alerts for high-relevance items.
 *
 * Schedule: Daily at 12:00 UTC via Vercel Cron
 * Auth: Bearer token matched against CRON_SECRET
 */

import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import sgMail from '@sendgrid/mail';
import { createServiceClient } from '@/lib/supabase/server';
import { logCronRun } from '@/lib/cron-utils';
import { fetchCompetitorContent, filterNewEntries } from '@/lib/seo/competitor-monitor';
import { analyzeCompetitorContent, type AnalyzedEntry } from '@/lib/seo/competitor-analysis';

export const maxDuration = 120;

// ── Helpers ──────────────────────────────────────────────────────────────────

function buildSlackPayload(entries: AnalyzedEntry[]) {
  const lines = entries.map(
    (e) =>
      `\u{1F50D} [${e.source}] ${e.title} (relevance: ${e.relevanceScore.toFixed(2)})\n` +
      `\u{1F4A1} Suggested response: ${e.suggestedResponse}`
  );

  return {
    text: `Competitor Intel: ${entries.length} new relevant article(s) detected`,
    attachments: [
      {
        color: '#3498db',
        title: `Competitor Intel: ${entries.length} new relevant articles detected`,
        text: lines.join('\n\n'),
        fallback: `Competitor intelligence: ${entries.length} relevant articles found`,
      },
    ],
  };
}

function buildEmailHtml(entries: AnalyzedEntry[]): string {
  const rows = entries
    .map(
      (e) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #eee;">
          <strong><a href="${e.url}" style="color:#3498db;">${e.title}</a></strong><br>
          <span style="color:#666;font-size:13px;">${e.source} &middot; Relevance: ${e.relevanceScore.toFixed(2)}</span><br>
          <span style="font-size:13px;">${e.analysis}</span><br>
          <span style="color:#2ecc71;font-size:13px;"><strong>Suggested response:</strong> ${e.suggestedResponse}</span>
        </td>
      </tr>`
    )
    .join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
      <h2 style="color:#2c3e50;">Daily Competitor Intelligence Digest</h2>
      <p>${entries.length} relevant article(s) detected from biopharma news sources.</p>
      <table style="width:100%;border-collapse:collapse;">${rows}</table>
      <p style="color:#999;font-size:12px;margin-top:20px;">
        Generated by Ambrosia Benchmarker Competitor Intelligence
      </p>
    </div>`;
}

// ── Route handler ────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  const startTime = Date.now();

  // 1. Auth
  const authHeader = request.headers.get('authorization');
  const token = authHeader?.replace('Bearer ', '') || '';
  const secret = process.env.CRON_SECRET || '';

  if (!secret || token.length !== secret.length) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const tokenBuf = Buffer.from(token);
    const secretBuf = Buffer.from(secret);
    if (!crypto.timingSafeEqual(tokenBuf, secretBuf)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
  } catch {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = createServiceClient();

  try {
    // 2. Fetch competitor content from RSS feeds
    const allEntries = await fetchCompetitorContent();

    // 3. Filter out already-seen entries
    const newEntries = await filterNewEntries(supabase, allEntries);

    if (newEntries.length === 0) {
      await logCronRun(supabase, 'competitor-intel', {
        fetched: allEntries.length,
        processed: 0,
        inserted: 0,
        parameters: { status: 'no_new_entries' },
      });
      return NextResponse.json({ message: 'No new entries', fetched: allEntries.length });
    }

    // 4. Analyze via Claude
    const analyzed = await analyzeCompetitorContent(newEntries);

    // 5. Insert all analyzed entries into competitor_content
    const errors: string[] = [];
    let inserted = 0;

    for (const entry of analyzed) {
      const { error } = await supabase.from('competitor_content').insert({
        source: entry.source,
        url: entry.url,
        title: entry.title,
        description: entry.description,
        published_at: entry.publishedAt,
        keyword_overlap: entry.keywordOverlap,
        relevance_score: entry.relevanceScore,
        analysis: entry.analysis,
        suggested_response: entry.suggestedResponse,
        created_at: new Date().toISOString(),
      });

      if (error) {
        errors.push(`${entry.url}: ${error.message}`);
      } else {
        inserted++;
      }
    }

    // 6. Send alerts for high-relevance entries (> 0.5)
    const highRelevance = analyzed.filter((e) => e.relevanceScore > 0.5);

    if (highRelevance.length > 0) {
      // Slack notification
      if (process.env.SLACK_WEBHOOK_URL) {
        try {
          await fetch(process.env.SLACK_WEBHOOK_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(buildSlackPayload(highRelevance)),
          });
        } catch (slackErr) {
          console.error('[competitor-intel] Slack notification failed:', slackErr);
        }
      }

      // Email digest via SendGrid
      if (process.env.SENDGRID_API_KEY) {
        try {
          sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

          const adminEmails = process.env.ADMIN_EMAILS
            ? process.env.ADMIN_EMAILS.split(',').map((e) => e.trim())
            : ['issa@ambrosiaventures.co'];

          await sgMail.send({
            to: adminEmails,
            from: 'alerts@ambrosiaventures.co',
            subject: 'Daily Competitor Intelligence Digest',
            html: buildEmailHtml(highRelevance),
          });
        } catch (emailErr) {
          console.error('[competitor-intel] Email notification failed:', emailErr);
        }
      }
    }

    // 7. Log cron run
    await logCronRun(supabase, 'competitor-intel', {
      fetched: allEntries.length,
      processed: newEntries.length,
      inserted,
      errors,
      parameters: {
        newEntries: newEntries.length,
        analyzed: analyzed.length,
        highRelevance: highRelevance.length,
      },
    });

    const durationMs = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      fetched: allEntries.length,
      newEntries: newEntries.length,
      analyzed: analyzed.length,
      inserted,
      highRelevance: highRelevance.length,
      errors: errors.length,
      durationMs,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    console.error('[competitor-intel] Error:', message);

    await logCronRun(supabase, 'competitor-intel', {
      errors: [message],
      parameters: { stage: 'top-level' },
    });

    return NextResponse.json({ error: message }, { status: 500 });
  }
}
