import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { verifyAdminAuth } from '@/lib/admin-auth';

// Company profiles for immunology and metabolic therapeutic areas
const allCompanies = [
  // ==========================================
  // IMMUNOLOGY COMPANIES
  // ==========================================
  {
    name: 'Prometheus Biosciences',
    name_variations: ['Prometheus Bio', 'Prometheus'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'gi'],
    indications_specific: ['ibd', 'ulcerative_colitis', 'crohns_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 10800000000,
    median_upfront_usd: 10800000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-TL1A', 'ibd', 'precision_medicine', 'biomarker_guided'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Arena Pharmaceuticals',
    name_variations: ['Arena Pharma', 'Arena'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['autoimmune', 'gi', 'dermatology'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'atopic_dermatitis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 0,
    avg_upfront_usd: 6700000000,
    median_upfront_usd: 6700000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['s1p_receptor', 'autoimmune', 'etrasimod'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Chinook Therapeutics',
    name_variations: ['Chinook', 'Chinook Tx'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'renal'],
    indications_specific: ['iga_nephropathy', 'lupus_nephritis', 'kidney_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: 3500000000,
    median_upfront_usd: 3500000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['iga_nephropathy', 'renal_autoimmune', 'atrasentan', 'complement'],
    data_quality_score: 72,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'RemeGen',
    name_variations: ['RemeGen Co.', 'RemeGen Biosciences', '荣昌生物'],
    ticker: '9995.HK',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['adc', 'antibody', 'fusion_protein'],
    modalities_primary: ['adc'],
    indications_active: ['autoimmune', 'oncology'],
    indications_specific: ['systemic_lupus_erythematosus', 'rheumatoid_arthritis', 'breast_cancer'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 15,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['adc_autoimmune', 'telitacicept', 'disitamab_vedotin', 'china_global_licensing'],
    data_quality_score: 68,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Immunocore',
    name_variations: ['Immunocore Holdings', 'Immunocore Ltd'],
    ticker: 'IMCR',
    company_type: 'mid_biotech',
    hq_country: 'UK',
    modalities_active: ['tcr_bispecific', 'bispecific'],
    modalities_primary: ['tcr_bispecific'],
    indications_active: ['oncology', 'autoimmune', 'infectious_disease'],
    indications_specific: ['melanoma', 'solid_tumors', 'autoimmune_expansion'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 12,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['immtac_platform', 'tebentafusp', 'tcr_bispecific', 'autoimmune_expansion'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Kimmtrak (tebentafusp)', indication: 'Oncology (Uveal Melanoma)', revenue_usd: 280000000, expiry_year: 2038 },
    ],
    data_sources: ['manual'],
  },
  {
    name: 'Prothena',
    name_variations: ['Prothena Corporation', 'Prothena Corp'],
    ticker: 'PRTA',
    company_type: 'mid_biotech',
    hq_country: 'Ireland',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'cns', 'rare_disease'],
    indications_specific: ['al_amyloidosis', 'neuroinflammation', 'tau_pathology'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-amyloid', 'birtamimab', 'neuroinflammation', 'tau_antibody'],
    data_quality_score: 74,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Annexon Biosciences',
    name_variations: ['Annexon', 'Annexon Bio'],
    ticker: 'ANNX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'cns', 'rare_disease'],
    indications_specific: ['guillain_barre', 'huntingtons', 'warm_autoimmune_hemolytic_anemia'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['complement_c1q', 'classical_complement', 'autoimmune_neurology'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Protagonist Therapeutics',
    name_variations: ['Protagonist', 'Protagonist Tx'],
    ticker: 'PTGX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['autoimmune', 'gi', 'hematological'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'polycythemia_vera'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oral_peptide', 'il23r_antagonist', 'ibd', 'rusfertide'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'iTeos Therapeutics',
    name_variations: ['iTeos', 'iTeos Tx'],
    ticker: 'ITOS',
    company_type: 'mid_biotech',
    hq_country: 'Belgium',
    modalities_active: ['antibody', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['oncology', 'autoimmune'],
    indications_specific: ['solid_tumors', 'immuno_oncology', 'checkpoint_combinations'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 8,
    avg_upfront_usd: 625000000,
    median_upfront_usd: 625000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-TIGIT', 'checkpoint', 'io_combinations', 'belrestotug'],
    data_quality_score: 72,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Ventyx Biosciences',
    name_variations: ['Ventyx', 'Ventyx Bio'],
    ticker: 'VTYX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['autoimmune', 'dermatology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'atopic_dermatitis', 'ibd'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['allosteric_tyk2', 'oral_autoimmune', 'nlrp3_inhibitor'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'MorphoSys',
    name_variations: ['MorphoSys AG', 'Morpho Sys'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'Germany',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'oncology', 'hematological'],
    indications_specific: ['systemic_lupus_erythematosus', 'dlbcl', 'autoimmune_disorders'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 6,
    avg_upfront_usd: 2700000000,
    median_upfront_usd: 2700000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-CD19', 'tafasitamab', 'antibody_discovery_platform', 'felzartamab'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Celldex Therapeutics',
    name_variations: ['Celldex', 'Celldex Tx'],
    ticker: 'CLDX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'dermatology'],
    indications_specific: ['chronic_spontaneous_urticaria', 'atopic_dermatitis', 'inflammatory'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-KIT', 'barzolvolimab', 'mast_cell', 'urticaria'],
    data_quality_score: 72,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Landos Biopharma',
    name_variations: ['Landos', 'Landos Bio'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['autoimmune', 'gi'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'rheumatoid_arthritis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 3,
    avg_upfront_usd: 25000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['nlrx1_agonist', 'omilancor', 'ibd', 'oral_immunology'],
    data_quality_score: 58,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Acelyrin',
    name_variations: ['Acelyrin Inc.', 'SLRN'],
    ticker: 'SLRN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'dermatology', 'rheumatology'],
    indications_specific: ['hidradenitis_suppurativa', 'rheumatoid_arthritis', 'polymyalgia_rheumatica'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-IL6', 'izokibep', 'autoimmune', 'nanobody'],
    data_quality_score: 65,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Alumis',
    name_variations: ['Alumis Inc.'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['autoimmune', 'dermatology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'systemic_lupus_erythematosus'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['tyk2_inhibitor', 'psoriasis', 'oral_autoimmune', 'eslumisant'],
    data_quality_score: 62,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Upstream Bio',
    name_variations: ['Upstream Biosciences', 'Upstream'],
    ticker: 'UPB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'respiratory'],
    indications_specific: ['asthma', 'copd', 'chronic_rhinosinusitis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-TSLP', 'respiratory', 'verekitug', 'type2_inflammation'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Kiniksa Pharmaceuticals',
    name_variations: ['Kiniksa', 'Kiniksa Pharma'],
    ticker: 'KNSA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'cardiovascular'],
    indications_specific: ['recurrent_pericarditis', 'gout', 'autoinflammatory'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-IL1', 'rilonacept', 'pericarditis', 'autoinflammatory'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Arcalyst (rilonacept)', indication: 'Cardiology (Recurrent Pericarditis)', revenue_usd: 450000000, expiry_year: 2033 },
    ],
    data_sources: ['manual'],
  },
  {
    name: 'Tarsus Pharmaceuticals',
    name_variations: ['Tarsus', 'Tarsus Pharma'],
    ticker: 'TARS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['ophthalmology', 'dermatology', 'autoimmune'],
    indications_specific: ['demodex_blepharitis', 'meibomian_gland_disease', 'rosacea'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['lotilaner', 'demodex', 'ophthalmology', 'inflammatory_expansion'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Xdemvy (lotilaner)', indication: 'Ophthalmology (Demodex Blepharitis)', revenue_usd: 200000000, expiry_year: 2037 },
    ],
    data_sources: ['manual'],
  },
  {
    name: 'Viela Bio',
    name_variations: ['Viela Biosciences'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['autoimmune', 'cns'],
    indications_specific: ['nmosd', 'myasthenia_gravis', 'autoimmune_neurology'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 0,
    avg_upfront_usd: 3050000000,
    median_upfront_usd: 3050000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti-CD19', 'inebilizumab', 'nmosd', 'b_cell_depletion'],
    data_quality_score: 68,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'COUR Pharmaceuticals',
    name_variations: ['COUR Pharma', 'COUR'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['nanoparticle'],
    modalities_primary: ['nanoparticle'],
    indications_active: ['autoimmune', 'cns'],
    indications_specific: ['celiac_disease', 'ms', 'peanut_allergy'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 2,
    avg_upfront_usd: 20000000,
    median_upfront_usd: 10000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['tolerizing_nanoparticle', 'immune_tolerance', 'celiac', 'CNP-101'],
    data_quality_score: 55,
    patent_cliffs: [],
    data_sources: ['manual'],
  },

  // ==========================================
  // METABOLIC COMPANIES
  // ==========================================
  {
    name: 'Viking Therapeutics',
    name_variations: ['Viking', 'Viking Tx'],
    ticker: 'VKTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'endocrine'],
    indications_specific: ['obesity', 'nash', 'type2_diabetes'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['dual_glp1_gip', 'VK2735', 'obesity', 'oral_incretin'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Altimmune',
    name_variations: ['Altimmune Inc.'],
    ticker: 'ALT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['nash', 'obesity', 'liver_fibrosis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['pemvidutide', 'glp1_glucagon_dual', 'nash', 'obesity'],
    data_quality_score: 62,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Zealand Pharma',
    name_variations: ['Zealand', 'Zealand Pharmaceuticals'],
    ticker: 'ZEAL.CO',
    company_type: 'mid_biotech',
    hq_country: 'Denmark',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'rare_disease', 'gi'],
    indications_specific: ['obesity', 'short_bowel_syndrome', 'congenital_hyperinsulinism'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['peptide_therapeutics', 'survodutide', 'glepaglutide', 'rare_metabolic'],
    data_quality_score: 75,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Inversago Pharma',
    name_variations: ['Inversago', 'Inversago Pharmaceuticals'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'Canada',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'endocrine'],
    indications_specific: ['obesity', 'prader_willi_syndrome', 'metabolic_syndrome'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['cb1_inverse_agonist', 'INV-202', 'peripheral_cb1', 'metabolic'],
    data_quality_score: 58,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Carmot Therapeutics',
    name_variations: ['Carmot', 'Carmot Tx'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'endocrine'],
    indications_specific: ['obesity', 'type2_diabetes'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 0,
    avg_upfront_usd: 2700000000,
    median_upfront_usd: 2700000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['glp1_gip', 'CT-388', 'oral_incretin', 'obesity'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Terns Pharmaceuticals',
    name_variations: ['Terns', 'Terns Pharma'],
    ticker: 'TERN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['nash', 'liver_fibrosis', 'nonalcoholic_fatty_liver'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'china'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['fxr_agonist', 'thr_beta_agonist', 'nash', 'TERN-501'],
    data_quality_score: 60,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Akero Therapeutics',
    name_variations: ['Akero', 'Akero Tx'],
    ticker: 'AKRO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['fusion_protein'],
    modalities_primary: ['fusion_protein'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['nash', 'liver_fibrosis', 'metabolic_liver_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['efruxifermin', 'fgf21', 'nash', 'liver_fibrosis'],
    data_quality_score: 72,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: '89bio',
    name_variations: ['89bio Inc.', '89 Bio'],
    ticker: 'ETNB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['fusion_protein'],
    modalities_primary: ['fusion_protein'],
    indications_active: ['metabolic', 'hepatology', 'cardiovascular'],
    indications_specific: ['nash', 'severe_hypertriglyceridemia', 'metabolic_liver_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['pegozafermin', 'fgf21', 'nash', 'severe_hypertriglyceridemia'],
    data_quality_score: 68,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Metacrine',
    name_variations: ['Metacrine Inc.'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['nonalcoholic_fatty_liver', 'metabolic_liver_disease', 'bile_acid_disorders'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_1',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 0,
    active_trials_count: 1,
    avg_upfront_usd: 15000000,
    median_upfront_usd: 10000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['fxr_agonist', 'metabolic_liver', 'MET409', 'bile_acid'],
    data_quality_score: 50,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Fractyl Health',
    name_variations: ['Fractyl', 'Fractyl Laboratories'],
    ticker: 'GUTS',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['device', 'procedure'],
    modalities_primary: ['device'],
    indications_active: ['metabolic', 'endocrine'],
    indications_specific: ['type2_diabetes', 'obesity', 'metabolic_syndrome'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['revita_dmr', 'duodenal_mucosal_resurfacing', 'diabetes', 'device_therapy'],
    data_quality_score: 58,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Intercept Pharmaceuticals',
    name_variations: ['Intercept', 'Intercept Pharma'],
    ticker: 'ICPT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['primary_biliary_cholangitis', 'nash', 'liver_fibrosis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 75000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['ocaliva', 'obeticholic_acid', 'pbc', 'liver_disease'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Ocaliva (obeticholic acid)', indication: 'Hepatology (Primary Biliary Cholangitis)', revenue_usd: 350000000, expiry_year: 2030 },
    ],
    data_sources: ['manual'],
  },
  {
    name: 'Scholar Rock',
    name_variations: ['Scholar Rock Holding', 'Scholar Rock Inc.'],
    ticker: 'SRRK',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['metabolic', 'neuromuscular', 'rare_disease'],
    indications_specific: ['spinal_muscular_atrophy', 'obesity', 'muscle_wasting'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 75000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['myostatin_inhibitor', 'apitegromab', 'sma', 'muscle_biology'],
    data_quality_score: 70,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Madrigal Pharmaceuticals',
    name_variations: ['Madrigal', 'Madrigal Pharma'],
    ticker: 'MDGL',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'hepatology'],
    indications_specific: ['nash', 'mash', 'liver_fibrosis', 'nonalcoholic_steatohepatitis'],
    phase_preference_min: 'phase_3',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'selective',
    strategic_priorities: ['resmetirom', 'rezdiffra', 'thr_beta', 'nash_approved', 'liver_franchise'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Rezdiffra (resmetirom)', indication: 'Hepatology (NASH/MASH)', revenue_usd: 1500000000, expiry_year: 2037 },
    ],
    data_sources: ['manual'],
  },
  {
    name: 'Structure Therapeutics',
    name_variations: ['Structure Tx', 'Structure'],
    ticker: 'GPCR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'endocrine'],
    indications_specific: ['obesity', 'type2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oral_glp1', 'gpcr_platform', 'GSBR-1290', 'obesity'],
    data_quality_score: 68,
    patent_cliffs: [],
    data_sources: ['manual'],
  },
  {
    name: 'Rhythm Pharmaceuticals',
    name_variations: ['Rhythm', 'Rhythm Pharma'],
    ticker: 'RYTM',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'rare_disease', 'endocrine'],
    indications_specific: ['rare_obesity', 'bardet_biedl_syndrome', 'hypothalamic_obesity'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: true,
    acquisition_appetite: 'selective',
    strategic_priorities: ['setmelanotide', 'mc4r_pathway', 'rare_obesity', 'imcivree'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Imcivree (setmelanotide)', indication: 'Rare Disease (Genetic Obesity)', revenue_usd: 300000000, expiry_year: 2036 },
    ],
    data_sources: ['manual'],
  },
];

export async function POST(request: NextRequest) {
  try {
    // Admin auth: timing-safe Bearer token or authenticated admin email
    const authError = await verifyAdminAuth(request);
    if (authError) return authError;

    const supabase = createServiceClient();

    const results: { updated: string[]; created: string[]; failed: string[] } = {
      updated: [],
      created: [],
      failed: [],
    };

    // Get all companies from database
    const { data: companies, error: fetchError } = await supabase
      .from('companies')
      .select('id, name')
      .order('name');

    if (fetchError) {
      console.error('Failed to fetch companies:', fetchError);
      return NextResponse.json(
        { error: 'Failed to fetch companies from database' },
        { status: 500 }
      );
    }

    // Create a map of company names to IDs (case-insensitive)
    const companyMap = new Map<string, string>();
    if (companies) {
      for (const company of companies) {
        companyMap.set(company.name.toLowerCase(), company.id);
      }
    }

    for (const company of allCompanies) {
      // Identity/profile fields — safe to update for existing companies
      const profileData = {
        name: company.name,
        name_variations: company.name_variations,
        ticker: company.ticker,
        company_type: company.company_type,
        hq_country: company.hq_country,
        indications_specific: company.indications_specific,
        territory_focus: company.territory_focus,
        strategic_priorities: company.strategic_priorities,
        patent_cliffs: company.patent_cliffs,
        data_sources: company.data_sources,
        last_enriched_at: new Date().toISOString(),
      };

      // Computed fields — only set on INSERT, not on UPDATE (auto-enrichment pipelines handle these)
      const computedData = {
        modalities_active: company.modalities_active,
        modalities_primary: company.modalities_primary,
        indications_active: company.indications_active,
        phase_preference_min: company.phase_preference_min,
        phase_preference_max: company.phase_preference_max,
        deals_last_12mo: company.deals_last_12mo,
        deals_last_24mo: company.deals_last_24mo,
        active_trials_count: company.active_trials_count,
        avg_upfront_usd: company.avg_upfront_usd,
        median_upfront_usd: company.median_upfront_usd,
        actively_acquiring: company.actively_acquiring,
        acquisition_appetite: company.acquisition_appetite,
        data_quality_score: company.data_quality_score,
      };

      // Full data for inserts only
      const companyData = { ...profileData, ...computedData };

      const existingId = companyMap.get(company.name.toLowerCase());

      if (existingId) {
        // Only update profile/identity fields — preserve auto-computed values
        const { error: updateError } = await supabase
          .from('companies')
          .update(profileData)
          .eq('id', existingId);

        if (updateError) {
          results.failed.push(`${company.name}: ${updateError.message}`);
        } else {
          results.updated.push(company.name);
        }
      } else {
        const { error: insertError } = await supabase
          .from('companies')
          .insert(companyData);

        if (insertError) {
          if (insertError.code === '23505') {
            // Duplicate — try update by name
            const { error: retryError } = await supabase
              .from('companies')
              .update(companyData)
              .eq('name', company.name);

            if (retryError) {
              console.error(`[seed-companies] Update failed for ${company.name}:`, retryError);
              results.failed.push(`Failed to process: ${company.name}`);
            } else {
              results.updated.push(company.name);
            }
          } else {
            console.error(`[seed-companies] Insert failed for ${company.name}:`, insertError);
            results.failed.push(`Failed to process: ${company.name}`);
          }
        } else {
          results.created.push(company.name);
        }
      }
    }

    return NextResponse.json({
      success: true,
      summary: {
        total_processed: allCompanies.length,
        updated: results.updated.length,
        created: results.created.length,
        failed: results.failed.length,
      },
      details: results,
    });

  } catch (error) {
    console.error('Seed immunology/metabolic companies error:', error);
    return NextResponse.json(
      { error: 'Failed to seed company data' },
      { status: 500 }
    );
  }
}
