export const REMEDIATION_THRESHOLDS = {
  AUTO_ACCEPT_MIN_CONFIDENCE: 85,
  AUTO_REJECT_MAX_CONFIDENCE: 40,
  OUTLIER_STDDEV_THRESHOLD: 3.0,
  DRIFT_INVESTIGATION_WINDOW_DAYS: 7,
  UPFRONT_TDV_SWAP_ENABLED: true,
  DRY_RUN_MODE: false,
} as const;
