// Script to seed neurology/CNS-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-neuro-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes CNS-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for neurology assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface NeuroCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// NEUROLOGY/CNS COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const neuroCompanies: NeuroCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA WITH MAJOR CNS FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'AbbVie',
    name_variations: ['AbbVie Inc.', 'AbbVie Inc', 'Allergan'],
    ticker: 'ABBV',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'gene_therapy', 'peptide'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['cns', 'autoimmune', 'oncology', 'aesthetics'],
    indications_specific: ['schizophrenia', 'alzheimers', 'parkinsons', 'depression', 'migraine'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 45,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1400000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['neuroscience', 'schizophrenia', 'alzheimers', 'neurodegeneration', 'psychiatry'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Botox', indication: 'Neurology (Migraine/Movement)', revenue_usd: 5400000000, expiry_year: 2028 },
      { drug_name: 'Vraylar', indication: 'Psychiatry (Schizophrenia)', revenue_usd: 2800000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Eli Lilly',
    name_variations: ['Eli Lilly and Company', 'Lilly', 'Eli Lilly & Co.'],
    ticker: 'LLY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'peptide'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['cns', 'metabolic', 'oncology', 'autoimmune'],
    indications_specific: ['alzheimers', 'pain', 'depression', 'obesity'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 38,
    avg_upfront_usd: 1800000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['alzheimers', 'neurodegeneration', 'anti-amyloid', 'pain', 'obesity'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Kisunla (donanemab)', indication: 'Neurology (Alzheimers)', revenue_usd: 3000000000, expiry_year: 2036 },
      { drug_name: 'Emgality', indication: 'Neurology (Migraine)', revenue_usd: 900000000, expiry_year: 2031 },
    ],
  },
  {
    name: 'Roche',
    name_variations: ['Roche Holding', 'F. Hoffmann-La Roche', 'Genentech'],
    ticker: 'ROG.SW',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['antibody', 'small_molecule', 'gene_therapy', 'aso', 'bbb_platform'],
    modalities_primary: ['antibody', 'bbb_platform'],
    indications_active: ['cns', 'oncology', 'autoimmune', 'rare_disease'],
    indications_specific: ['alzheimers', 'parkinsons', 'huntingtons', 'sma', 'ms'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 14,
    active_trials_count: 52,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['bbb_delivery', 'neurodegeneration', 'brain_shuttle', 'alzheimers', 'huntingtons'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Ocrevus', indication: 'Neurology (Multiple Sclerosis)', revenue_usd: 6200000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Johnson & Johnson',
    name_variations: ['J&J', 'Janssen', 'Janssen Pharmaceuticals', 'Janssen Neuroscience'],
    ticker: 'JNJ',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'psychedelic'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns', 'autoimmune', 'oncology', 'cardiovascular'],
    indications_specific: ['depression', 'schizophrenia', 'alzheimers', 'pain'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 30,
    avg_upfront_usd: 5000000000,
    median_upfront_usd: 3000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['psychiatry', 'depression', 'schizophrenia', 'treatment-resistant depression', 'neuroscience'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Spravato', indication: 'Psychiatry (TRD)', revenue_usd: 1200000000, expiry_year: 2034 },
      { drug_name: 'Caplyta (via acquisition)', indication: 'Psychiatry (Schizophrenia/Depression)', revenue_usd: 1400000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['antibody', 'small_molecule', 'aso', 'bbb_platform'],
    modalities_primary: ['antibody', 'bbb_platform'],
    indications_active: ['cns', 'oncology', 'cardiovascular', 'respiratory'],
    indications_specific: ['alzheimers', 'parkinsons', 'rareNeuro'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 25,
    avg_upfront_usd: 825000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['bbb_delivery', 'neurodegeneration', 'brain_penetrant_antibodies'],
    data_quality_score: 82,
    patent_cliffs: [],
  },
  {
    name: 'Novartis',
    name_variations: ['Novartis AG', 'Novartis Pharma'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['small_molecule', 'gene_therapy', 'aso', 'antibody'],
    modalities_primary: ['small_molecule', 'gene_therapy'],
    indications_active: ['cns', 'oncology', 'cardiovascular', 'autoimmune'],
    indications_specific: ['huntingtons', 'sma', 'ms', 'rareNeuro', 'parkinsons'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 12,
    active_trials_count: 40,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['rare_neurological', 'gene_therapy_cns', 'huntingtons', 'sma', 'neurodegeneration'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Gilenya', indication: 'Neurology (Multiple Sclerosis)', revenue_usd: 2800000000, expiry_year: 2025 },
      { drug_name: 'Zolgensma', indication: 'Neurology (SMA Gene Therapy)', revenue_usd: 1400000000, expiry_year: 2033 },
    ],
  },
  {
    name: 'Sanofi',
    name_variations: ['Sanofi S.A.', 'Sanofi-Aventis'],
    ticker: 'SNY',
    company_type: 'large_pharma',
    hq_country: 'France',
    modalities_active: ['antibody', 'small_molecule', 'aso'],
    modalities_primary: ['antibody'],
    indications_active: ['cns', 'autoimmune', 'rare_disease', 'oncology'],
    indications_specific: ['alzheimers', 'ms', 'rareNeuro'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 22,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['alzheimers', 'tau_antibody', 'neuroinflammation', 'rare_disease'],
    data_quality_score: 80,
    patent_cliffs: [],
  },
  {
    name: 'Takeda',
    name_variations: ['Takeda Pharmaceutical', 'Takeda Pharma'],
    ticker: 'TAK',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'gene_therapy', 'cell_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns', 'rare_disease', 'oncology', 'gi'],
    indications_specific: ['depression', 'schizophrenia', 'rareNeuro', 'narcolepsy'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 18,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['neuroscience', 'rare_disease_cns', 'depression', 'narcolepsy'],
    data_quality_score: 75,
    patent_cliffs: [],
  },

  // ─────────────────────────────────────────────────────────────────
  // LARGE BIOTECH — PRIMARY CNS FOCUS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Biogen',
    name_variations: ['Biogen Inc.', 'Biogen Idec'],
    ticker: 'BIIB',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'aso', 'gene_therapy', 'small_molecule'],
    modalities_primary: ['antibody', 'aso'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['alzheimers', 'ms', 'als', 'parkinsons', 'sma', 'rareNeuro'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 35,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 350000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['alzheimers', 'als', 'parkinsons', 'neurodegeneration', 'digital_biomarkers_cns'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Leqembi (lecanemab)', indication: 'Neurology (Alzheimers)', revenue_usd: 1800000000, expiry_year: 2037 },
      { drug_name: 'Spinraza', indication: 'Neurology (SMA)', revenue_usd: 1700000000, expiry_year: 2030 },
      { drug_name: 'Tysabri', indication: 'Neurology (Multiple Sclerosis)', revenue_usd: 1900000000, expiry_year: 2027 },
      { drug_name: 'Tecfidera', indication: 'Neurology (Multiple Sclerosis)', revenue_usd: 1800000000, expiry_year: 2025 },
    ],
  },
  {
    name: 'Eisai',
    name_variations: ['Eisai Co.', 'Eisai Inc.'],
    ticker: '4523.T',
    company_type: 'large_biotech',
    hq_country: 'Japan',
    modalities_active: ['antibody', 'small_molecule'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['cns', 'oncology'],
    indications_specific: ['alzheimers', 'epilepsy', 'pain'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 20,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['alzheimers', 'lecanemab', 'anti-amyloid', 'epilepsy', 'dementia'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Leqembi (lecanemab)', indication: 'Neurology (Alzheimers)', revenue_usd: 1800000000, expiry_year: 2037 },
      { drug_name: 'Fycompa', indication: 'Neurology (Epilepsy)', revenue_usd: 400000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Jazz Pharmaceuticals',
    name_variations: ['Jazz Pharma', 'Jazz'],
    ticker: 'JAZZ',
    company_type: 'large_biotech',
    hq_country: 'Ireland',
    modalities_active: ['small_molecule', 'gene_therapy', 'aso'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['narcolepsy', 'epilepsy', 'rareNeuro'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 15,
    avg_upfront_usd: 800000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['sleep_disorders', 'narcolepsy', 'epilepsy', 'rare_cns'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Xywav', indication: 'Neurology (Narcolepsy)', revenue_usd: 2100000000, expiry_year: 2031 },
      { drug_name: 'Epidiolex', indication: 'Neurology (Epilepsy)', revenue_usd: 800000000, expiry_year: 2036 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP BIOTECH — CNS-FOCUSED
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Neurocrine Biosciences',
    name_variations: ['Neurocrine'],
    ticker: 'NBIX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'gene_therapy', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['tardive_dyskinesia', 'parkinsons', 'schizophrenia', 'rareNeuro'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 12,
    avg_upfront_usd: 175000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['movement_disorders', 'psychiatry', 'gene_therapy_cns', 'parkinsons'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Ingrezza', indication: 'Neurology (Tardive Dyskinesia)', revenue_usd: 2100000000, expiry_year: 2031 },
    ],
  },
  {
    name: 'Acadia Pharmaceuticals',
    name_variations: ['Acadia Pharma', 'ACAD'],
    ticker: 'ACAD',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['parkinsons', 'rareNeuro', 'rett_syndrome', 'schizophrenia'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 75000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['neuropsychiatry', 'rett_syndrome', 'parkinsons_psychosis', 'rare_cns'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Nuplazid', indication: 'Neurology (Parkinson\'s Psychosis)', revenue_usd: 560000000, expiry_year: 2029 },
      { drug_name: 'Daybue', indication: 'Neurology (Rett Syndrome)', revenue_usd: 400000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Ionis Pharmaceuticals',
    name_variations: ['Ionis', 'Isis Pharmaceuticals'],
    ticker: 'IONS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['aso', 'oligonucleotide'],
    modalities_primary: ['aso'],
    indications_active: ['cns', 'rare_disease', 'cardiovascular'],
    indications_specific: ['als', 'huntingtons', 'sma', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 25,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['antisense_cns', 'als', 'huntingtons', 'cns_delivery', 'rare_neurological'],
    data_quality_score: 85,
    patent_cliffs: [],
  },
  {
    name: 'Denali Therapeutics',
    name_variations: ['Denali'],
    ticker: 'DNLI',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'bbb_platform', 'gene_therapy'],
    modalities_primary: ['bbb_platform', 'antibody'],
    indications_active: ['cns'],
    indications_specific: ['alzheimers', 'parkinsons', 'als', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['bbb_delivery', 'trem2', 'lrrk2', 'neurodegeneration', 'transport_vehicle'],
    data_quality_score: 78,
    patent_cliffs: [],
  },
  {
    name: 'Sage Therapeutics',
    name_variations: ['Sage'],
    ticker: 'SAGE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['depression', 'epilepsy', 'parkinsons', 'pain'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['depression', 'zuranolone', 'gaba_modulation', 'postpartum_depression'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Zurzuvae (zuranolone)', indication: 'Psychiatry (Postpartum Depression)', revenue_usd: 200000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Lundbeck',
    name_variations: ['H. Lundbeck', 'Lundbeck A/S'],
    ticker: 'LUN.CO',
    company_type: 'mid_pharma',
    hq_country: 'Denmark',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['depression', 'schizophrenia', 'parkinsons', 'alzheimers', 'migraine'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 14,
    avg_upfront_usd: 250000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['depression', 'schizophrenia', 'neurodegeneration', 'psychiatry', 'migraine'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Brintellix/Trintellix', indication: 'Psychiatry (Depression)', revenue_usd: 1100000000, expiry_year: 2027 },
      { drug_name: 'Rexulti', indication: 'Psychiatry (Schizophrenia)', revenue_usd: 1400000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Otsuka',
    name_variations: ['Otsuka Pharmaceutical', 'Otsuka Holdings'],
    ticker: '4578.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['schizophrenia', 'depression', 'alzheimers'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['psychiatry', 'schizophrenia', 'depression', 'digital_therapeutics_cns'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Rexulti', indication: 'Psychiatry (Schizophrenia/Depression)', revenue_usd: 1400000000, expiry_year: 2030 },
      { drug_name: 'Abilify Maintena', indication: 'Psychiatry (Schizophrenia)', revenue_usd: 1600000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'UCB',
    name_variations: ['UCB S.A.', 'UCB Pharma'],
    ticker: 'UCB.BR',
    company_type: 'mid_pharma',
    hq_country: 'Belgium',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['cns', 'autoimmune'],
    indications_specific: ['epilepsy', 'parkinsons', 'rareNeuro'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['epilepsy', 'parkinsons', 'rare_epilepsy', 'antibody_therapeutics'],
    data_quality_score: 76,
    patent_cliffs: [
      { drug_name: 'Vimpat', indication: 'Neurology (Epilepsy)', revenue_usd: 2000000000, expiry_year: 2026 },
      { drug_name: 'Briviact', indication: 'Neurology (Epilepsy)', revenue_usd: 500000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'Wave Life Sciences',
    name_variations: ['Wave'],
    ticker: 'WVE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['aso', 'oligonucleotide'],
    modalities_primary: ['aso'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['huntingtons', 'als', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['stereopure_oligonucleotides', 'huntingtons', 'als', 'cns_delivery'],
    data_quality_score: 65,
    patent_cliffs: [],
  },
  {
    name: 'Voyager Therapeutics',
    name_variations: ['Voyager'],
    ticker: 'VYGR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'bbb_platform', 'antibody'],
    modalities_primary: ['bbb_platform', 'gene_therapy'],
    indications_active: ['cns'],
    indications_specific: ['alzheimers', 'parkinsons', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 4,
    avg_upfront_usd: 175000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['aav_capsid_cns', 'bbb_delivery', 'anti-tau', 'gene_therapy_cns'],
    data_quality_score: 68,
    patent_cliffs: [],
  },
  {
    name: 'Alector',
    name_variations: ['Alector Inc.'],
    ticker: 'ALEC',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['cns'],
    indications_specific: ['alzheimers', 'als', 'parkinsons', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['immuno-neurology', 'trem2', 'progranulin', 'neurodegeneration'],
    data_quality_score: 65,
    patent_cliffs: [],
  },
  {
    name: 'Praxis Precision Medicine',
    name_variations: ['Praxis'],
    ticker: 'PRAX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['epilepsy', 'depression', 'pain', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['ion_channel', 'epilepsy', 'genetic_epilepsy', 'cns_ion_channels'],
    data_quality_score: 60,
    patent_cliffs: [],
  },
  {
    name: 'Axsome Therapeutics',
    name_variations: ['Axsome'],
    ticker: 'AXSM',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['depression', 'alzheimers', 'narcolepsy', 'migraine', 'pain'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['depression', 'alzheimer_agitation', 'narcolepsy', 'multi-indication_cns'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Auvelity', indication: 'Psychiatry (MDD)', revenue_usd: 500000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Harmony Biosciences',
    name_variations: ['Harmony'],
    ticker: 'HRMY',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['narcolepsy', 'rareNeuro', 'epilepsy'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['narcolepsy', 'orexin', 'sleep_disorders', 'rare_cns'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Wakix', indication: 'Neurology (Narcolepsy)', revenue_usd: 600000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Neumora Therapeutics',
    name_variations: ['Neumora'],
    ticker: 'NMRA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['depression', 'alzheimers', 'pain'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['precision_psychiatry', 'depression', 'kappa_opioid', 'cns_biomarkers'],
    data_quality_score: 55,
    patent_cliffs: [],
  },
  {
    name: 'uniQure',
    name_variations: ['uniQure N.V.', 'Uniqure'],
    ticker: 'QURE',
    company_type: 'mid_biotech',
    hq_country: 'Netherlands',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['huntingtons', 'rareNeuro'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['huntingtons_gene_therapy', 'aav_cns', 'one_time_gene_therapy'],
    data_quality_score: 62,
    patent_cliffs: [],
  },
  {
    name: 'Passage Bio',
    name_variations: ['Passage BioSciences'],
    ticker: 'PASG',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cns', 'rare_disease'],
    indications_specific: ['rareNeuro', 'gm1_gangliosidosis', 'krabbe'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['cns_gene_therapy', 'lysosomal_storage', 'rare_neurological'],
    data_quality_score: 55,
    patent_cliffs: [],
  },
  {
    name: 'Annovis Bio',
    name_variations: ['Annovis'],
    ticker: 'ANVS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cns'],
    indications_specific: ['alzheimers', 'parkinsons'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['alzheimers', 'parkinsons', 'neurotoxic_protein_inhibitor'],
    data_quality_score: 50,
    patent_cliffs: [],
  },
  {
    name: 'BioArctic',
    name_variations: ['BioArctic AB'],
    ticker: 'BIOA-B.ST',
    company_type: 'mid_biotech',
    hq_country: 'Sweden',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['cns'],
    indications_specific: ['alzheimers', 'parkinsons', 'als'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 4,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 150000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['lecanemab_originator', 'alzheimers', 'alpha-synuclein', 'parkinsons'],
    data_quality_score: 68,
    patent_cliffs: [],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedNeuroCompanies() {
  console.log('Starting neurology/CNS company seed...\n');
  console.log(`Seeding ${neuroCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of neuroCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    // Try insert first
    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        // Already exists — update with neurology data
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            // Merge arrays rather than overwrite for companies that may already have oncology data
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with CNS data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${neuroCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedNeuroCompanies().catch(console.error);
