// Script to seed immunology-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-immunology-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes immunology-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for immunology assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface ImmunologyCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// IMMUNOLOGY COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const immunologyCompanies: ImmunologyCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA WITH MAJOR IMMUNOLOGY FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'AbbVie',
    name_variations: ['AbbVie Inc.', 'AbbVie Inc', 'Pharmacyclics'],
    ticker: 'ABBV',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'peptide', 'adc'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['immunology', 'oncology', 'hematology', 'neuroscience'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'rheumatoid_arthritis', 'atopic_dermatitis', 'ulcerative_colitis', 'crohns_disease', 'hidradenitis_suppurativa'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 55,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['il23_franchise', 'jak_inhibitors', 'next_gen_tnf', 'post_humira_immunology', 'oral_immunology'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Humira (adalimumab)', indication: 'Immunology (RA/PsA/UC/CD)', revenue_usd: 14400000000, expiry_year: 2023 },
      { drug_name: 'Skyrizi (risankizumab)', indication: 'Immunology (Psoriasis/PsA/CD/UC)', revenue_usd: 8500000000, expiry_year: 2035 },
      { drug_name: 'Rinvoq (upadacitinib)', indication: 'Immunology (RA/PsA/AD/UC/CD)', revenue_usd: 5200000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Johnson & Johnson (Janssen)',
    name_variations: ['J&J', 'Janssen', 'Janssen Pharmaceuticals', 'Janssen Biotech'],
    ticker: 'JNJ',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'bispecific', 'small_molecule', 'peptide'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'oncology', 'hematology', 'neuroscience'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'crohns_disease', 'ulcerative_colitis', 'lupus'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 40,
    avg_upfront_usd: 3500000000,
    median_upfront_usd: 2000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['il23_expansion', 'post_stelara_strategy', 'ibd', 'psoriatic_disease', 'next_gen_biologics'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Stelara (ustekinumab)', indication: 'Immunology (Psoriasis/PsA/CD/UC)', revenue_usd: 10900000000, expiry_year: 2025 },
      { drug_name: 'Tremfya (guselkumab)', indication: 'Immunology (Psoriasis/PsA)', revenue_usd: 3800000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Roche/Genentech',
    name_variations: ['Roche', 'Genentech', 'Roche Holding AG', 'F. Hoffmann-La Roche'],
    ticker: 'RHHBY',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['antibody', 'bispecific', 'small_molecule', 'adc'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'oncology', 'neurology', 'hematology'],
    indications_specific: ['multiple_sclerosis', 'rheumatoid_arthritis', 'lupus', 'vasculitis', 'giant_cell_arteritis', 'neuromyelitis_optica'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 13,
    active_trials_count: 50,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['cd20_franchise', 'il6_pathway', 'ms_dominance', 'next_gen_autoimmune', 'complement'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Ocrevus (ocrelizumab)', indication: 'Immunology (Multiple Sclerosis)', revenue_usd: 7200000000, expiry_year: 2031 },
      { drug_name: 'Actemra/RoActemra (tocilizumab)', indication: 'Immunology (RA/GCA)', revenue_usd: 3800000000, expiry_year: 2027 },
      { drug_name: 'MabThera/Rituxan (rituximab)', indication: 'Immunology (RA/Vasculitis)', revenue_usd: 2100000000, expiry_year: 2025 },
    ],
  },
  {
    name: 'Novartis',
    name_variations: ['Novartis AG', 'Novartis Pharma'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['antibody', 'small_molecule', 'cell_therapy', 'gene_therapy'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['immunology', 'oncology', 'hematology', 'cardiovascular', 'neurology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'ankylosing_spondylitis', 'multiple_sclerosis', 'asthma', 'urticaria', 'hidradenitis_suppurativa'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 13,
    active_trials_count: 45,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['il17_franchise', 'b_cell_depletion', 'ige_pathway', 'next_gen_autoimmune', 'tyk2'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Cosentyx (secukinumab)', indication: 'Immunology (Psoriasis/PsA/AS/HS)', revenue_usd: 5000000000, expiry_year: 2029 },
      { drug_name: 'Kesimpta (ofatumumab)', indication: 'Immunology (Multiple Sclerosis)', revenue_usd: 2800000000, expiry_year: 2035 },
      { drug_name: 'Xolair (omalizumab)', indication: 'Immunology (Asthma/Urticaria)', revenue_usd: 2500000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Sanofi',
    name_variations: ['Sanofi S.A.', 'Sanofi-Aventis', 'Sanofi-Regeneron'],
    ticker: 'SNY',
    company_type: 'large_pharma',
    hq_country: 'France',
    modalities_active: ['antibody', 'small_molecule', 'bispecific'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'rare_disease', 'oncology', 'hematology'],
    indications_specific: ['atopic_dermatitis', 'asthma', 'chronic_rhinosinusitis', 'eosinophilic_esophagitis', 'copd', 'prurigo_nodularis', 'urticaria'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 40,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['dupixent_expansion', 'il4_il13_pathway', 'type2_inflammation', 'next_gen_atopic', 'eosinophilic_disease'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Dupixent (dupilumab)', indication: 'Immunology (AD/Asthma/CRSwNP/EoE/COPD)', revenue_usd: 13000000000, expiry_year: 2031 },
      { drug_name: 'Kevzara (sarilumab)', indication: 'Immunology (Rheumatoid Arthritis)', revenue_usd: 500000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Pfizer',
    name_variations: ['Pfizer Inc.', 'Pfizer Inc'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'oncology', 'hematology', 'rare_disease', 'infectious_disease'],
    indications_specific: ['rheumatoid_arthritis', 'psoriatic_arthritis', 'ulcerative_colitis', 'atopic_dermatitis', 'ankylosing_spondylitis', 'alopecia_areata'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 35,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['jak_franchise', 'oral_immunology', 'next_gen_jak', 'post_covid_diversification', 'autoimmune_pipeline'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Xeljanz (tofacitinib)', indication: 'Immunology (RA/PsA/UC/AS)', revenue_usd: 2000000000, expiry_year: 2025 },
      { drug_name: 'Cibinqo (abrocitinib)', indication: 'Immunology (Atopic Dermatitis)', revenue_usd: 600000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ', 'MedImmune'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['antibody', 'small_molecule', 'bispecific'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'oncology', 'cardiovascular', 'respiratory'],
    indications_specific: ['asthma', 'eosinophilic_asthma', 'copd', 'chronic_rhinosinusitis', 'urticaria'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 30,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['respiratory_immunology', 'eosinophil_targeting', 'tslp_pathway', 'il5_franchise', 'severe_asthma'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Fasenra (benralizumab)', indication: 'Immunology (Severe Eosinophilic Asthma)', revenue_usd: 1800000000, expiry_year: 2032 },
      { drug_name: 'Tezspire (tezepelumab)', indication: 'Immunology (Severe Asthma/CRSwNP)', revenue_usd: 1200000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'GSK',
    name_variations: ['GlaxoSmithKline', 'GSK plc'],
    ticker: 'GSK',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['antibody', 'small_molecule', 'bispecific'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'oncology', 'infectious_disease', 'respiratory'],
    indications_specific: ['lupus', 'systemic_lupus_erythematosus', 'asthma', 'eosinophilic_asthma', 'copd', 'hypereosinophilic_syndrome'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 25,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['lupus_franchise', 'b_cell_targeting', 'eosinophil_pathway', 'respiratory_immunology', 'il5_expansion'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Benlysta (belimumab)', indication: 'Immunology (Systemic Lupus/Lupus Nephritis)', revenue_usd: 2200000000, expiry_year: 2029 },
      { drug_name: 'Nucala (mepolizumab)', indication: 'Immunology (Eosinophilic Asthma/HES/CRSwNP)', revenue_usd: 1800000000, expiry_year: 2030 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP IMMUNOLOGY BIOTECHS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Horizon Therapeutics (Amgen)',
    name_variations: ['Horizon', 'Horizon Pharma', 'Horizon Therapeutics plc'],
    ticker: 'AMGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'fusion_protein'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'rare_disease', 'nephrology'],
    indications_specific: ['thyroid_eye_disease', 'gout', 'iga_nephropathy', 'rare_autoimmune'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 20,
    avg_upfront_usd: 800000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_autoimmune', 'igf1r_pathway', 'refractory_gout', 'thyroid_eye_disease', 'inflammation'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Tepezza (teprotumumab)', indication: 'Immunology (Thyroid Eye Disease)', revenue_usd: 2000000000, expiry_year: 2034 },
      { drug_name: 'Krystexxa (pegloticase)', indication: 'Immunology (Refractory Gout)', revenue_usd: 900000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Argenx',
    name_variations: ['argenx SE', 'argenx', 'Argenx SE'],
    ticker: 'ARGX',
    company_type: 'mid_biotech',
    hq_country: 'Netherlands',
    modalities_active: ['antibody', 'antibody_fragment'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'neurology', 'hematology'],
    indications_specific: ['myasthenia_gravis', 'cidp', 'pemphigus_vulgaris', 'immune_thrombocytopenia', 'membranous_nephropathy', 'bullous_pemphigoid'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 18,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['fcrn_platform', 'igg_autoantibody_diseases', 'neuromuscular_autoimmune', 'complement', 'rare_autoimmune'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Vyvgart (efgartigimod)', indication: 'Immunology (gMG/CIDP/PV)', revenue_usd: 2500000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'UCB',
    name_variations: ['UCB S.A.', 'UCB Pharma'],
    ticker: 'UCB.BR',
    company_type: 'mid_pharma',
    hq_country: 'Belgium',
    modalities_active: ['antibody', 'small_molecule', 'antibody_fragment'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'neurology', 'dermatology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'ankylosing_spondylitis', 'hidradenitis_suppurativa', 'crohns_disease', 'rheumatoid_arthritis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 22,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['il17_dual_inhibition', 'next_gen_psoriasis', 'tnf_franchise_sunset', 'autoimmune_dermatology', 'ibd'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Bimzelx (bimekizumab)', indication: 'Immunology (Psoriasis/PsA/AS/HS)', revenue_usd: 2500000000, expiry_year: 2037 },
      { drug_name: 'Cimzia (certolizumab pegol)', indication: 'Immunology (RA/PsA/AS/CD)', revenue_usd: 1800000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Galapagos',
    name_variations: ['Galapagos NV', 'Galapagos Biotech'],
    ticker: 'GLPG',
    company_type: 'mid_biotech',
    hq_country: 'Belgium',
    modalities_active: ['small_molecule', 'cell_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'fibrosis'],
    indications_specific: ['rheumatoid_arthritis', 'ulcerative_colitis', 'crohns_disease', 'psoriatic_arthritis', 'ankylosing_spondylitis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['europe', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['jak_inhibitors', 'oral_autoimmune', 'filgotinib_expansion', 'cell_therapy_autoimmune'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Jyseleca (filgotinib)', indication: 'Immunology (RA/UC)', revenue_usd: 300000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'TG Therapeutics',
    name_variations: ['TG Therapeutics Inc', 'TG Therapeutics Inc.'],
    ticker: 'TGTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'hematology'],
    indications_specific: ['multiple_sclerosis', 'relapsing_ms'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['anti_cd20_ms', 'b_cell_depletion', 'subcutaneous_ms', 'autoimmune_expansion'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Briumvi (ublituximab)', indication: 'Immunology (Relapsing Multiple Sclerosis)', revenue_usd: 800000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Protagonist Therapeutics',
    name_variations: ['Protagonist', 'Protagonist Therapeutics Inc'],
    ticker: 'PTGX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['immunology', 'hematology', 'gi'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'ibd'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['oral_peptide_immunology', 'il17_peptide', 'integrin_peptides', 'oral_biologics'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Icotrokinra (JNJ-2113)', indication: 'Immunology (Psoriasis/UC oral peptide)', revenue_usd: 600000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Ventyx Biosciences (Eli Lilly)',
    name_variations: ['Ventyx', 'Ventyx Biosciences Inc', 'Ventyx/Lilly'],
    ticker: 'LLY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'gi'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'psoriasis', 'psoriatic_arthritis', 'ibd'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 10,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['tl1a_inhibition', 'tyk2_inhibitors', 'oral_autoimmune', 'ibd_pipeline', 'next_gen_jak'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'VTX958 (TL1A inhibitor)', indication: 'Immunology (IBD/Psoriasis)', revenue_usd: 500000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'Acelyrin',
    name_variations: ['Acelyrin Inc', 'ACELYRIN'],
    ticker: 'SLRN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody_fragment', 'small_molecule'],
    modalities_primary: ['antibody_fragment'],
    indications_active: ['immunology', 'dermatology'],
    indications_specific: ['psoriatic_arthritis', 'ankylosing_spondylitis', 'hidradenitis_suppurativa', 'psoriasis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['il17_nanobody', 'subcutaneous_autoimmune', 'rapid_onset_biologics', 'spondyloarthritis'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Izokibep (IL-17A nanobody)', indication: 'Immunology (PsA/AS/HS)', revenue_usd: 400000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Annexon Biosciences',
    name_variations: ['Annexon', 'Annexon Biosciences Inc'],
    ticker: 'ANNX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'neurology', 'ophthalmology'],
    indications_specific: ['guillain_barre', 'autoimmune_hemolytic_anemia', 'geographic_atrophy', 'huntingtons'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['classical_complement', 'c1q_inhibition', 'autoimmune_neuropathy', 'complement_mediated_disease'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'ANX005 (anti-C1q)', indication: 'Immunology (Guillain-Barre/AIHA)', revenue_usd: 300000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Rallybio',
    name_variations: ['Rallybio Corp', 'Rallybio Corporation'],
    ticker: 'RLYB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'hematology', 'rare_disease'],
    indications_specific: ['fnait', 'complement_disorders', 'hemolytic_disease_newborn'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['anti_hpa1a', 'fnait_prevention', 'complement_rare', 'neonatal_alloimmune'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'RLYB212 (anti-HPA-1a)', indication: 'Immunology (FNAIT Prevention)', revenue_usd: 200000000, expiry_year: 2040 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // SPECIALTY IMMUNOLOGY
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Aurinia Pharmaceuticals',
    name_variations: ['Aurinia', 'Aurinia Pharma'],
    ticker: 'AUPH',
    company_type: 'specialty',
    hq_country: 'Canada',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'nephrology'],
    indications_specific: ['lupus_nephritis', 'systemic_lupus_erythematosus', 'iga_nephropathy'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['lupus_nephritis', 'calcineurin_inhibition', 'renal_autoimmune', 'voclosporin_expansion'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Lupkynis (voclosporin)', indication: 'Immunology (Lupus Nephritis)', revenue_usd: 600000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Alumis',
    name_variations: ['Alumis Inc'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'dermatology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'lupus', 'hidradenitis_suppurativa'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['tyk2_inhibition', 'next_gen_oral_psoriasis', 'allosteric_tyk2', 'autoimmune_dermatology'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'ESK-001 (TYK2 inhibitor)', indication: 'Immunology (Psoriasis/PsA)', revenue_usd: 400000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'Priovant Therapeutics (Roivant)',
    name_variations: ['Priovant', 'Priovant Therapeutics', 'Roivant Sciences'],
    ticker: 'ROIV',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'dermatology'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'lupus', 'dermatomyositis', 'vitiligo'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['dual_tyk2_jak1', 'oral_psoriasis', 'autoimmune_pipeline', 'brepocitinib_expansion'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Brepocitinib (TYK2/JAK1)', indication: 'Immunology (Psoriasis/DM/Vitiligo)', revenue_usd: 500000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Chinook Therapeutics (Novartis)',
    name_variations: ['Chinook', 'Chinook Therapeutics Inc'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'nephrology'],
    indications_specific: ['iga_nephropathy', 'lupus_nephritis', 'complement_nephropathy', 'membranous_nephropathy'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['iga_nephropathy', 'renal_autoimmune', 'april_targeting', 'complement_kidney', 'lupus_nephritis'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Atrasentan', indication: 'Immunology (IgA Nephropathy)', revenue_usd: 500000000, expiry_year: 2037 },
      { drug_name: 'Zigakibart (anti-APRIL)', indication: 'Immunology (IgA Nephropathy)', revenue_usd: 400000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Vera Therapeutics',
    name_variations: ['Vera', 'Vera Therapeutics Inc'],
    ticker: 'VERA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['fusion_protein', 'antibody'],
    modalities_primary: ['fusion_protein'],
    indications_active: ['immunology', 'nephrology'],
    indications_specific: ['iga_nephropathy', 'lupus_nephritis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['atacicept_igan', 'april_blys_dual', 'renal_autoimmune', 'b_cell_modulation'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Atacicept (TACI-Fc)', indication: 'Immunology (IgA Nephropathy)', revenue_usd: 600000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Omeros',
    name_variations: ['Omeros Corporation', 'Omeros Corp'],
    ticker: 'OMER',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'hematology', 'nephrology'],
    indications_specific: ['iga_nephropathy', 'atypical_hus', 'stem_cell_transplant', 'complement_disorders'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['masp2_inhibition', 'lectin_complement', 'iga_nephropathy', 'complement_platform'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Narsoplimab (anti-MASP-2)', indication: 'Immunology (IgAN/aHUS/HSCT-TMA)', revenue_usd: 300000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'BioCryst Pharmaceuticals',
    name_variations: ['BioCryst', 'BioCryst Pharmaceuticals Inc'],
    ticker: 'BCRX',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'rare_disease'],
    indications_specific: ['hereditary_angioedema', 'complement_disorders'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'europe', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 6,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['oral_hae', 'kallikrein_inhibition', 'complement_pathway', 'rare_immunology'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Orladeyo (berotralstat)', indication: 'Immunology (Hereditary Angioedema)', revenue_usd: 500000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Pharvaris',
    name_variations: ['Pharvaris NV', 'Pharvaris BV'],
    ticker: 'PHVS',
    company_type: 'mid_biotech',
    hq_country: 'Netherlands',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'rare_disease'],
    indications_specific: ['hereditary_angioedema'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'europe', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oral_hae_prophylaxis', 'bradykinin_b2_antagonist', 'hae_acute', 'oral_rare_immunology'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Deucrictibant (PHVS416)', indication: 'Immunology (Hereditary Angioedema)', revenue_usd: 400000000, expiry_year: 2040 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ASIAN PHARMA ACTIVE IN IMMUNOLOGY
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Chugai Pharmaceutical',
    name_variations: ['Chugai', 'Chugai Pharma', 'Chugai Pharmaceutical Co.'],
    ticker: '4519.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['antibody', 'bispecific', 'small_molecule'],
    modalities_primary: ['antibody'],
    indications_active: ['immunology', 'neurology', 'oncology', 'hematology'],
    indications_specific: ['neuromyelitis_optica', 'myasthenia_gravis', 'rheumatoid_arthritis', 'giant_cell_arteritis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['japan', 'global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 15,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['il6_recycling_antibody', 'nmo', 'autoimmune_neurology', 'next_gen_antibody_engineering'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Enspryng (satralizumab)', indication: 'Immunology (Neuromyelitis Optica)', revenue_usd: 500000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Zai Lab',
    name_variations: ['Zai Lab Limited', 'Zai Lab Ltd'],
    ticker: 'ZLAB',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['antibody', 'small_molecule', 'adc'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['immunology', 'oncology', 'neurology'],
    indications_specific: ['autoimmune_diseases', 'lupus', 'ibd', 'atopic_dermatitis'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'asia_pacific'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['china_immunology_licensing', 'autoimmune_china', 'in_licensing_biologics', 'asia_market_access'],
    data_quality_score: 72,
    patent_cliffs: [],
  },
  {
    name: 'Hutchmed',
    name_variations: ['Hutchmed (China) Limited', 'Hutchison MediPharma', 'HUTCHMED'],
    ticker: 'HCM',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'oncology'],
    indications_specific: ['ulcerative_colitis', 'crohns_disease', 'rheumatoid_arthritis', 'autoimmune_diseases'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['selective_jak1', 'oral_autoimmune', 'ibd_china', 'autoimmune_pipeline'],
    data_quality_score: 68,
    patent_cliffs: [],
  },
  {
    name: 'RemeGen',
    name_variations: ['RemeGen Co. Ltd', 'RemeGen Biosciences'],
    ticker: '9995.HK',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['adc', 'fusion_protein', 'antibody'],
    modalities_primary: ['adc', 'fusion_protein'],
    indications_active: ['immunology', 'oncology'],
    indications_specific: ['systemic_lupus_erythematosus', 'lupus_nephritis', 'rheumatoid_arthritis', 'autoimmune_diseases'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['adc_autoimmune', 'lupus', 'b_cell_depletion_adc', 'fusion_protein_immunology'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Telitacicept (BLyS/APRIL dual)', indication: 'Immunology (SLE/Lupus Nephritis/RA)', revenue_usd: 400000000, expiry_year: 2036 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ADDITIONAL IMMUNOLOGY-FOCUSED COMPANIES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Eli Lilly',
    name_variations: ['Lilly', 'Eli Lilly and Company'],
    ticker: 'LLY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'fusion_protein'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['immunology', 'metabolic', 'oncology', 'neuroscience'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'atopic_dermatitis', 'alopecia_areata', 'vitiligo', 'hidradenitis_suppurativa'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 35,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['il13_il17_franchise', 'jak_dermatology', 'tl1a', 'tyk2', 'next_gen_autoimmune'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Taltz (ixekizumab)', indication: 'Immunology (Psoriasis/PsA/AS)', revenue_usd: 2800000000, expiry_year: 2029 },
      { drug_name: 'Olumiant (baricitinib)', indication: 'Immunology (RA/AD/Alopecia)', revenue_usd: 1200000000, expiry_year: 2029 },
      { drug_name: 'Ebglyss (lebrikizumab)', indication: 'Immunology (Atopic Dermatitis)', revenue_usd: 800000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Amgen',
    name_variations: ['Amgen Inc.', 'Amgen Inc'],
    ticker: 'AMGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'bispecific', 'small_molecule', 'fusion_protein'],
    modalities_primary: ['antibody', 'bispecific'],
    indications_active: ['immunology', 'oncology', 'hematology', 'cardiovascular'],
    indications_specific: ['psoriasis', 'psoriatic_arthritis', 'atopic_dermatitis', 'asthma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 30,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['inflammatory_pipeline', 'horizon_integration', 'rare_autoimmune', 'tepezza_expansion', 'bispecific_immunology'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Otezla (apremilast)', indication: 'Immunology (Psoriasis/PsA)', revenue_usd: 2400000000, expiry_year: 2028 },
      { drug_name: 'Enbrel (etanercept)', indication: 'Immunology (RA/PsA/AS/Psoriasis)', revenue_usd: 3600000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Bristol-Myers Squibb',
    name_variations: ['BMS', 'Bristol Myers Squibb', 'Bristol-Myers Squibb Company'],
    ticker: 'BMY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'protein_degrader'],
    modalities_primary: ['small_molecule'],
    indications_active: ['immunology', 'oncology', 'hematology', 'cardiovascular'],
    indications_specific: ['psoriasis', 'lupus', 'ibd', 'multiple_sclerosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 25,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['tyk2_franchise', 'oral_autoimmune', 'protein_degradation_immunology', 'next_gen_immunomodulators'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Sotyktu (deucravacitinib)', indication: 'Immunology (Psoriasis)', revenue_usd: 600000000, expiry_year: 2036 },
      { drug_name: 'Orencia (abatacept)', indication: 'Immunology (RA/JIA)', revenue_usd: 3400000000, expiry_year: 2026 },
      { drug_name: 'Zeposia (ozanimod)', indication: 'Immunology (MS/UC)', revenue_usd: 800000000, expiry_year: 2034 },
    ],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedImmunologyCompanies() {
  console.log('Starting immunology company seed...\n');
  console.log(`Seeding ${immunologyCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of immunologyCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      therapeutic_area: 'immunology',
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with immunology data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${immunologyCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedImmunologyCompanies().catch(console.error);
