// Script to seed metabolic/endocrine-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-metabolic-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes metabolic-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for metabolic assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface MetabolicCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// METABOLIC / ENDOCRINE COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const metabolicCompanies: MetabolicCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA WITH DOMINANT METABOLIC FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Novo Nordisk',
    name_variations: ['Novo Nordisk A/S', 'Novo'],
    ticker: 'NVO',
    company_type: 'large_pharma',
    hq_country: 'Denmark',
    modalities_active: ['peptide', 'small_molecule', 'antibody', 'gene_therapy'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'cardiovascular', 'rare_disease', 'hematology'],
    indications_specific: ['type_2_diabetes', 'obesity', 'nash_mash', 'type_1_diabetes', 'ckd', 'heart_failure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 65,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['glp1_franchise', 'obesity', 'next_gen_incretin', 'oral_glp1', 'cardiometabolic'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Ozempic (semaglutide)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 18000000000, expiry_year: 2031 },
      { drug_name: 'Wegovy (semaglutide)', indication: 'Metabolic (Obesity)', revenue_usd: 8000000000, expiry_year: 2032 },
      { drug_name: 'Rybelsus (oral semaglutide)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 3500000000, expiry_year: 2031 },
      { drug_name: 'Victoza (liraglutide)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 2000000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Eli Lilly',
    name_variations: ['Lilly', 'Eli Lilly and Company'],
    ticker: 'LLY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['peptide', 'small_molecule', 'antibody'],
    modalities_primary: ['peptide', 'small_molecule'],
    indications_active: ['metabolic', 'oncology', 'neurology', 'autoimmune'],
    indications_specific: ['type_2_diabetes', 'obesity', 'nash_mash', 'type_1_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 55,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['tirzepatide_expansion', 'obesity', 'next_gen_incretin', 'retatrutide', 'orforglipron'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Mounjaro (tirzepatide)', indication: 'Metabolic (Type 2 Diabetes GLP-1/GIP)', revenue_usd: 12000000000, expiry_year: 2036 },
      { drug_name: 'Zepbound (tirzepatide)', indication: 'Metabolic (Obesity)', revenue_usd: 5000000000, expiry_year: 2036 },
      { drug_name: 'Trulicity (dulaglutide)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 5500000000, expiry_year: 2027 },
      { drug_name: 'Jardiance (empagliflozin)', indication: 'Metabolic (Type 2 Diabetes/HF)', revenue_usd: 3000000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Sanofi',
    name_variations: ['Sanofi S.A.', 'Sanofi-Aventis'],
    ticker: 'SNY',
    company_type: 'large_pharma',
    hq_country: 'France',
    modalities_active: ['peptide', 'small_molecule', 'antibody', 'insulin'],
    modalities_primary: ['insulin', 'antibody'],
    indications_active: ['metabolic', 'autoimmune', 'rare_disease', 'oncology'],
    indications_specific: ['type_1_diabetes', 'type_2_diabetes', 'insulin_therapy'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 25,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['insulin_portfolio', 'immunology', 'rare_disease', 'metabolic_rare'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Lantus (insulin glargine)', indication: 'Metabolic (Diabetes Insulin)', revenue_usd: 2500000000, expiry_year: 2025 },
      { drug_name: 'Toujeo (insulin glargine 300)', indication: 'Metabolic (Diabetes Insulin)', revenue_usd: 1800000000, expiry_year: 2028 },
      { drug_name: 'Soliqua (insulin glargine/lixisenatide)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 500000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'peptide', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'cardiovascular', 'oncology', 'respiratory'],
    indications_specific: ['type_2_diabetes', 'ckd', 'heart_failure', 'hyperkalemia', 'nash_mash'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 35,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['sglt2_expansion', 'cardiorenal', 'ckd', 'nash_mash', 'metabolic_cv'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Farxiga (dapagliflozin)', indication: 'Metabolic (Type 2 Diabetes/CKD/HF)', revenue_usd: 6500000000, expiry_year: 2028 },
      { drug_name: 'Lokelma (sodium zirconium cyclosilicate)', indication: 'Metabolic (Hyperkalemia)', revenue_usd: 800000000, expiry_year: 2031 },
    ],
  },
  {
    name: 'Merck',
    name_variations: ['Merck & Co.', 'Merck Sharp & Dohme', 'MSD'],
    ticker: 'MRK',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'oncology', 'cardiovascular', 'infectious_disease'],
    indications_specific: ['type_2_diabetes', 'obesity', 'nash_mash'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 20,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['post_keytruda_diversification', 'obesity', 'metabolic_pipeline', 'cardiometabolic'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Januvia (sitagliptin)', indication: 'Metabolic (Type 2 Diabetes DPP-4)', revenue_usd: 3000000000, expiry_year: 2026 },
      { drug_name: 'Janumet (sitagliptin/metformin)', indication: 'Metabolic (Type 2 Diabetes)', revenue_usd: 2000000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Boehringer Ingelheim',
    name_variations: ['Boehringer', 'BI', 'Boehringer Ingelheim GmbH'],
    ticker: null,
    company_type: 'large_pharma',
    hq_country: 'Germany',
    modalities_active: ['small_molecule', 'peptide', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'cardiovascular', 'respiratory', 'oncology'],
    indications_specific: ['type_2_diabetes', 'heart_failure', 'ckd', 'nash_mash', 'obesity'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 30,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['sglt2_franchise', 'cardiorenal', 'nash_mash', 'obesity', 'survodutide'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Jardiance (empagliflozin, co-develop w/ Lilly)', indication: 'Metabolic (Type 2 Diabetes/HF/CKD)', revenue_usd: 7000000000, expiry_year: 2028 },
      { drug_name: 'Trajenta (linagliptin)', indication: 'Metabolic (Type 2 Diabetes DPP-4)', revenue_usd: 1200000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Pfizer',
    name_variations: ['Pfizer Inc.', 'Pfizer Inc'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'peptide', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'oncology', 'autoimmune', 'cardiovascular'],
    indications_specific: ['obesity', 'type_2_diabetes', 'nash_mash'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 18,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['oral_glp1', 'danuglipron', 'obesity', 'metabolic_pipeline'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Danuglipron (oral GLP-1)', indication: 'Metabolic (Obesity/Type 2 Diabetes)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Amgen',
    name_variations: ['Amgen Inc.', 'Amgen Inc'],
    ticker: 'AMGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['peptide', 'antibody', 'bispecific', 'small_molecule'],
    modalities_primary: ['peptide', 'antibody'],
    indications_active: ['metabolic', 'oncology', 'cardiovascular', 'rare_disease'],
    indications_specific: ['obesity', 'type_2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 15,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['obesity', 'amg133_maridebart', 'glp1_gip', 'cardiometabolic'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'MariTide (maridebart cafraglutide, AMG 133)', indication: 'Metabolic (Obesity GLP-1/GIPR)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP METABOLIC / NASH-MASH SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Madrigal Pharmaceuticals',
    name_variations: ['Madrigal', 'Madrigal Pharmaceuticals Inc'],
    ticker: 'MDGL',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'liver_fibrosis', 'nafld'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['rezdiffra_launch', 'nash_mash', 'thrbeta_agonist', 'liver_fibrosis'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Rezdiffra (resmetirom)', indication: 'Metabolic (NASH/MASH THRbeta)', revenue_usd: 2000000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Akero Therapeutics',
    name_variations: ['Akero', 'Akero Therapeutics Inc'],
    ticker: 'AKRO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['recombinant_protein'],
    modalities_primary: ['recombinant_protein'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'liver_fibrosis', 'metabolic_liver_disease'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['efruxifermin', 'fgf21_analog', 'nash_mash', 'liver_fibrosis_resolution'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Efruxifermin (EFX)', indication: 'Metabolic (NASH/MASH FGF21)', revenue_usd: 1500000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Viking Therapeutics',
    name_variations: ['Viking', 'Viking Therapeutics Inc'],
    ticker: 'VKTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'nash_mash', 'type_2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['vk2735_glp1_gip', 'obesity', 'subq_oral_formulations', 'nash_mash'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'VK2735', indication: 'Metabolic (Obesity GLP-1/GIP Dual Agonist)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },
  {
    name: 'Structure Therapeutics',
    name_variations: ['Structure', 'Structure Therapeutics Inc', 'Grit Biotechnology'],
    ticker: 'GPCR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'type_2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oral_glp1_agonist', 'gpcr_platform', 'obesity', 'small_molecule_incretin'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'GSBR-1290 (oral GLP-1)', indication: 'Metabolic (Obesity/T2D Oral GLP-1)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },
  {
    name: 'Fractyl Health',
    name_variations: ['Fractyl', 'Fractyl Laboratories', 'Fractyl Health Inc'],
    ticker: 'GUTS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['device', 'gene_therapy'],
    modalities_primary: ['device'],
    indications_active: ['metabolic'],
    indications_specific: ['type_2_diabetes', 'obesity', 'metabolic_syndrome'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['revita_dmr', 'duodenal_mucosal_resurfacing', 'gene_therapy_metabolic', 'diabetes_remission'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'Revita DMR', indication: 'Metabolic (Type 2 Diabetes Duodenal Resurfacing)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Zealand Pharma',
    name_variations: ['Zealand', 'Zealand Pharma A/S'],
    ticker: 'ZEAL',
    company_type: 'mid_biotech',
    hq_country: 'Denmark',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'rare_disease', 'gi'],
    indications_specific: ['obesity', 'type_2_diabetes', 'short_bowel_syndrome', 'congenital_hyperinsulinism'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['peptide_platform', 'survodutide_partnership', 'glucagon_glp1', 'rare_metabolic'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Survodutide (partnered with BI)', indication: 'Metabolic (Obesity/NASH Glucagon/GLP-1)', revenue_usd: 0, expiry_year: 2040 },
      { drug_name: 'Glepaglutide', indication: 'Metabolic (Short Bowel Syndrome GLP-2)', revenue_usd: 300000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Carmot Therapeutics (Roche)',
    name_variations: ['Carmot', 'Carmot Therapeutics', 'Roche Carmot'],
    ticker: 'RHHBY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'type_2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 6,
    avg_upfront_usd: 2700000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['glp1_franchise_build', 'obesity', 'next_gen_incretin', 'injectable_oral'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'CT-996 (oral GLP-1)', indication: 'Metabolic (Obesity/T2D Oral GLP-1)', revenue_usd: 0, expiry_year: 2041 },
      { drug_name: 'CT-388 (GLP-1/GIP)', indication: 'Metabolic (Obesity GLP-1/GIP)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },
  {
    name: 'Intercept Pharmaceuticals',
    name_variations: ['Intercept', 'Intercept Pharmaceuticals Inc'],
    ticker: 'ICPT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'pbc', 'liver_fibrosis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['oca_nash', 'fxr_agonist', 'liver_disease', 'pbc'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Ocaliva (obeticholic acid)', indication: 'Metabolic (PBC FXR Agonist)', revenue_usd: 400000000, expiry_year: 2032 },
    ],
  },
  {
    name: '89bio',
    name_variations: ['89bio Inc', '89bio Inc.'],
    ticker: 'ETNB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['recombinant_protein'],
    modalities_primary: ['recombinant_protein'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'hypertriglyceridemia', 'liver_fibrosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['pegozafermin', 'fgf21_analog', 'nash_mash', 'severe_hypertriglyceridemia'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Pegozafermin', indication: 'Metabolic (NASH/MASH FGF21)', revenue_usd: 0, expiry_year: 2039 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // CARDIOMETABOLIC / RNA / SPECIALTY
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Ionis Pharmaceuticals',
    name_variations: ['Ionis', 'Ionis Pharmaceuticals Inc', 'Isis Pharmaceuticals'],
    ticker: 'IONS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antisense_oligonucleotide', 'rna_therapeutics'],
    modalities_primary: ['antisense_oligonucleotide'],
    indications_active: ['metabolic', 'cardiovascular', 'neurology', 'rare_disease'],
    indications_specific: ['hypertriglyceridemia', 'apoc3', 'angptl3', 'lpa', 'cardiometabolic'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 20,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['antisense_cardiometabolic', 'angptl3', 'apoc3', 'lpa_lowering', 'rna_platform'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Waylivra (volanesorsen)', indication: 'Metabolic (FCS/Hypertriglyceridemia)', revenue_usd: 100000000, expiry_year: 2033 },
      { drug_name: 'Olezarsen (ApoC-III ASO)', indication: 'Metabolic (Hypertriglyceridemia)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Alnylam Pharmaceuticals',
    name_variations: ['Alnylam', 'Alnylam Pharmaceuticals Inc'],
    ticker: 'ALNY',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['rna_therapeutics', 'sirna'],
    modalities_primary: ['sirna'],
    indications_active: ['metabolic', 'cardiovascular', 'neurology', 'rare_disease'],
    indications_specific: ['hypertension', 'lpa', 'nash_mash', 'cardiometabolic'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 18,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rnai_cardiometabolic', 'zilebesiran', 'lpa_sirna', 'metabolic_liver'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Zilebesiran (AGT siRNA)', indication: 'Metabolic/CV (Hypertension RNAi)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },
  {
    name: 'Regeneron Pharmaceuticals',
    name_variations: ['Regeneron', 'Regeneron Pharmaceuticals Inc'],
    ticker: 'REGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'gene_therapy'],
    modalities_primary: ['antibody'],
    indications_active: ['metabolic', 'cardiovascular', 'ophthalmology', 'autoimmune'],
    indications_specific: ['hypercholesterolemia', 'cardiovascular_risk', 'obesity'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 30,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['pcsk9_franchise', 'cardiometabolic', 'obesity_antibody', 'genetics_driven'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Praluent (alirocumab)', indication: 'Metabolic/CV (Hypercholesterolemia PCSK9)', revenue_usd: 600000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Lexicon Pharmaceuticals',
    name_variations: ['Lexicon', 'Lexicon Pharmaceuticals Inc'],
    ticker: 'LXRX',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'cardiovascular'],
    indications_specific: ['type_1_diabetes', 'heart_failure', 'type_2_diabetes'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['sotagliflozin', 'sglt1_sglt2', 'heart_failure', 'type_1_diabetes'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Inpefa (sotagliflozin)', indication: 'Metabolic/CV (Heart Failure SGLT1/2)', revenue_usd: 400000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Ultragenyx Pharmaceutical',
    name_variations: ['Ultragenyx', 'Ultragenyx Pharmaceutical Inc'],
    ticker: 'RARE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['enzyme_replacement', 'gene_therapy', 'antibody', 'small_molecule'],
    modalities_primary: ['enzyme_replacement', 'gene_therapy'],
    indications_active: ['metabolic', 'rare_disease'],
    indications_specific: ['xlh', 'hph', 'osteogenesis_imperfecta', 'glycogen_storage', 'pku'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 12,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_metabolic', 'gene_therapy_metabolic', 'enzyme_replacement', 'bone_metabolism'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Crysvita (burosumab)', indication: 'Metabolic (XLH Rare Bone)', revenue_usd: 800000000, expiry_year: 2033 },
      { drug_name: 'Mepsevii (vestronidase alfa)', indication: 'Metabolic (MPS VII Enzyme Replacement)', revenue_usd: 50000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'BioMarin Pharmaceutical',
    name_variations: ['BioMarin', 'BioMarin Pharmaceutical Inc'],
    ticker: 'BMRN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['enzyme_replacement', 'gene_therapy', 'small_molecule'],
    modalities_primary: ['enzyme_replacement'],
    indications_active: ['metabolic', 'rare_disease'],
    indications_specific: ['pku', 'achondroplasia', 'mps', 'cln2'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 14,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_metabolic', 'enzyme_replacement', 'achondroplasia', 'pku', 'gene_therapy'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Voxzogo (vosoritide)', indication: 'Metabolic (Achondroplasia)', revenue_usd: 700000000, expiry_year: 2036 },
      { drug_name: 'Palynziq (pegvaliase)', indication: 'Metabolic (PKU Enzyme Substitution)', revenue_usd: 400000000, expiry_year: 2032 },
      { drug_name: 'Kuvan (sapropterin)', indication: 'Metabolic (PKU)', revenue_usd: 500000000, expiry_year: 2027 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ASIAN PHARMA ACTIVE IN METABOLIC
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Daiichi Sankyo',
    name_variations: ['Daiichi Sankyo Co.', 'Daiichi Sankyo Inc.'],
    ticker: '4568.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody', 'adc'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'cardiovascular', 'oncology'],
    indications_specific: ['type_2_diabetes', 'dyslipidemia', 'hypertension'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 15,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['cardiometabolic', 'dyslipidemia', 'diabetes', 'japan_metabolic'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Tenelia (teneligliptin)', indication: 'Metabolic (Type 2 Diabetes DPP-4)', revenue_usd: 300000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Astellas Pharma',
    name_variations: ['Astellas', 'Astellas Pharma Inc.'],
    ticker: '4503.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'oncology', 'urology'],
    indications_specific: ['type_2_diabetes', 'diabetic_kidney_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 12,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['cardiometabolic_expansion', 'diabetes', 'renal_metabolic', 'japan_metabolic'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Suglat (ipragliflozin)', indication: 'Metabolic (Type 2 Diabetes SGLT2)', revenue_usd: 400000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Ono Pharmaceutical',
    name_variations: ['Ono', 'Ono Pharmaceutical Co.', 'Ono Pharma'],
    ticker: '4528.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'oncology', 'autoimmune'],
    indications_specific: ['type_2_diabetes', 'obesity', 'dyslipidemia'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['japan', 'asia'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['diabetes', 'obesity', 'cardiometabolic', 'japan_first'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Forxiga (dapagliflozin, Japan rights)', indication: 'Metabolic (Type 2 Diabetes SGLT2)', revenue_usd: 300000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Sumitomo Pharma',
    name_variations: ['Sumitomo', 'Sumitomo Pharma Co.', 'Sumitomo Dainippon Pharma'],
    ticker: '4506.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'cell_therapy', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic', 'psychiatry', 'oncology'],
    indications_specific: ['type_2_diabetes', 'obesity'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['japan', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['metabolic_pipeline', 'diabetes', 'regenerative_medicine', 'japan_metabolic'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Equa (vildagliptin, Japan)', indication: 'Metabolic (Type 2 Diabetes DPP-4)', revenue_usd: 200000000, expiry_year: 2026 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ADDITIONAL METABOLIC SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Inventiva',
    name_variations: ['Inventiva S.A.', 'Inventiva Pharma'],
    ticker: 'IVA',
    company_type: 'mid_biotech',
    hq_country: 'France',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'liver_fibrosis', 'mps'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['lanifibranor', 'ppar_agonist', 'nash_mash', 'liver_fibrosis'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Lanifibranor (pan-PPAR agonist)', indication: 'Metabolic (NASH/MASH PPARa/d/g)', revenue_usd: 0, expiry_year: 2038 },
    ],
  },
  {
    name: 'Hanmi Pharmaceutical',
    name_variations: ['Hanmi', 'Hanmi Pharm Co.'],
    ticker: '128940.KS',
    company_type: 'mid_pharma',
    hq_country: 'South Korea',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic', 'oncology'],
    indications_specific: ['obesity', 'type_2_diabetes', 'nash_mash'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global', 'asia'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['triple_agonist', 'glp1_gip_glucagon', 'obesity', 'long_acting_peptide'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Efinopegdutide (GLP-1/Glucagon)', indication: 'Metabolic (Obesity/NASH Dual Agonist)', revenue_usd: 0, expiry_year: 2039 },
    ],
  },
  {
    name: 'Altimmune',
    name_variations: ['Altimmune Inc', 'Altimmune Inc.'],
    ticker: 'ALT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'nash_mash', 'type_2_diabetes'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['pemvidutide', 'glp1_glucagon_dual', 'obesity', 'nash_mash'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'Pemvidutide (GLP-1/Glucagon)', indication: 'Metabolic (Obesity/NASH GLP-1/Glucagon)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Echosens',
    name_variations: ['Echosens SA'],
    ticker: null,
    company_type: 'specialty',
    hq_country: 'France',
    modalities_active: ['diagnostic'],
    modalities_primary: ['diagnostic'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'liver_fibrosis', 'nafld'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 0,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['fibroscan', 'liver_diagnostics', 'nash_mash_staging', 'companion_diagnostic'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'FibroScan', indication: 'Metabolic (NASH/MASH Liver Diagnostic)', revenue_usd: 300000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Terns Pharmaceuticals',
    name_variations: ['Terns', 'Terns Pharmaceuticals Inc'],
    ticker: 'TERN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['metabolic'],
    indications_specific: ['nash_mash', 'obesity', 'liver_fibrosis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['tern_501_glp1', 'nash_mash', 'fxr_agonist', 'metabolic_pipeline'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'TERN-501 (THRbeta)', indication: 'Metabolic (NASH/MASH THRbeta Agonist)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Novo Holdings / Catalent (Novo Nordisk)',
    name_variations: ['Novo Holdings', 'Catalent', 'Catalent Inc'],
    ticker: null,
    company_type: 'large_pharma',
    hq_country: 'Denmark',
    modalities_active: ['manufacturing', 'cdmo'],
    modalities_primary: ['manufacturing'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'type_2_diabetes', 'glp1_manufacturing'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 0,
    avg_upfront_usd: 16500000000,
    median_upfront_usd: 16500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['glp1_manufacturing_capacity', 'fill_finish', 'supply_chain', 'cdmo_integration'],
    data_quality_score: 72,
    patent_cliffs: [],
  },
  {
    name: 'Sciwind Biosciences',
    name_variations: ['Sciwind', 'Sciwind Biosciences Co.'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['peptide', 'small_molecule'],
    modalities_primary: ['peptide'],
    indications_active: ['metabolic'],
    indications_specific: ['obesity', 'type_2_diabetes', 'nash_mash'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['china', 'asia', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['oral_glp1', 'obesity_china', 'incretin_pipeline', 'china_metabolic'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'Ecnoglutide (XW003)', indication: 'Metabolic (Obesity/T2D GLP-1)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Tonghua Dongbao',
    name_variations: ['Tonghua Dongbao Pharmaceutical', 'THDB'],
    ticker: '600867.SS',
    company_type: 'mid_pharma',
    hq_country: 'China',
    modalities_active: ['peptide', 'insulin', 'small_molecule'],
    modalities_primary: ['insulin', 'peptide'],
    indications_active: ['metabolic'],
    indications_specific: ['type_2_diabetes', 'obesity', 'insulin_therapy'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'asia'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['insulin_biosimilars', 'glp1_china', 'diabetes_china', 'affordable_metabolic'],
    data_quality_score: 58,
    patent_cliffs: [
      { drug_name: 'Insulin Glargine (biosimilar)', indication: 'Metabolic (Diabetes Insulin China)', revenue_usd: 600000000, expiry_year: 2030 },
    ],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedMetabolicCompanies() {
  console.log('Starting metabolic company seed...\n');
  console.log(`Seeding ${metabolicCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of metabolicCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with metabolic data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${metabolicCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedMetabolicCompanies().catch(console.error);
