// Script to seed rare disease-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-rare-disease-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes rare disease-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for rare disease assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface RareDiseaseCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// RARE DISEASE COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const rareDiseaseCompanies: RareDiseaseCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA / BIOTECH WITH MAJOR RARE DISEASE FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Alexion (AstraZeneca)',
    name_variations: ['Alexion Pharmaceuticals', 'Alexion', 'AstraZeneca Rare Disease'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'gene_therapy', 'enzyme_replacement'],
    modalities_primary: ['antibody', 'enzyme_replacement'],
    indications_active: ['rare_disease', 'hematology', 'nephrology', 'neurology'],
    indications_specific: ['pnh', 'ahus', 'myasthenia_gravis', 'nmosd', 'hppsc', 'wilson_disease'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 35,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['complement_biology', 'rare_hematology', 'rare_neurology', 'enzyme_replacement', 'gene_therapy'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Soliris (eculizumab)', indication: 'Rare Disease (PNH/aHUS)', revenue_usd: 3800000000, expiry_year: 2027 },
      { drug_name: 'Ultomiris (ravulizumab)', indication: 'Rare Disease (PNH/aHUS/MG)', revenue_usd: 4200000000, expiry_year: 2035 },
      { drug_name: 'Strensiq', indication: 'Rare Disease (HPP)', revenue_usd: 1100000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'BioMarin',
    name_variations: ['BioMarin Pharmaceutical', 'BioMarin Inc.'],
    ticker: 'BMRN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['enzyme_replacement', 'gene_therapy', 'small_molecule'],
    modalities_primary: ['enzyme_replacement', 'gene_therapy'],
    indications_active: ['rare_disease'],
    indications_specific: ['hemophilia_a', 'achondroplasia', 'pku', 'mps', 'cln2'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 22,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['gene_therapy_rare', 'enzyme_replacement', 'hemophilia', 'skeletal_dysplasia', 'lysosomal_storage'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Voxzogo (vosoritide)', indication: 'Rare Disease (Achondroplasia)', revenue_usd: 800000000, expiry_year: 2036 },
      { drug_name: 'Roctavian (valoctocogene)', indication: 'Rare Disease (Hemophilia A)', revenue_usd: 400000000, expiry_year: 2038 },
      { drug_name: 'Naglazyme', indication: 'Rare Disease (MPS VI)', revenue_usd: 400000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Ultragenyx',
    name_variations: ['Ultragenyx Pharmaceutical', 'Ultragenyx Inc.'],
    ticker: 'RARE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'enzyme_replacement', 'antibody'],
    modalities_primary: ['gene_therapy', 'enzyme_replacement'],
    indications_active: ['rare_disease'],
    indications_specific: ['osteogenesis_imperfecta', 'angelman_syndrome', 'glycogen_storage', 'mps', 'wilson_disease'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 18,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['gene_therapy_rare', 'bone_disease', 'metabolic_rare', 'aav_gene_therapy'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Crysvita (burosumab)', indication: 'Rare Disease (XLH)', revenue_usd: 700000000, expiry_year: 2033 },
      { drug_name: 'Dojolvi', indication: 'Rare Disease (LC-FAOD)', revenue_usd: 120000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Sarepta Therapeutics',
    name_variations: ['Sarepta', 'Sarepta Inc.'],
    ticker: 'SRPT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'aso', 'rna'],
    modalities_primary: ['gene_therapy', 'aso'],
    indications_active: ['rare_disease', 'neurology'],
    indications_specific: ['dmd', 'lgmd', 'charcot_marie_tooth', 'pompe'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 7,
    active_trials_count: 20,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['gene_therapy_neuromuscular', 'dmd', 'lgmd', 'aav_platform', 'exon_skipping'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Elevidys (delandistrogene)', indication: 'Rare Disease (DMD Gene Therapy)', revenue_usd: 1500000000, expiry_year: 2038 },
      { drug_name: 'Exondys 51', indication: 'Rare Disease (DMD Exon 51)', revenue_usd: 600000000, expiry_year: 2031 },
    ],
  },
  {
    name: 'Vertex Pharmaceuticals',
    name_variations: ['Vertex', 'Vertex Inc.'],
    ticker: 'VRTX',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'gene_editing', 'cell_therapy', 'mrna'],
    modalities_primary: ['small_molecule', 'gene_editing'],
    indications_active: ['rare_disease', 'hematology', 'pain'],
    indications_specific: ['cystic_fibrosis', 'sickle_cell', 'beta_thalassemia', 'ttpn', 'dm1'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 30,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['cystic_fibrosis', 'gene_editing', 'sickle_cell', 'pain', 'kidney_disease'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Trikafta/Kaftrio', indication: 'Rare Disease (Cystic Fibrosis)', revenue_usd: 9000000000, expiry_year: 2037 },
      { drug_name: 'Casgevy (exagamglogene)', indication: 'Rare Disease (SCD/Beta-Thal)', revenue_usd: 500000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'Alnylam Pharmaceuticals',
    name_variations: ['Alnylam', 'Alnylam Inc.'],
    ticker: 'ALNY',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['rnai', 'sirna'],
    modalities_primary: ['rnai', 'sirna'],
    indications_active: ['rare_disease', 'cardiovascular', 'hepatology'],
    indications_specific: ['hattr', 'ahp', 'primary_hyperoxaluria', 'complement_mediated'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 20,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rnai_therapeutics', 'hattr', 'complement_diseases', 'liver_targeted_rare'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Onpattro (patisiran)', indication: 'Rare Disease (hATTR)', revenue_usd: 500000000, expiry_year: 2030 },
      { drug_name: 'Amvuttra (vutrisiran)', indication: 'Rare Disease (hATTR)', revenue_usd: 1200000000, expiry_year: 2037 },
      { drug_name: 'Givlaari', indication: 'Rare Disease (AHP)', revenue_usd: 300000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Ionis Pharmaceuticals',
    name_variations: ['Ionis', 'Isis Pharmaceuticals'],
    ticker: 'IONS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['aso', 'oligonucleotide'],
    modalities_primary: ['aso'],
    indications_active: ['rare_disease', 'cns', 'cardiovascular'],
    indications_specific: ['sma', 'hattr', 'huntingtons', 'als', 'complement_mediated'],
    phase_preference_min: 'discovery',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 25,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['antisense_rare', 'neuromuscular', 'complement', 'rare_cardio'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Spinraza (nusinersen)', indication: 'Rare Disease (SMA)', revenue_usd: 1700000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Takeda (Rare Disease Unit)',
    name_variations: ['Takeda Pharmaceutical', 'Takeda Rare Diseases', 'Shire'],
    ticker: 'TAK',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['enzyme_replacement', 'gene_therapy', 'small_molecule', 'cell_therapy'],
    modalities_primary: ['enzyme_replacement', 'gene_therapy'],
    indications_active: ['rare_disease', 'hematology', 'gi', 'cns'],
    indications_specific: ['hae', 'fabry', 'hunter_syndrome', 'gaucher', 'hemophilia'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 28,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['rare_hematology', 'hereditary_angioedema', 'lysosomal_storage', 'gene_therapy_rare'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Takhzyro (lanadelumab)', indication: 'Rare Disease (HAE)', revenue_usd: 1800000000, expiry_year: 2033 },
      { drug_name: 'Elaprase', indication: 'Rare Disease (Hunter Syndrome)', revenue_usd: 800000000, expiry_year: 2027 },
      { drug_name: 'Replagal', indication: 'Rare Disease (Fabry)', revenue_usd: 700000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Horizon Therapeutics (Amgen)',
    name_variations: ['Horizon Pharma', 'Horizon Therapeutics', 'Amgen Rare Disease'],
    ticker: 'AMGN',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'enzyme_replacement'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['rare_disease', 'autoimmune', 'endocrinology'],
    indications_specific: ['thyroid_eye_disease', 'gout', 'rare_autoimmune', 'myasthenia_gravis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 15,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['rare_autoimmune', 'thyroid_eye_disease', 'inflammation_rare', 'gout'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Tepezza (teprotumumab)', indication: 'Rare Disease (TED)', revenue_usd: 2000000000, expiry_year: 2034 },
      { drug_name: 'Krystexxa (pegloticase)', indication: 'Rare Disease (Chronic Gout)', revenue_usd: 900000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Bluebird Bio',
    name_variations: ['bluebird bio', 'Bluebird', 'bluebird bio Inc.'],
    ticker: 'BLUE',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'cell_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['rare_disease', 'hematology'],
    indications_specific: ['sickle_cell', 'beta_thalassemia', 'cerebral_adrenoleukodystrophy'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['gene_therapy_hematology', 'sickle_cell', 'beta_thalassemia', 'lentiviral_gene_therapy'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Lyfgenia (lovotibeglogene)', indication: 'Rare Disease (Sickle Cell)', revenue_usd: 300000000, expiry_year: 2038 },
      { drug_name: 'Zynteglo (betibeglogene)', indication: 'Rare Disease (Beta-Thalassemia)', revenue_usd: 150000000, expiry_year: 2036 },
      { drug_name: 'Skysona (elivaldogene)', indication: 'Rare Disease (CALD)', revenue_usd: 80000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Regeneron',
    name_variations: ['Regeneron Pharmaceuticals', 'Regeneron Inc.'],
    ticker: 'REGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'gene_therapy', 'rnai'],
    modalities_primary: ['antibody'],
    indications_active: ['rare_disease', 'oncology', 'autoimmune', 'ophthalmology'],
    indications_specific: ['hattr', 'rare_eye_disease', 'hfh', 'rare_autoimmune'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 40,
    avg_upfront_usd: 800000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['genetics_driven_rare', 'antibody_platform', 'gene_therapy', 'rare_complement'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Dupixent (dupilumab)', indication: 'Multiple (Atopic Dermatitis/Asthma)', revenue_usd: 13000000000, expiry_year: 2031 },
      { drug_name: 'Praluent (alirocumab)', indication: 'Rare Disease (HoFH)', revenue_usd: 400000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Novo Nordisk (Rare Blood Disorders)',
    name_variations: ['Novo Nordisk', 'Novo Nordisk A/S', 'Novo Nordisk Rare Disease'],
    ticker: 'NVO',
    company_type: 'large_pharma',
    hq_country: 'Denmark',
    modalities_active: ['antibody', 'recombinant_protein', 'gene_therapy'],
    modalities_primary: ['recombinant_protein'],
    indications_active: ['rare_disease', 'hematology', 'metabolic'],
    indications_specific: ['hemophilia_a', 'hemophilia_b', 'rare_bleeding', 'sickle_cell'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 15,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_hematology', 'hemophilia', 'sickle_cell', 'coagulation_factors'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'NovoSeven (eptacog alfa)', indication: 'Rare Disease (Hemophilia)', revenue_usd: 1200000000, expiry_year: 2025 },
      { drug_name: 'Alhemo (concizumab)', indication: 'Rare Disease (Hemophilia A/B)', revenue_usd: 300000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'CSL Behring',
    name_variations: ['CSL', 'CSL Limited', 'CSL Behring LLC'],
    ticker: 'CSL.AX',
    company_type: 'large_biotech',
    hq_country: 'Australia',
    modalities_active: ['recombinant_protein', 'gene_therapy', 'antibody'],
    modalities_primary: ['recombinant_protein'],
    indications_active: ['rare_disease', 'hematology', 'immunology'],
    indications_specific: ['hemophilia_a', 'hemophilia_b', 'von_willebrand', 'pid', 'hae'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 7,
    active_trials_count: 20,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['hemophilia_gene_therapy', 'rare_hematology', 'immunoglobulin', 'coagulation'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Hemgenix (etranacogene)', indication: 'Rare Disease (Hemophilia B Gene Therapy)', revenue_usd: 200000000, expiry_year: 2039 },
      { drug_name: 'Haegarda (C1-INH)', indication: 'Rare Disease (HAE)', revenue_usd: 800000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Sobi (Swedish Orphan Biovitrum)',
    name_variations: ['Sobi', 'Swedish Orphan Biovitrum', 'Sobi AB'],
    ticker: 'SOBI.ST',
    company_type: 'mid_pharma',
    hq_country: 'Sweden',
    modalities_active: ['recombinant_protein', 'antibody', 'enzyme_replacement'],
    modalities_primary: ['recombinant_protein'],
    indications_active: ['rare_disease', 'hematology', 'immunology'],
    indications_specific: ['hemophilia_a', 'hemophilia_b', 'neonatal_rare', 'pid'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 12,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_hematology', 'neonatal_rare', 'hemophilia', 'immunology_rare'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Elocta (efmoroctocog alfa)', indication: 'Rare Disease (Hemophilia A)', revenue_usd: 600000000, expiry_year: 2029 },
      { drug_name: 'Alprolix (eftrenonacog alfa)', indication: 'Rare Disease (Hemophilia B)', revenue_usd: 400000000, expiry_year: 2029 },
      { drug_name: 'Kineret (anakinra)', indication: 'Rare Disease (CAPS/FMF)', revenue_usd: 500000000, expiry_year: 2025 },
    ],
  },
  {
    name: 'Chiesi',
    name_variations: ['Chiesi Farmaceutici', 'Chiesi Group', 'Chiesi Rare Diseases'],
    ticker: null,
    company_type: 'mid_pharma',
    hq_country: 'Italy',
    modalities_active: ['enzyme_replacement', 'small_molecule', 'gene_therapy'],
    modalities_primary: ['enzyme_replacement'],
    indications_active: ['rare_disease', 'pulmonology'],
    indications_specific: ['fabry', 'alpha_mannosidosis', 'rare_metabolic', 'neonatal_rare'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_metabolic', 'enzyme_replacement', 'neonatal', 'lysosomal_storage'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Lamzede (velmanase alfa)', indication: 'Rare Disease (Alpha-Mannosidosis)', revenue_usd: 100000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'Ipsen',
    name_variations: ['Ipsen S.A.', 'Ipsen Pharma'],
    ticker: 'IPN.PA',
    company_type: 'mid_pharma',
    hq_country: 'France',
    modalities_active: ['small_molecule', 'peptide', 'gene_therapy'],
    modalities_primary: ['small_molecule', 'peptide'],
    indications_active: ['rare_disease', 'oncology', 'neurology'],
    indications_specific: ['fibrodysplasia_ossificans', 'achondroplasia', 'rare_endocrine', 'psp'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 14,
    avg_upfront_usd: 250000000,
    median_upfront_usd: 120000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_bone_disease', 'rare_endocrine', 'neuroscience_rare', 'fop'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Somatuline (lanreotide)', indication: 'Rare Disease (Acromegaly/NETs)', revenue_usd: 1500000000, expiry_year: 2027 },
      { drug_name: 'Onivyde', indication: 'Oncology', revenue_usd: 400000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Recordati',
    name_variations: ['Recordati S.p.A.', 'Recordati Rare Diseases'],
    ticker: 'REC.MI',
    company_type: 'mid_pharma',
    hq_country: 'Italy',
    modalities_active: ['small_molecule', 'enzyme_replacement'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'rare_metabolic'],
    indications_specific: ['fabry', 'pku', 'bile_acid_synthesis', 'urea_cycle_disorders'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_metabolic', 'orphan_drugs', 'rare_endocrine', 'urea_cycle'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Isturisa (osilodrostat)', indication: 'Rare Disease (Cushings)', revenue_usd: 250000000, expiry_year: 2033 },
      { drug_name: 'Carbaglu (carglumic acid)', indication: 'Rare Disease (NAGS deficiency)', revenue_usd: 200000000, expiry_year: 2028 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP BIOTECHS ACTIVE IN RARE DISEASE LICENSING
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Travere Therapeutics',
    name_variations: ['Travere', 'Retrophin'],
    ticker: 'TVTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'nephrology'],
    indications_specific: ['iga_nephropathy', 'focal_segmental_glomerulosclerosis', 'primary_hyperoxaluria', 'alagille_syndrome'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_kidney', 'iga_nephropathy', 'glomerular_disease', 'orphan_nephrology'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Filspari (sparsentan)', indication: 'Rare Disease (IgA Nephropathy)', revenue_usd: 500000000, expiry_year: 2036 },
      { drug_name: 'Thiola (tiopronin)', indication: 'Rare Disease (Cystinuria)', revenue_usd: 180000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Intercept Pharmaceuticals',
    name_variations: ['Intercept', 'Intercept Pharma'],
    ticker: 'ICPT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'hepatology'],
    indications_specific: ['primary_biliary_cholangitis', 'nash', 'primary_sclerosing_cholangitis', 'rare_liver'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['rare_liver', 'pbc', 'fxr_agonist', 'cholestatic_disease'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Ocaliva (obeticholic acid)', indication: 'Rare Disease (PBC)', revenue_usd: 350000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Neurocrine Biosciences',
    name_variations: ['Neurocrine', 'Neurocrine Inc.'],
    ticker: 'NBIX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'neurology', 'endocrinology'],
    indications_specific: ['congenital_adrenal_hyperplasia', 'tardive_dyskinesia', 'endogenous_cushings', 'rare_neuroendocrine'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 14,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_neuroendocrine', 'movement_disorders', 'cah', 'neuropsychiatry'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Ingrezza (valbenazine)', indication: 'Rare Disease (Tardive Dyskinesia)', revenue_usd: 2100000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'Harmony Biosciences',
    name_variations: ['Harmony', 'Harmony Bio'],
    ticker: 'HRMY',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'neurology'],
    indications_specific: ['narcolepsy', 'idiopathic_hypersomnia', 'rare_sleep_disorders', 'prader_willi'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_sleep', 'narcolepsy', 'orexin_pathway', 'rare_cns'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Wakix (pitolisant)', indication: 'Rare Disease (Narcolepsy)', revenue_usd: 700000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Rhythm Pharmaceuticals',
    name_variations: ['Rhythm', 'Rhythm Pharma'],
    ticker: 'RYTM',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['peptide'],
    modalities_primary: ['peptide'],
    indications_active: ['rare_disease', 'metabolic'],
    indications_specific: ['bbs', 'pomc_deficiency', 'lepr_deficiency', 'rare_genetic_obesity', 'alstrom_syndrome'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['mc4r_pathway', 'rare_genetic_obesity', 'hypothalamic_obesity', 'bbs'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Imcivree (setmelanotide)', indication: 'Rare Disease (BBS/POMC/LEPR Obesity)', revenue_usd: 250000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Mirum Pharmaceuticals',
    name_variations: ['Mirum', 'Mirum Pharma'],
    ticker: 'MIRM',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'hepatology'],
    indications_specific: ['alagille_syndrome', 'pfic', 'biliary_atresia', 'rare_pediatric_liver'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 7,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: true,
    acquisition_appetite: 'selective',
    strategic_priorities: ['rare_pediatric_liver', 'cholestatic_disease', 'apical_sodium_bile_acid', 'alagille'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Livmarli (maralixibat)', indication: 'Rare Disease (Alagille/PFIC)', revenue_usd: 350000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Insmed',
    name_variations: ['Insmed Incorporated', 'Insmed Inc.'],
    ticker: 'INSM',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'inhaled_formulation', 'antibody'],
    modalities_primary: ['inhaled_formulation', 'antibody'],
    indications_active: ['rare_disease', 'pulmonology'],
    indications_specific: ['ntm_lung_disease', 'bronchiectasis', 'rare_pulmonary', 'pai_1'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_pulmonary', 'ntm', 'bronchiectasis', 'inhaled_therapies'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Arikayce (amikacin liposome)', indication: 'Rare Disease (NTM Lung)', revenue_usd: 350000000, expiry_year: 2034 },
      { drug_name: 'Brensocatib', indication: 'Rare Disease (Bronchiectasis)', revenue_usd: 600000000, expiry_year: 2038 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ASIAN / EUROPEAN PHARMA ACTIVE IN RARE DISEASE
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Daiichi Sankyo (Rare Disease)',
    name_variations: ['Daiichi Sankyo', 'Daiichi Sankyo Company'],
    ticker: '4568.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'gene_therapy'],
    modalities_primary: ['small_molecule', 'adc'],
    indications_active: ['rare_disease', 'oncology', 'cardiovascular'],
    indications_specific: ['rare_cardiac', 'transthyretin_cardiomyopathy', 'rare_hematology', 'rare_metabolic'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan', 'asia'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 18,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_cardiology', 'adc_rare', 'rare_metabolic', 'japan_orphan'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Enhertu (trastuzumab deruxtecan)', indication: 'Oncology (HER2+)', revenue_usd: 4500000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Astellas Pharma (Rare Disease)',
    name_variations: ['Astellas', 'Astellas Pharma Inc.'],
    ticker: '4503.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'gene_therapy', 'cell_therapy', 'antibody'],
    modalities_primary: ['gene_therapy', 'small_molecule'],
    indications_active: ['rare_disease', 'oncology', 'urology'],
    indications_specific: ['rare_mitochondrial', 'rare_genetic_eye', 'rare_muscular', 'fabry'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 16,
    avg_upfront_usd: 350000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['gene_therapy_rare', 'rare_mitochondrial', 'rare_ophthalmology', 'cell_therapy'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Xtandi (enzalutamide)', indication: 'Oncology (Prostate)', revenue_usd: 4800000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Kyowa Kirin',
    name_variations: ['Kyowa Kirin Co.', 'Kyowa Hakko Kirin'],
    ticker: '4151.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['antibody', 'small_molecule', 'recombinant_protein'],
    modalities_primary: ['antibody'],
    indications_active: ['rare_disease', 'hematology', 'nephrology'],
    indications_specific: ['xlh', 'fop', 'rare_bone', 'rare_hematology', 'cutaneous_t_cell_lymphoma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan', 'asia'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_bone', 'rare_hematology', 'xlh', 'fop', 'japan_rare'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Crysvita (burosumab)', indication: 'Rare Disease (XLH)', revenue_usd: 700000000, expiry_year: 2033 },
      { drug_name: 'Poteligeo (mogamulizumab)', indication: 'Rare Disease (CTCL)', revenue_usd: 350000000, expiry_year: 2031 },
    ],
  },
  {
    name: 'Orchard Therapeutics',
    name_variations: ['Orchard', 'Orchard Tx'],
    ticker: 'ORTX',
    company_type: 'specialty',
    hq_country: 'UK',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['rare_disease', 'neurology', 'immunology'],
    indications_specific: ['mld', 'mps_iiia', 'als', 'rare_neurometabolic', 'wiskott_aldrich'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe', 'us'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['hsc_gene_therapy', 'rare_neurometabolic', 'leukodystrophy', 'lentiviral_platform'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'Libmeldy (atidarsagene)', indication: 'Rare Disease (MLD)', revenue_usd: 100000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Menarini / Stemline',
    name_variations: ['Menarini Group', 'Stemline Therapeutics', 'Menarini Stemline'],
    ticker: null,
    company_type: 'mid_pharma',
    hq_country: 'Italy',
    modalities_active: ['small_molecule', 'adc', 'antibody'],
    modalities_primary: ['small_molecule', 'adc'],
    indications_active: ['rare_disease', 'hematology', 'oncology'],
    indications_specific: ['bpdcn', 'mastocytosis', 'myelofibrosis', 'rare_leukemia', 'rare_hematologic_malignancy'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rare_hematology', 'bpdcn', 'rare_oncology', 'mastocytosis'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Elzonris (tagraxofusp)', indication: 'Rare Disease (BPDCN)', revenue_usd: 150000000, expiry_year: 2033 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // SPECIALTY RARE DISEASE COMPANIES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Passage Bio',
    name_variations: ['Passage Bio Inc.', 'PassageBio'],
    ticker: 'PASG',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['rare_disease', 'neurology'],
    indications_specific: ['gm1_gangliosidosis', 'frontotemporal_dementia', 'krabbe_disease', 'rare_cns'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['aav_gene_therapy_cns', 'rare_lysosomal_cns', 'gm1', 'ftd'],
    data_quality_score: 55,
    patent_cliffs: [],
  },
  {
    name: 'Sangamo Therapeutics',
    name_variations: ['Sangamo', 'Sangamo Inc.'],
    ticker: 'SGMO',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'gene_editing', 'cell_therapy'],
    modalities_primary: ['gene_therapy', 'gene_editing'],
    indications_active: ['rare_disease', 'neurology', 'hematology'],
    indications_specific: ['fabry', 'hemophilia_a', 'tauopathy', 'rare_cns', 'mps_ii'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 6,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['zinc_finger_nuclease', 'in_vivo_gene_editing', 'gene_therapy_rare', 'aav_capsid'],
    data_quality_score: 60,
    patent_cliffs: [],
  },
  {
    name: 'Applied Therapeutics',
    name_variations: ['Applied Therapeutics Inc.', 'Applied Tx'],
    ticker: 'APLT',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['rare_disease', 'metabolic'],
    indications_specific: ['galactosemia', 'sorbitol_dehydrogenase_deficiency', 'diabetic_cardiomyopathy', 'rare_metabolic'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 4,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['aldose_reductase_inhibitor', 'galactosemia', 'rare_metabolic', 'polyol_pathway'],
    data_quality_score: 55,
    patent_cliffs: [],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedRareDiseaseCompanies() {
  console.log('Starting rare disease company seed...\n');
  console.log(`Seeding ${rareDiseaseCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of rareDiseaseCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with rare disease data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${rareDiseaseCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedRareDiseaseCompanies().catch(console.error);
