// Script to seed infectious disease-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-infectious-disease-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes infectious disease-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for infectious disease assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface InfectiousDiseaseCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// INFECTIOUS DISEASE COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const infectiousDiseaseCompanies: InfectiousDiseaseCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA WITH MAJOR INFECTIOUS DISEASE FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Gilead Sciences',
    name_variations: ['Gilead', 'Gilead Sciences Inc.', 'Gilead Sciences Inc'],
    ticker: 'GILD',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'capsid_inhibitor', 'nucleotide_analog'],
    modalities_primary: ['small_molecule', 'nucleotide_analog'],
    indications_active: ['infectious_disease', 'hematology', 'oncology', 'inflammation'],
    indications_specific: ['hiv', 'hcv', 'hbv', 'covid_19', 'fungal_infections'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 55,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['hiv_long_acting', 'hiv_cure', 'hbv_functional_cure', 'lenacapavir_expansion', 'antiviral_platform'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Biktarvy (bictegravir/emtricitabine/TAF)', indication: 'Infectious Disease (HIV)', revenue_usd: 12400000000, expiry_year: 2033 },
      { drug_name: 'Descovy (emtricitabine/TAF)', indication: 'Infectious Disease (HIV/PrEP)', revenue_usd: 2100000000, expiry_year: 2031 },
      { drug_name: 'Veklury (remdesivir)', indication: 'Infectious Disease (COVID-19)', revenue_usd: 1900000000, expiry_year: 2035 },
      { drug_name: 'Lenacapavir (Sunlenca)', indication: 'Infectious Disease (HIV Long-Acting)', revenue_usd: 800000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Merck',
    name_variations: ['Merck & Co.', 'Merck Sharp & Dohme', 'MSD'],
    ticker: 'MRK',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'vaccine', 'antiviral'],
    modalities_primary: ['small_molecule', 'vaccine'],
    indications_active: ['infectious_disease', 'oncology', 'cardiovascular', 'immunology'],
    indications_specific: ['covid_19', 'hiv', 'hpv', 'cmv', 'fungal_infections'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 40,
    avg_upfront_usd: 4000000000,
    median_upfront_usd: 2000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['antiviral_portfolio', 'gardasil_expansion', 'prevymis_transplant', 'pandemic_preparedness', 'amr'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Gardasil/Gardasil 9', indication: 'Infectious Disease (HPV Vaccine)', revenue_usd: 9400000000, expiry_year: 2028 },
      { drug_name: 'Lagevrio (molnupiravir)', indication: 'Infectious Disease (COVID-19)', revenue_usd: 1200000000, expiry_year: 2036 },
      { drug_name: 'Prevymis (letermovir)', indication: 'Infectious Disease (CMV)', revenue_usd: 600000000, expiry_year: 2033 },
    ],
  },
  {
    name: 'Pfizer',
    name_variations: ['Pfizer Inc.', 'Pfizer Inc'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'mrna', 'vaccine', 'antibody', 'antiviral'],
    modalities_primary: ['small_molecule', 'vaccine'],
    indications_active: ['infectious_disease', 'oncology', 'immunology', 'rare_disease'],
    indications_specific: ['covid_19', 'pneumococcal', 'rsv', 'influenza', 'fungal_infections'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 45,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['antiviral_oral', 'mrna_platform', 'vaccine_portfolio', 'pandemic_preparedness', 'amr_antibiotics'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Paxlovid (nirmatrelvir/ritonavir)', indication: 'Infectious Disease (COVID-19)', revenue_usd: 4100000000, expiry_year: 2036 },
      { drug_name: 'Prevnar 20 (PCV20)', indication: 'Infectious Disease (Pneumococcal Vaccine)', revenue_usd: 6400000000, expiry_year: 2034 },
      { drug_name: 'Abrysvo (RSV vaccine)', indication: 'Infectious Disease (RSV)', revenue_usd: 900000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'GSK',
    name_variations: ['GlaxoSmithKline', 'GSK plc'],
    ticker: 'GSK',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['vaccine', 'antibody', 'small_molecule', 'mrna'],
    modalities_primary: ['vaccine', 'small_molecule'],
    indications_active: ['infectious_disease', 'oncology', 'immunology', 'hiv'],
    indications_specific: ['hiv', 'shingles', 'meningitis', 'rsv', 'malaria', 'influenza'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 40,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['shingrix_expansion', 'hiv_via_viiv', 'vaccine_innovation', 'adjuvant_technology', 'pandemic_preparedness'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Shingrix (RZV)', indication: 'Infectious Disease (Shingles Vaccine)', revenue_usd: 4300000000, expiry_year: 2034 },
      { drug_name: 'Arexvy (RSV vaccine)', indication: 'Infectious Disease (RSV)', revenue_usd: 1800000000, expiry_year: 2038 },
      { drug_name: 'Mosquirix (RTS,S)', indication: 'Infectious Disease (Malaria Vaccine)', revenue_usd: 200000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Johnson & Johnson (Janssen)',
    name_variations: ['J&J', 'Janssen', 'Janssen Pharmaceuticals', 'Janssen Biotech', 'Janssen Infectious Diseases'],
    ticker: 'JNJ',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'vaccine', 'antibody', 'antiviral'],
    modalities_primary: ['small_molecule', 'vaccine'],
    indications_active: ['infectious_disease', 'oncology', 'immunology', 'cardiovascular'],
    indications_specific: ['hiv', 'tuberculosis', 'rsv', 'hepatitis_b', 'amr'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 30,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['tuberculosis', 'hiv_long_acting', 'rsv', 'vaccine_platform', 'global_health'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Sirturo (bedaquiline)', indication: 'Infectious Disease (MDR-TB)', revenue_usd: 900000000, expiry_year: 2027 },
      { drug_name: 'Edurant (rilpivirine)', indication: 'Infectious Disease (HIV)', revenue_usd: 500000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'AbbVie',
    name_variations: ['AbbVie Inc.', 'AbbVie Inc'],
    ticker: 'ABBV',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'antiviral'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease', 'immunology', 'hematology', 'oncology'],
    indications_specific: ['hcv', 'hiv', 'rsv'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 20,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['antiviral_portfolio', 'hcv_legacy', 'next_gen_antivirals', 'pandemic_preparedness'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Mavyret (glecaprevir/pibrentasvir)', indication: 'Infectious Disease (HCV)', revenue_usd: 1600000000, expiry_year: 2030 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // HIV SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'ViiV Healthcare',
    name_variations: ['ViiV', 'ViiV Healthcare Ltd', 'ViiV Healthcare Company'],
    ticker: null,
    company_type: 'specialty',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'long_acting_injectable', 'antibody', 'capsid_inhibitor'],
    modalities_primary: ['small_molecule', 'long_acting_injectable'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hiv', 'hiv_prevention', 'hiv_cure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 28,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['hiv_long_acting', 'hiv_two_drug_regimens', 'hiv_cure_research', 'cabotegravir_expansion', 'broadly_neutralizing_antibodies'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Dolutegravir (Tivicay/Dovato/Juluca)', indication: 'Infectious Disease (HIV)', revenue_usd: 7500000000, expiry_year: 2029 },
      { drug_name: 'Cabotegravir (Cabenuva/Apretude)', indication: 'Infectious Disease (HIV Long-Acting)', revenue_usd: 1800000000, expiry_year: 2035 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ANTIVIRAL SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Shionogi',
    name_variations: ['Shionogi & Co.', 'Shionogi Inc.', 'Shionogi Pharma'],
    ticker: '4507.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antiviral', 'antibiotic'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease', 'pain_management'],
    indications_specific: ['influenza', 'covid_19', 'amr', 'hiv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 18,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['influenza_antivirals', 'covid_antivirals', 'amr_antibiotics', 'cap_dependent_endonuclease', 'pandemic_preparedness'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Xofluza (baloxavir marboxil)', indication: 'Infectious Disease (Influenza)', revenue_usd: 900000000, expiry_year: 2033 },
      { drug_name: 'Xocova/Ensitrelvir', indication: 'Infectious Disease (COVID-19)', revenue_usd: 500000000, expiry_year: 2037 },
      { drug_name: 'Fetroja (cefiderocol)', indication: 'Infectious Disease (AMR/Gram-negative)', revenue_usd: 300000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Roche/Genentech',
    name_variations: ['Roche', 'Genentech', 'Roche Holding AG', 'F. Hoffmann-La Roche'],
    ticker: 'RHHBY',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['antibody', 'small_molecule', 'antiviral', 'diagnostic'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['infectious_disease', 'oncology', 'neurology', 'ophthalmology'],
    indications_specific: ['influenza', 'covid_19', 'rsv', 'hbv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 25,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['antiviral_portfolio', 'diagnostics_therapeutics', 'pandemic_preparedness', 'hbv_cure'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Tamiflu (oseltamivir)', indication: 'Infectious Disease (Influenza)', revenue_usd: 400000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['antibody', 'small_molecule', 'antiviral'],
    modalities_primary: ['antibody'],
    indications_active: ['infectious_disease', 'oncology', 'cardiovascular', 'rare_disease'],
    indications_specific: ['covid_19', 'rsv', 'influenza'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 18,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['monoclonal_antibody_antivirals', 'long_acting_antibodies', 'rsv_prevention', 'pandemic_preparedness'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Evusheld (tixagevimab/cilgavimab)', indication: 'Infectious Disease (COVID-19 Prevention)', revenue_usd: 1200000000, expiry_year: 2036 },
      { drug_name: 'Beyfortus (nirsevimab, with Sanofi)', indication: 'Infectious Disease (RSV Prevention)', revenue_usd: 1500000000, expiry_year: 2038 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ANTIBIOTICS / AMR SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Paratek Pharmaceuticals',
    name_variations: ['Paratek', 'Paratek Pharmaceuticals Inc'],
    ticker: 'PRTK',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['cabp', 'absssi', 'uti', 'amr'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['tetracycline_platform', 'amr_antibiotics', 'community_acquired_pneumonia', 'skin_infections'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Nuzyra (omadacycline)', indication: 'Infectious Disease (CABP/ABSSSI)', revenue_usd: 150000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Melinta Therapeutics',
    name_variations: ['Melinta', 'Melinta Therapeutics Inc'],
    ticker: 'MLNT',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['absssi', 'cabp', 'uti', 'amr_gram_positive'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['fluoroquinolone_antibiotics', 'amr', 'hospital_antibiotics', 'skin_infections'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'Baxdela (delafloxacin)', indication: 'Infectious Disease (ABSSSI/CABP)', revenue_usd: 80000000, expiry_year: 2032 },
      { drug_name: 'Vabomere (meropenem/vaborbactam)', indication: 'Infectious Disease (cUTI/AMR)', revenue_usd: 60000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Entasis Therapeutics (Innoviva)',
    name_variations: ['Entasis', 'Entasis Therapeutics', 'Innoviva Specialty Therapeutics'],
    ticker: 'INVA',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'beta_lactamase_inhibitor'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['amr_gram_negative', 'cuti', 'hospital_acquired_pneumonia', 'acinetobacter'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 40000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['beta_lactamase_inhibitors', 'gram_negative_amr', 'acinetobacter', 'novel_antibiotics'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Durlobactam/sulbactam (Xacduro)', indication: 'Infectious Disease (Acinetobacter HAP/VAP)', revenue_usd: 200000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Cidara Therapeutics',
    name_variations: ['Cidara', 'Cidara Therapeutics Inc'],
    ticker: 'CDTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antifungal', 'antibody_drug_conjugate'],
    modalities_primary: ['antifungal'],
    indications_active: ['infectious_disease'],
    indications_specific: ['invasive_fungal_infections', 'candidemia', 'influenza', 'rsv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['echinocandin_antifungals', 'long_acting_antifungal', 'cloudbreak_platform', 'antiviral_conjugates'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Rezafungin', indication: 'Infectious Disease (Candidemia/Invasive Candidiasis)', revenue_usd: 300000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Iterum Therapeutics',
    name_variations: ['Iterum', 'Iterum Therapeutics plc'],
    ticker: 'ITRM',
    company_type: 'specialty',
    hq_country: 'Ireland',
    modalities_active: ['small_molecule', 'antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['uti', 'amr', 'intra_abdominal_infections'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 20000000,
    median_upfront_usd: 10000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oral_carbapenem', 'uti_antibiotics', 'amr', 'outpatient_iv_to_oral'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'Sulopenem', indication: 'Infectious Disease (uUTI)', revenue_usd: 150000000, expiry_year: 2036 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // VACCINE SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Moderna',
    name_variations: ['Moderna Inc.', 'Moderna Inc', 'Moderna Therapeutics'],
    ticker: 'MRNA',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['mrna', 'vaccine', 'mrna_therapeutic'],
    modalities_primary: ['mrna', 'vaccine'],
    indications_active: ['infectious_disease', 'oncology', 'rare_disease', 'autoimmune'],
    indications_specific: ['covid_19', 'rsv', 'influenza', 'cmv', 'hiv', 'nipah', 'zika'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 45,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['mrna_vaccine_platform', 'combination_vaccines', 'respiratory_franchise', 'cmv_vaccine', 'pandemic_preparedness'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Spikevax (mRNA-1273)', indication: 'Infectious Disease (COVID-19 mRNA Vaccine)', revenue_usd: 6200000000, expiry_year: 2035 },
      { drug_name: 'mRESVIA (mRNA-1345)', indication: 'Infectious Disease (RSV mRNA Vaccine)', revenue_usd: 1200000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'BioNTech',
    name_variations: ['BioNTech SE', 'BioNTech Inc'],
    ticker: 'BNTX',
    company_type: 'large_biotech',
    hq_country: 'Germany',
    modalities_active: ['mrna', 'vaccine', 'cell_therapy', 'antibody'],
    modalities_primary: ['mrna', 'vaccine'],
    indications_active: ['infectious_disease', 'oncology'],
    indications_specific: ['covid_19', 'influenza', 'shingles', 'malaria', 'tuberculosis', 'hiv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 35,
    avg_upfront_usd: 800000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['mrna_platform', 'next_gen_covid', 'combination_vaccines', 'malaria_mrna', 'tuberculosis_vaccine'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Comirnaty (BNT162b2)', indication: 'Infectious Disease (COVID-19 mRNA Vaccine)', revenue_usd: 4800000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Novavax',
    name_variations: ['Novavax Inc.', 'Novavax Inc'],
    ticker: 'NVAX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['protein_subunit', 'vaccine', 'nanoparticle'],
    modalities_primary: ['protein_subunit', 'vaccine'],
    indications_active: ['infectious_disease'],
    indications_specific: ['covid_19', 'influenza', 'covid_flu_combo', 'rsv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['protein_subunit_platform', 'combination_vaccines', 'matrix_m_adjuvant', 'pandemic_preparedness'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Nuvaxovid (NVX-CoV2373)', indication: 'Infectious Disease (COVID-19 Protein Vaccine)', revenue_usd: 800000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Valneva',
    name_variations: ['Valneva SE', 'Valneva Austria GmbH'],
    ticker: 'VALN',
    company_type: 'mid_biotech',
    hq_country: 'France',
    modalities_active: ['vaccine', 'inactivated_virus'],
    modalities_primary: ['vaccine'],
    indications_active: ['infectious_disease'],
    indications_specific: ['chikungunya', 'lyme_disease', 'covid_19', 'japanese_encephalitis'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['travel_vaccines', 'chikungunya_vaccine', 'lyme_disease_vaccine', 'tropical_disease'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Ixchiq (VLA1553)', indication: 'Infectious Disease (Chikungunya Vaccine)', revenue_usd: 300000000, expiry_year: 2039 },
      { drug_name: 'Ixiaro (JE vaccine)', indication: 'Infectious Disease (Japanese Encephalitis)', revenue_usd: 150000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Bavarian Nordic',
    name_variations: ['Bavarian Nordic A/S', 'BN'],
    ticker: 'BAVA.CO',
    company_type: 'mid_biotech',
    hq_country: 'Denmark',
    modalities_active: ['vaccine', 'viral_vector'],
    modalities_primary: ['vaccine'],
    indications_active: ['infectious_disease'],
    indications_specific: ['smallpox', 'mpox', 'rsv', 'ebola', 'hpv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'europe', 'us'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 75000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['mva_bn_platform', 'biodefense', 'mpox_vaccine', 'rsv_vaccine', 'pandemic_preparedness'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Jynneos/Imvanex (MVA-BN)', indication: 'Infectious Disease (Smallpox/Mpox Vaccine)', revenue_usd: 800000000, expiry_year: 2033 },
    ],
  },
  {
    name: 'Dynavax Technologies',
    name_variations: ['Dynavax', 'Dynavax Technologies Corp'],
    ticker: 'DVAX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['vaccine', 'adjuvant'],
    modalities_primary: ['vaccine', 'adjuvant'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b', 'plague', 'adjuvant_partnerships'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 8,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['cpg_1018_adjuvant', 'hepatitis_b_market_share', 'adjuvant_licensing', 'pandemic_preparedness'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Heplisav-B', indication: 'Infectious Disease (Hepatitis B Vaccine)', revenue_usd: 700000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Sanofi',
    name_variations: ['Sanofi S.A.', 'Sanofi-Aventis', 'Sanofi Pasteur'],
    ticker: 'SNY',
    company_type: 'large_pharma',
    hq_country: 'France',
    modalities_active: ['vaccine', 'antibody', 'small_molecule', 'mrna'],
    modalities_primary: ['vaccine', 'antibody'],
    indications_active: ['infectious_disease', 'immunology', 'rare_disease', 'oncology'],
    indications_specific: ['rsv', 'influenza', 'meningitis', 'polio', 'dengue'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 35,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['rsv_prevention', 'influenza_next_gen', 'mrna_vaccines', 'meningitis_franchise', 'global_health'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Beyfortus (nirsevimab, with AZ)', indication: 'Infectious Disease (RSV Prevention)', revenue_usd: 1500000000, expiry_year: 2038 },
      { drug_name: 'Fluzone/Flublok', indication: 'Infectious Disease (Influenza Vaccine)', revenue_usd: 3200000000, expiry_year: 2028 },
      { drug_name: 'Menactra/MenQuadfi', indication: 'Infectious Disease (Meningococcal Vaccine)', revenue_usd: 1200000000, expiry_year: 2030 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ASIAN PHARMA ACTIVE IN INFECTIOUS DISEASE
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Daiichi Sankyo',
    name_variations: ['Daiichi Sankyo Co.', 'Daiichi Sankyo Inc.'],
    ticker: '4568.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibiotic', 'vaccine'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease', 'oncology', 'cardiovascular'],
    indications_specific: ['amr', 'mrsa', 'gram_negative'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 12,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['antibiotic_pipeline', 'amr', 'japan_infectious_disease', 'pandemic_preparedness'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Sivextro (tedizolid)', indication: 'Infectious Disease (ABSSSI/MRSA)', revenue_usd: 200000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Meiji Seika Pharma',
    name_variations: ['Meiji Seika', 'Meiji Pharma', 'Meiji Seika Pharma Co.'],
    ticker: '4569.T',
    company_type: 'mid_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibiotic', 'vaccine'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['amr', 'mrsa', 'gram_negative', 'carbapenem_resistant'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['japan', 'asia', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['carbapenem_antibiotics', 'amr_pipeline', 'japan_hospital_antibiotics', 'biosimilars'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Meropenem (generic/branded)', indication: 'Infectious Disease (Hospital Infections)', revenue_usd: 300000000, expiry_year: 2026 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ADDITIONAL INFECTIOUS DISEASE COMPANIES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Emergent BioSolutions',
    name_variations: ['Emergent', 'Emergent BioSolutions Inc'],
    ticker: 'EBS',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['vaccine', 'antibody', 'antitoxin', 'smallpox_treatment'],
    modalities_primary: ['vaccine', 'antitoxin'],
    indications_active: ['infectious_disease'],
    indications_specific: ['anthrax', 'smallpox', 'botulism', 'biodefense', 'opioid_overdose'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['us'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['biodefense', 'cbrn_medical_countermeasures', 'anthrax_vaccine', 'government_contracts'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'BioThrax/ACAM2000', indication: 'Infectious Disease (Anthrax/Smallpox Biodefense)', revenue_usd: 500000000, expiry_year: 2029 },
      { drug_name: 'TEMBEXA (brincidofovir)', indication: 'Infectious Disease (Smallpox Treatment)', revenue_usd: 100000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Assembly Biosciences',
    name_variations: ['Assembly Bio', 'Assembly Biosciences Inc'],
    ticker: 'ASMB',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'capsid_inhibitor'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b', 'hbv_cure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['hbv_core_inhibitor', 'hbv_functional_cure', 'capsid_assembly_modulation', 'combination_hbv'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Vebicorvir (ABI-H0731)', indication: 'Infectious Disease (HBV Core Inhibitor)', revenue_usd: 200000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Arbutus Biopharma',
    name_variations: ['Arbutus', 'Arbutus Biopharma Corp'],
    ticker: 'ABUS',
    company_type: 'mid_biotech',
    hq_country: 'Canada',
    modalities_active: ['small_molecule', 'rna_interference'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_b', 'hbv_cure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 40000000,
    median_upfront_usd: 20000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['hbv_functional_cure', 'pd_l1_sirna', 'combination_hbv', 'rna_interference_antivirals'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'Imdusiran (AB-729)', indication: 'Infectious Disease (HBV RNAi)', revenue_usd: 300000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Atea Pharmaceuticals',
    name_variations: ['Atea', 'Atea Pharmaceuticals Inc'],
    ticker: 'AVIR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'nucleoside_analog', 'antiviral'],
    modalities_primary: ['small_molecule', 'antiviral'],
    indications_active: ['infectious_disease'],
    indications_specific: ['hepatitis_c', 'dengue', 'rsv', 'covid_19'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['direct_acting_antivirals', 'rna_polymerase_inhibitors', 'broad_spectrum_antivirals', 'pandemic_preparedness'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Bemnifosbuvir (AT-527)', indication: 'Infectious Disease (HCV/COVID-19 Antiviral)', revenue_usd: 400000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Virios Therapeutics',
    name_variations: ['Virios', 'Virios Therapeutics Inc'],
    ticker: 'VIRI',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antiviral'],
    modalities_primary: ['antiviral'],
    indications_active: ['infectious_disease'],
    indications_specific: ['herpes_simplex', 'fibromyalgia_viral', 'ibs_viral'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['antiviral_repurposing', 'hsv_reactivation', 'viral_driven_chronic_disease'],
    data_quality_score: 55,
    patent_cliffs: [
      { drug_name: 'IMC-1 (valacyclovir/celecoxib)', indication: 'Infectious Disease (HSV-associated Fibromyalgia)', revenue_usd: 100000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Enanta Pharmaceuticals',
    name_variations: ['Enanta', 'Enanta Pharmaceuticals Inc'],
    ticker: 'ENTA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'protease_inhibitor', 'antiviral'],
    modalities_primary: ['small_molecule'],
    indications_active: ['infectious_disease'],
    indications_specific: ['rsv', 'hbv', 'covid_19', 'hcv'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['rsv_oral_antiviral', 'hbv_protease_inhibitor', 'direct_acting_antivirals', 'protease_inhibitor_platform'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'EDP-938 (zelicapavir)', indication: 'Infectious Disease (RSV Oral Antiviral)', revenue_usd: 400000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Novartis',
    name_variations: ['Novartis AG', 'Novartis Pharma'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['small_molecule', 'antibody', 'vaccine', 'gene_therapy'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['infectious_disease', 'oncology', 'cardiovascular', 'immunology'],
    indications_specific: ['malaria', 'chagas', 'tuberculosis', 'tropical_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 15,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['tropical_disease', 'malaria_treatment', 'global_health_access', 'neglected_diseases'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Coartem (artemether/lumefantrine)', indication: 'Infectious Disease (Malaria)', revenue_usd: 400000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Amplyx/Pfizer (Antifungal)',
    name_variations: ['Amplyx Pharmaceuticals', 'Pfizer Antifungal'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antifungal'],
    modalities_primary: ['antifungal'],
    indications_active: ['infectious_disease'],
    indications_specific: ['invasive_aspergillosis', 'mucormycosis', 'invasive_fungal_infections'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 5,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['novel_antifungal_classes', 'invasive_fungal_infections', 'aspergillosis', 'anti_infective_pipeline'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Fosmanogepix (APX001)', indication: 'Infectious Disease (Invasive Fungal Infections)', revenue_usd: 500000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Qpex Biopharma (Shionogi)',
    name_variations: ['Qpex', 'Qpex Biopharma Inc', 'Shionogi Qpex'],
    ticker: '4507.T',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'beta_lactamase_inhibitor', 'antibiotic'],
    modalities_primary: ['antibiotic'],
    indications_active: ['infectious_disease'],
    indications_specific: ['amr_gram_negative', 'pseudomonas', 'carbapenem_resistant'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['novel_beta_lactamase_inhibitors', 'gram_negative_amr', 'pseudomonas', 'carbapenem_sparing'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'Xeruborbactam (QPX7728)', indication: 'Infectious Disease (AMR Gram-Negative)', revenue_usd: 250000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Inovio Pharmaceuticals',
    name_variations: ['Inovio', 'Inovio Pharmaceuticals Inc'],
    ticker: 'INO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['dna_vaccine', 'vaccine', 'immunotherapy'],
    modalities_primary: ['dna_vaccine'],
    indications_active: ['infectious_disease', 'oncology'],
    indications_specific: ['hpv', 'covid_19', 'mers', 'zika', 'ebola', 'lassa'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['dna_vaccine_platform', 'cellectra_delivery', 'pandemic_preparedness', 'emerging_infectious_disease'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'INO-4800', indication: 'Infectious Disease (COVID-19 DNA Vaccine)', revenue_usd: 200000000, expiry_year: 2037 },
      { drug_name: 'VGX-3100', indication: 'Infectious Disease/Oncology (HPV-related CIN)', revenue_usd: 300000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'CureVac',
    name_variations: ['CureVac N.V.', 'CureVac AG'],
    ticker: 'CVAC',
    company_type: 'mid_biotech',
    hq_country: 'Germany',
    modalities_active: ['mrna', 'vaccine'],
    modalities_primary: ['mrna'],
    indications_active: ['infectious_disease', 'oncology'],
    indications_specific: ['covid_19', 'influenza', 'rsv', 'rabies'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global', 'europe'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['mrna_optimization', 'second_gen_mrna', 'gsk_partnership', 'respiratory_vaccines'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'CV2CoV (next-gen COVID)', indication: 'Infectious Disease (COVID-19 mRNA)', revenue_usd: 300000000, expiry_year: 2038 },
    ],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedInfectiousDiseaseCompanies() {
  console.log('Starting infectious disease company seed...\n');
  console.log(`Seeding ${infectiousDiseaseCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of infectiousDiseaseCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with infectious disease data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${infectiousDiseaseCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedInfectiousDiseaseCompanies().catch(console.error);
