// Script to seed cardiovascular-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-cardiovascular-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes cardiovascular-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for cardiovascular assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface CardiovascularCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// CARDIOVASCULAR COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const cardiovascularCompanies: CardiovascularCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA WITH MAJOR CARDIOVASCULAR FRANCHISES
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Novartis',
    name_variations: ['Novartis AG', 'Novartis Pharma'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['small_molecule', 'antibody', 'sirna', 'gene_therapy'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['cardiovascular', 'oncology', 'hematology', 'autoimmune'],
    indications_specific: ['heart_failure', 'hypertension', 'atherosclerosis', 'hypercholesterolemia', 'hcm'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 13,
    active_trials_count: 45,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['heart_failure', 'entresto_expansion', 'leqvio_pcsk9', 'cv_rnai', 'factor_xi'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Entresto (sacubitril/valsartan)', indication: 'Cardiovascular (Heart Failure ARNI)', revenue_usd: 6500000000, expiry_year: 2028 },
      { drug_name: 'Leqvio (inclisiran)', indication: 'Cardiovascular (Hypercholesterolemia PCSK9 siRNA)', revenue_usd: 600000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Pfizer',
    name_variations: ['Pfizer Inc.', 'Pfizer Inc'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'sirna'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology', 'autoimmune', 'metabolic'],
    indications_specific: ['atrial_fibrillation', 'vte', 'dvt', 'pulmonary_embolism', 'anticoagulation'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 25,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['post_eliquis_strategy', 'next_gen_anticoagulation', 'factor_xi', 'cv_pipeline'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Eliquis (apixaban, co-rights with BMS)', indication: 'Cardiovascular (AF/VTE Anticoagulant)', revenue_usd: 10000000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Bristol-Myers Squibb',
    name_variations: ['BMS', 'Bristol Myers Squibb', 'Bristol-Myers Squibb Company'],
    ticker: 'BMY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'bispecific'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'hematology', 'oncology', 'autoimmune'],
    indications_specific: ['atrial_fibrillation', 'vte', 'thrombosis', 'factor_xia'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 13,
    active_trials_count: 20,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['post_eliquis_pipeline', 'milvexian_fxia', 'next_gen_anticoagulation', 'cv_pipeline'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Eliquis (apixaban, co-rights with Pfizer)', indication: 'Cardiovascular (AF/VTE Anticoagulant)', revenue_usd: 12000000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Johnson & Johnson (Janssen)',
    name_variations: ['J&J', 'Janssen', 'Janssen Pharmaceuticals'],
    ticker: 'JNJ',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology', 'autoimmune', 'pulmonology'],
    indications_specific: ['thrombosis', 'pah', 'peripheral_artery_disease'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 18,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['pah', 'thrombosis', 'post_xarelto', 'cv_pipeline'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Xarelto (rivaroxaban)', indication: 'Cardiovascular (AF/VTE/ACS Anticoagulant)', revenue_usd: 4500000000, expiry_year: 2026 },
      { drug_name: 'Opsumit (macitentan)', indication: 'Cardiovascular (PAH)', revenue_usd: 2000000000, expiry_year: 2028 },
      { drug_name: 'Uptravi (selexipag)', indication: 'Cardiovascular (PAH)', revenue_usd: 1500000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'antibody', 'peptide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'metabolic', 'oncology', 'respiratory'],
    indications_specific: ['heart_failure', 'ckd', 'atherosclerosis', 'acs', 'antiplatelet'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 35,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['cardiorenal', 'sglt2_cv', 'heart_failure', 'antiplatelet', 'cv_outcomes'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Farxiga (dapagliflozin)', indication: 'Cardiovascular (Heart Failure/CKD SGLT2)', revenue_usd: 6500000000, expiry_year: 2028 },
      { drug_name: 'Brilinta (ticagrelor)', indication: 'Cardiovascular (ACS Antiplatelet)', revenue_usd: 2800000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Merck',
    name_variations: ['Merck & Co.', 'Merck Sharp & Dohme', 'MSD'],
    ticker: 'MRK',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology', 'metabolic', 'pulmonology'],
    indications_specific: ['pah', 'heart_failure', 'thrombotic_events'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 15,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['pah', 'vericiguat', 'sgc_stimulator', 'cv_pipeline', 'cardiometabolic'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Adempas (riociguat)', indication: 'Cardiovascular (PAH/CTEPH sGC Stimulator)', revenue_usd: 800000000, expiry_year: 2028 },
      { drug_name: 'Verquvo (vericiguat)', indication: 'Cardiovascular (Heart Failure sGC Stimulator)', revenue_usd: 300000000, expiry_year: 2033 },
    ],
  },
  {
    name: 'Bayer',
    name_variations: ['Bayer AG', 'Bayer Pharma'],
    ticker: 'BAYN.DE',
    company_type: 'large_pharma',
    hq_country: 'Germany',
    modalities_active: ['small_molecule', 'antibody', 'antisense_oligonucleotide'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'metabolic', 'oncology'],
    indications_specific: ['ckd', 'diabetic_kidney_disease', 'heart_failure', 'thrombosis', 'pah'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 28,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['finerenone_expansion', 'cardiorenal', 'factor_xi', 'post_xarelto', 'sgc_stimulator'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Kerendia (finerenone)', indication: 'Cardiovascular (CKD/Diabetic Kidney MRA)', revenue_usd: 1200000000, expiry_year: 2033 },
      { drug_name: 'Xarelto (rivaroxaban, co-rights with J&J)', indication: 'Cardiovascular (AF/VTE Anticoagulant)', revenue_usd: 5000000000, expiry_year: 2026 },
      { drug_name: 'Adempas (riociguat, co-rights with Merck)', indication: 'Cardiovascular (PAH sGC Stimulator)', revenue_usd: 800000000, expiry_year: 2028 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP CARDIOVASCULAR SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Alnylam Pharmaceuticals',
    name_variations: ['Alnylam', 'Alnylam Pharmaceuticals Inc'],
    ticker: 'ALNY',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['sirna', 'rna_therapeutics'],
    modalities_primary: ['sirna'],
    indications_active: ['cardiovascular', 'metabolic', 'neurology', 'rare_disease'],
    indications_specific: ['hypertension', 'attr_cardiomyopathy', 'lpa', 'heart_failure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 18,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['rnai_cardiovascular', 'zilebesiran_hypertension', 'attr_cardiomyopathy', 'lpa_sirna'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Zilebesiran (AGT siRNA)', indication: 'Cardiovascular (Hypertension RNAi)', revenue_usd: 0, expiry_year: 2041 },
      { drug_name: 'Onpattro/Amvuttra (patisiran/vutrisiran)', indication: 'Cardiovascular (ATTR Cardiomyopathy)', revenue_usd: 1200000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'Ionis Pharmaceuticals',
    name_variations: ['Ionis', 'Ionis Pharmaceuticals Inc', 'Isis Pharmaceuticals'],
    ticker: 'IONS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antisense_oligonucleotide', 'rna_therapeutics'],
    modalities_primary: ['antisense_oligonucleotide'],
    indications_active: ['cardiovascular', 'metabolic', 'neurology', 'rare_disease'],
    indications_specific: ['lpa', 'apoc3', 'angptl3', 'atherosclerosis', 'factor_xi'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 20,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['pelacarsen_lpa', 'antisense_cv', 'factor_xi_aso', 'apoc3_cardiometabolic'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Pelacarsen (Lp(a) ASO, partnered w/ Novartis)', indication: 'Cardiovascular (Atherosclerosis Lp(a))', revenue_usd: 0, expiry_year: 2039 },
      { drug_name: 'Olezarsen (ApoC-III ASO)', indication: 'Cardiovascular (Hypertriglyceridemia)', revenue_usd: 0, expiry_year: 2040 },
      { drug_name: 'Fesomersen (FXI ASO, partnered w/ Bayer)', indication: 'Cardiovascular (Thrombosis Factor XI)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Lexicon Pharmaceuticals',
    name_variations: ['Lexicon', 'Lexicon Pharmaceuticals Inc'],
    ticker: 'LXRX',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'metabolic'],
    indications_specific: ['heart_failure', 'type_1_diabetes', 'hfpef', 'hfref'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['sotagliflozin_hf', 'sglt1_sglt2_dual', 'heart_failure', 'inpefa_launch'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Inpefa (sotagliflozin)', indication: 'Cardiovascular (Heart Failure SGLT1/2)', revenue_usd: 400000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Cytokinetics',
    name_variations: ['Cytokinetics Inc', 'Cytokinetics Incorporated'],
    ticker: 'CYTK',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hcm', 'heart_failure', 'dcm', 'cardiac_muscle'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['aficamten_hcm', 'cardiac_myosin', 'omecamtiv_hf', 'muscle_biology'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Aficamten', indication: 'Cardiovascular (HCM Cardiac Myosin Inhibitor)', revenue_usd: 2000000000, expiry_year: 2040 },
      { drug_name: 'Omecamtiv mecarbil', indication: 'Cardiovascular (Heart Failure Cardiac Myosin Activator)', revenue_usd: 500000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'MyoKardia (BMS)',
    name_variations: ['MyoKardia', 'MyoKardia Inc', 'BMS MyoKardia'],
    ticker: 'BMY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hcm', 'dcm', 'cardiomyopathy'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 8,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['mavacamten_expansion', 'hcm', 'cardiomyopathy', 'cardiac_precision_medicine'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Camzyos (mavacamten)', indication: 'Cardiovascular (HCM Cardiac Myosin Inhibitor)', revenue_usd: 1500000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Anthos Therapeutics (Novartis)',
    name_variations: ['Anthos Therapeutics', 'Anthos', 'Novartis Anthos'],
    ticker: 'NVS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['antibody'],
    modalities_primary: ['antibody'],
    indications_active: ['cardiovascular'],
    indications_specific: ['atrial_fibrillation', 'thrombosis', 'stroke_prevention', 'factor_xi'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 250000000,
    median_upfront_usd: 125000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['abelacimab', 'factor_xi_inhibition', 'safer_anticoagulation', 'af_stroke_prevention'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Abelacimab (Factor XI antibody)', indication: 'Cardiovascular (AF Stroke Prevention Factor XI)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // HEART FAILURE / STRUCTURAL HEART / GENE THERAPY
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Tenaya Therapeutics',
    name_variations: ['Tenaya', 'Tenaya Therapeutics Inc'],
    ticker: 'TNYA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy', 'small_molecule'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular'],
    indications_specific: ['dcm', 'hcm', 'genetic_cardiomyopathy', 'heart_failure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 4,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['gene_therapy_cardiomyopathy', 'dcm', 'bag3', 'aav_cardiac'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'TN-201 (BAG3 gene therapy)', indication: 'Cardiovascular (DCM Gene Therapy)', revenue_usd: 0, expiry_year: 2042 },
    ],
  },
  {
    name: 'Renovacor',
    name_variations: ['Renovacor Inc'],
    ticker: 'RCOR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular'],
    indications_specific: ['dcm', 'bac_cardiomyopathy', 'genetic_heart_failure'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_1',
    territory_focus: ['us'],
    deals_last_12mo: 0,
    deals_last_24mo: 1,
    active_trials_count: 2,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['cardiac_gene_therapy', 'bac_cardiomyopathy', 'aav_gene_replacement'],
    data_quality_score: 55,
    patent_cliffs: [
      { drug_name: 'REN-001 (BAG3 gene therapy)', indication: 'Cardiovascular (DCM BAG3 Gene Therapy)', revenue_usd: 0, expiry_year: 2042 },
    ],
  },
  {
    name: 'Rocket Pharmaceuticals',
    name_variations: ['Rocket Pharma', 'Rocket Pharmaceuticals Inc'],
    ticker: 'RCKT',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_therapy'],
    modalities_primary: ['gene_therapy'],
    indications_active: ['cardiovascular', 'hematology', 'rare_disease'],
    indications_specific: ['danon_disease', 'cardiomyopathy', 'fanconi_anemia', 'lad1'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['danon_disease_gene_therapy', 'cardiac_gene_therapy', 'lentiviral_platform', 'rare_disease_cv'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'RP-A501 (Danon disease gene therapy)', indication: 'Cardiovascular (Danon Disease AAV Gene Therapy)', revenue_usd: 0, expiry_year: 2041 },
    ],
  },
  {
    name: 'Edwards Lifesciences',
    name_variations: ['Edwards', 'Edwards Lifesciences Corp'],
    ticker: 'EW',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['device', 'structural_heart'],
    modalities_primary: ['device'],
    indications_active: ['cardiovascular'],
    indications_specific: ['aortic_stenosis', 'mitral_regurgitation', 'tricuspid_regurgitation', 'structural_heart'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 20,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['tavr', 'tmvr', 'ttvr', 'structural_heart_innovation', 'heart_valve'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'SAPIEN (TAVR valve)', indication: 'Cardiovascular (Aortic Stenosis TAVR)', revenue_usd: 3800000000, expiry_year: 2030 },
      { drug_name: 'PASCAL (mitral/tricuspid repair)', indication: 'Cardiovascular (Mitral/Tricuspid Regurgitation)', revenue_usd: 400000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Cardiol Therapeutics',
    name_variations: ['Cardiol', 'Cardiol Therapeutics Inc'],
    ticker: 'CRDL',
    company_type: 'mid_biotech',
    hq_country: 'Canada',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['myocarditis', 'pericarditis', 'cardiac_inflammation'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['cardiol_rx', 'myocarditis', 'cardiac_inflammation', 'cannabidiol_iv'],
    data_quality_score: 55,
    patent_cliffs: [
      { drug_name: 'CardiolRx (IV cannabidiol)', indication: 'Cardiovascular (Acute Myocarditis)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Regeneron Pharmaceuticals',
    name_variations: ['Regeneron', 'Regeneron Pharmaceuticals Inc'],
    ticker: 'REGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'gene_therapy'],
    modalities_primary: ['antibody'],
    indications_active: ['cardiovascular', 'metabolic', 'ophthalmology', 'autoimmune'],
    indications_specific: ['hypercholesterolemia', 'atherosclerosis', 'cardiovascular_risk'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 30,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['pcsk9_franchise', 'cv_genetics', 'atherosclerosis', 'lipid_lowering'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Praluent (alirocumab)', indication: 'Cardiovascular (Hypercholesterolemia PCSK9)', revenue_usd: 600000000, expiry_year: 2029 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ANTICOAGULATION / THROMBOSIS SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Boehringer Ingelheim',
    name_variations: ['Boehringer', 'BI', 'Boehringer Ingelheim GmbH'],
    ticker: null,
    company_type: 'large_pharma',
    hq_country: 'Germany',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'metabolic', 'respiratory'],
    indications_specific: ['stroke_prevention', 'af', 'vte', 'anticoagulation'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 18,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['anticoagulation', 'af', 'stroke_prevention', 'cardiorenal'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Pradaxa (dabigatran)', indication: 'Cardiovascular (AF/VTE Anticoagulant)', revenue_usd: 2500000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Daiichi Sankyo',
    name_variations: ['Daiichi Sankyo Co.', 'Daiichi Sankyo Inc.'],
    ticker: '4568.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'adc', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology'],
    indications_specific: ['af', 'vte', 'anticoagulation', 'hypertension'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 15,
    avg_upfront_usd: 500000000,
    median_upfront_usd: 250000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['anticoagulation', 'edoxaban', 'cardiovascular_japan', 'hypertension'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Savaysa/Lixiana (edoxaban)', indication: 'Cardiovascular (AF/VTE Anticoagulant)', revenue_usd: 2200000000, expiry_year: 2029 },
      { drug_name: 'Olmesartan', indication: 'Cardiovascular (Hypertension ARB)', revenue_usd: 1000000000, expiry_year: 2026 },
    ],
  },
  {
    name: 'Otsuka Pharmaceutical',
    name_variations: ['Otsuka', 'Otsuka Pharmaceutical Co.', 'Otsuka Holdings'],
    ticker: '4578.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'psychiatry', 'nephrology'],
    indications_specific: ['heart_failure', 'hyponatremia', 'adpkd', 'vasopressin'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 12,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['tolvaptan', 'vasopressin_antagonism', 'heart_failure', 'cardiorenal'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Samsca/Jinarc (tolvaptan)', indication: 'Cardiovascular (Heart Failure/ADPKD Vasopressin)', revenue_usd: 2000000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Astellas Pharma',
    name_variations: ['Astellas', 'Astellas Pharma Inc.'],
    ticker: '4503.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['small_molecule', 'antibody', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'oncology', 'urology'],
    indications_specific: ['heart_failure', 'cardiorenal'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 10,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['cardiorenal', 'heart_failure', 'japan_cv', 'targeted_therapies'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Mirabegron (Myrbetriq)', indication: 'Urology (OAB)', revenue_usd: 2000000000, expiry_year: 2028 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // PULMONARY HYPERTENSION / PAH
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'United Therapeutics',
    name_variations: ['United Therapeutics Corp', 'UT'],
    ticker: 'UTHR',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'peptide', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'pulmonology'],
    indications_specific: ['pah', 'pulmonary_hypertension', 'organ_transplant'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 10,
    avg_upfront_usd: 400000000,
    median_upfront_usd: 200000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['pah_franchise', 'treprostinil', 'organ_manufacturing', 'prostacyclin'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Tyvaso (treprostinil)', indication: 'Cardiovascular (PAH/PH-ILD Prostacyclin)', revenue_usd: 2500000000, expiry_year: 2028 },
      { drug_name: 'Remodulin (treprostinil)', indication: 'Cardiovascular (PAH Prostacyclin IV/SC)', revenue_usd: 800000000, expiry_year: 2027 },
      { drug_name: 'Orenitram (treprostinil)', indication: 'Cardiovascular (PAH Oral Prostacyclin)', revenue_usd: 400000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Gossamer Bio',
    name_variations: ['Gossamer Bio Inc', 'Gossamer'],
    ticker: 'GOSS',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'pulmonology', 'oncology'],
    indications_specific: ['pah', 'pulmonary_hypertension'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['seralutinib', 'pah', 'pdgfr_csf1r_inhibition', 'inhaled_kinase'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'Seralutinib (inhaled PDGFR/CSF1R)', indication: 'Cardiovascular (PAH Inhaled Kinase Inhibitor)', revenue_usd: 0, expiry_year: 2040 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // LIPID-LOWERING / ATHEROSCLEROSIS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Amgen',
    name_variations: ['Amgen Inc.', 'Amgen Inc'],
    ticker: 'AMGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'sirna'],
    modalities_primary: ['antibody'],
    indications_active: ['cardiovascular', 'oncology', 'rare_disease', 'metabolic'],
    indications_specific: ['hypercholesterolemia', 'atherosclerosis', 'cardiovascular_risk', 'lpa'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 20,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['pcsk9', 'lpa_targeting', 'olpasiran', 'cv_risk_reduction', 'atherosclerosis'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Repatha (evolocumab)', indication: 'Cardiovascular (Hypercholesterolemia PCSK9)', revenue_usd: 1800000000, expiry_year: 2029 },
      { drug_name: 'Olpasiran (Lp(a) siRNA)', indication: 'Cardiovascular (Atherosclerosis Lp(a))', revenue_usd: 0, expiry_year: 2040 },
    ],
  },
  {
    name: 'Esperion Therapeutics',
    name_variations: ['Esperion', 'Esperion Therapeutics Inc'],
    ticker: 'ESPR',
    company_type: 'specialty',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hypercholesterolemia', 'statin_intolerance', 'atherosclerosis'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['bempedoic_acid', 'ldl_lowering', 'statin_alternative', 'cv_outcomes'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Nexletol (bempedoic acid)', indication: 'Cardiovascular (Hypercholesterolemia ACL Inhibitor)', revenue_usd: 500000000, expiry_year: 2036 },
      { drug_name: 'Nexlizet (bempedoic/ezetimibe)', indication: 'Cardiovascular (Hypercholesterolemia Combo)', revenue_usd: 300000000, expiry_year: 2036 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ADDITIONAL CV SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Milestone Pharmaceuticals',
    name_variations: ['Milestone', 'Milestone Pharmaceuticals Inc'],
    ticker: 'MIST',
    company_type: 'mid_biotech',
    hq_country: 'Canada',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['psvt', 'svt', 'arrhythmia'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 3,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['etripamil', 'psvt', 'self_administered_antiarrhythmic', 'nasal_delivery'],
    data_quality_score: 60,
    patent_cliffs: [
      { drug_name: 'Etripamil (intranasal)', indication: 'Cardiovascular (PSVT Intranasal Calcium Channel Blocker)', revenue_usd: 0, expiry_year: 2038 },
    ],
  },
  {
    name: 'Agepha Pharma',
    name_variations: ['Agepha', 'Agepha Pharma GmbH'],
    ticker: null,
    company_type: 'specialty',
    hq_country: 'Austria',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular'],
    indications_specific: ['hypertension', 'heart_failure', 'arrhythmia'],
    phase_preference_min: 'approved',
    phase_preference_max: 'approved',
    territory_focus: ['europe'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 2,
    avg_upfront_usd: null,
    median_upfront_usd: null,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['generic_cv', 'european_distribution', 'cardiovascular_portfolio'],
    data_quality_score: 50,
    patent_cliffs: [],
  },
  {
    name: 'Medtronic',
    name_variations: ['Medtronic plc', 'Medtronic Inc'],
    ticker: 'MDT',
    company_type: 'large_biotech',
    hq_country: 'Ireland',
    modalities_active: ['device', 'structural_heart', 'neuromodulation'],
    modalities_primary: ['device'],
    indications_active: ['cardiovascular', 'neurology'],
    indications_specific: ['arrhythmia', 'heart_failure', 'aortic_disease', 'peripheral_vascular'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 30,
    avg_upfront_usd: 800000000,
    median_upfront_usd: 400000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['cardiac_devices', 'pacemaker', 'ablation', 'structural_heart', 'aortic'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Micra (leadless pacemaker)', indication: 'Cardiovascular (Arrhythmia Pacemaker)', revenue_usd: 1500000000, expiry_year: 2030 },
      { drug_name: 'PulseSelect (PFA ablation)', indication: 'Cardiovascular (AF Pulsed Field Ablation)', revenue_usd: 500000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Abbott Laboratories',
    name_variations: ['Abbott', 'Abbott Labs'],
    ticker: 'ABT',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['device', 'diagnostic'],
    modalities_primary: ['device'],
    indications_active: ['cardiovascular'],
    indications_specific: ['structural_heart', 'arrhythmia', 'heart_failure', 'coronary'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 25,
    avg_upfront_usd: 600000000,
    median_upfront_usd: 300000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['mitraclip', 'structural_heart', 'coronary_stents', 'cardiac_monitoring'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'MitraClip', indication: 'Cardiovascular (Mitral Regurgitation Repair)', revenue_usd: 1200000000, expiry_year: 2030 },
      { drug_name: 'Xience (coronary stent)', indication: 'Cardiovascular (Coronary Artery Disease)', revenue_usd: 1500000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Verve Therapeutics',
    name_variations: ['Verve', 'Verve Therapeutics Inc'],
    ticker: 'VERV',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['gene_editing', 'rna_therapeutics'],
    modalities_primary: ['gene_editing'],
    indications_active: ['cardiovascular'],
    indications_specific: ['familial_hypercholesterolemia', 'atherosclerosis', 'pcsk9', 'angptl3'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_1',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 3,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['base_editing_cv', 'pcsk9_gene_editing', 'one_time_ldl_lowering', 'angptl3_editing'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'VERVE-101 (PCSK9 base editing)', indication: 'Cardiovascular (HeFH Gene Editing)', revenue_usd: 0, expiry_year: 2042 },
      { drug_name: 'VERVE-201 (ANGPTL3 base editing)', indication: 'Cardiovascular (Hypercholesterolemia Gene Editing)', revenue_usd: 0, expiry_year: 2042 },
    ],
  },
  {
    name: 'BridgeBio Pharma',
    name_variations: ['BridgeBio', 'BridgeBio Pharma Inc'],
    ticker: 'BBIO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'gene_therapy'],
    modalities_primary: ['small_molecule'],
    indications_active: ['cardiovascular', 'rare_disease'],
    indications_specific: ['attr_cardiomyopathy', 'hypertrophic_cardiomyopathy', 'genetic_heart_disease'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['acoramidis_attr', 'ttr_stabilizer', 'genetic_cardiomyopathy', 'rare_cv'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Attruby (acoramidis)', indication: 'Cardiovascular (ATTR Cardiomyopathy TTR Stabilizer)', revenue_usd: 2000000000, expiry_year: 2039 },
    ],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedCardiovascularCompanies() {
  console.log('Starting cardiovascular company seed...\n');
  console.log(`Seeding ${cardiovascularCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of cardiovascularCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with cardiovascular data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${cardiovascularCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedCardiovascularCompanies().catch(console.error);
