// Script to seed oncology-focused companies into the partner matching database
// Run with: npx tsx scripts/seed-oncology-companies.ts
//
// These companies are curated from real deal activity, SEC filings, and pipeline data.
// Each company includes oncology-relevant indications, modalities, strategic priorities,
// and deal history to power accurate partner matching for oncology assets.

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface OncologyCompany {
  name: string;
  name_variations: string[];
  ticker: string | null;
  company_type: 'large_pharma' | 'mid_pharma' | 'large_biotech' | 'mid_biotech' | 'specialty';
  hq_country: string;
  modalities_active: string[];
  modalities_primary: string[];
  indications_active: string[];
  indications_specific: string[];
  phase_preference_min: string;
  phase_preference_max: string;
  territory_focus: string[];
  deals_last_12mo: number;
  deals_last_24mo: number;
  active_trials_count: number;
  avg_upfront_usd: number | null;
  median_upfront_usd: number | null;
  actively_acquiring: boolean;
  acquisition_appetite: 'aggressive' | 'moderate' | 'selective' | 'inactive';
  strategic_priorities: string[];
  data_quality_score: number;
  patent_cliffs: Array<{
    drug_name: string;
    indication: string;
    revenue_usd: number;
    expiry_year: number;
  }>;
}

// =============================================================================
// ONCOLOGY COMPANY DATABASE
// Sources: SEC filings, DealForma, BioPharma Dive, Evaluate Pharma, company IRs
// =============================================================================

const oncologyCompanies: OncologyCompany[] = [
  // ─────────────────────────────────────────────────────────────────
  // LARGE PHARMA ONCOLOGY LEADERS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Merck',
    name_variations: ['Merck & Co.', 'Merck Sharp & Dohme', 'MSD', 'Merck & Co Inc'],
    ticker: 'MRK',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'adc', 'bispecific', 'mrna_vaccine'],
    modalities_primary: ['antibody', 'adc'],
    indications_active: ['oncology', 'hematology', 'infectious_disease'],
    indications_specific: ['nsclc', 'melanoma', 'rcc', 'head_neck', 'triple_negative_breast', 'endometrial', 'cervical', 'msi_high', 'hodgkin_lymphoma', 'gastric', 'hcc'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 9,
    deals_last_24mo: 16,
    active_trials_count: 120,
    avg_upfront_usd: 4000000000,
    median_upfront_usd: 2500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['post_keytruda_pipeline', 'io_combinations', 'adc_platform', 'personalized_cancer_vaccine', 'io_resistance'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Keytruda (pembrolizumab)', indication: 'Oncology (pan-tumor PD-1)', revenue_usd: 25000000000, expiry_year: 2028 },
      { drug_name: 'Lynparza (olaparib)', indication: 'Oncology (BRCA+ ovarian/breast/prostate)', revenue_usd: 2800000000, expiry_year: 2028 },
      { drug_name: 'Lenvima (lenvatinib)', indication: 'Oncology (RCC/HCC/endometrial)', revenue_usd: 2200000000, expiry_year: 2030 },
      { drug_name: 'Welireg (belzutifan)', indication: 'Oncology (VHL/RCC)', revenue_usd: 400000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'Roche/Genentech',
    name_variations: ['Roche', 'Genentech', 'Roche Holding AG', 'F. Hoffmann-La Roche'],
    ticker: 'RHHBY',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['antibody', 'bispecific', 'adc', 'small_molecule', 'immunotherapy'],
    modalities_primary: ['antibody', 'adc', 'bispecific'],
    indications_active: ['oncology', 'hematology', 'autoimmune', 'neurology'],
    indications_specific: ['nsclc', 'sclc', 'breast', 'her2_positive', 'bladder', 'liver', 'crc', 'melanoma', 'dlbcl', 'follicular_lymphoma'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 110,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['adc_next_gen', 'bispecific_platform', 'io_combinations', 'her2_franchise', 'lung_cancer'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Tecentriq (atezolizumab)', indication: 'Oncology (NSCLC/SCLC/bladder PD-L1)', revenue_usd: 3800000000, expiry_year: 2031 },
      { drug_name: 'Avastin (bevacizumab)', indication: 'Oncology (CRC/NSCLC/glioblastoma VEGF)', revenue_usd: 1500000000, expiry_year: 2025 },
      { drug_name: 'Herceptin (trastuzumab)', indication: 'Oncology (HER2+ breast/gastric)', revenue_usd: 800000000, expiry_year: 2025 },
      { drug_name: 'Perjeta (pertuzumab)', indication: 'Oncology (HER2+ breast)', revenue_usd: 4200000000, expiry_year: 2028 },
      { drug_name: 'Kadcyla (ado-trastuzumab emtansine)', indication: 'Oncology (HER2+ breast ADC)', revenue_usd: 2100000000, expiry_year: 2029 },
    ],
  },
  {
    name: 'Bristol-Myers Squibb',
    name_variations: ['BMS', 'Bristol Myers Squibb', 'Bristol-Myers Squibb Company'],
    ticker: 'BMY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'small_molecule', 'cell_therapy', 'bispecific', 'protein_degrader'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['oncology', 'hematology', 'cardiovascular', 'autoimmune'],
    indications_specific: ['nsclc', 'melanoma', 'rcc', 'hcc', 'mesothelioma', 'esophageal', 'gastric', 'crc', 'bladder'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 14,
    active_trials_count: 95,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['io_next_gen', 'lag3_combinations', 'protein_degradation', 'io_io_combos', 'solid_tumor_cell_therapy'],
    data_quality_score: 93,
    patent_cliffs: [
      { drug_name: 'Opdivo (nivolumab)', indication: 'Oncology (pan-tumor PD-1)', revenue_usd: 9200000000, expiry_year: 2028 },
      { drug_name: 'Yervoy (ipilimumab)', indication: 'Oncology (melanoma/RCC CTLA-4)', revenue_usd: 2200000000, expiry_year: 2026 },
      { drug_name: 'Opdualag (nivolumab + relatlimab)', indication: 'Oncology (melanoma PD-1/LAG-3)', revenue_usd: 600000000, expiry_year: 2036 },
    ],
  },
  {
    name: 'AstraZeneca',
    name_variations: ['AstraZeneca PLC', 'AZ', 'AstraZeneca Oncology'],
    ticker: 'AZN',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'bispecific', 'cell_therapy'],
    modalities_primary: ['small_molecule', 'adc'],
    indications_active: ['oncology', 'hematology', 'rare_disease', 'respiratory'],
    indications_specific: ['nsclc', 'egfr_mutant', 'breast', 'her2_low', 'ovarian', 'prostate', 'bladder', 'gastric', 'biliary', 'endometrial'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 10,
    deals_last_24mo: 18,
    active_trials_count: 130,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['adc_franchise', 'enhertu_expansion', 'egfr_next_gen', 'io_combinations', 'precision_oncology'],
    data_quality_score: 95,
    patent_cliffs: [
      { drug_name: 'Tagrisso (osimertinib)', indication: 'Oncology (EGFR-mutant NSCLC)', revenue_usd: 5800000000, expiry_year: 2032 },
      { drug_name: 'Enhertu (trastuzumab deruxtecan)', indication: 'Oncology (HER2+ breast/gastric/NSCLC ADC)', revenue_usd: 4000000000, expiry_year: 2035 },
      { drug_name: 'Imfinzi (durvalumab)', indication: 'Oncology (NSCLC/SCLC/bladder PD-L1)', revenue_usd: 4200000000, expiry_year: 2032 },
      { drug_name: 'Lynparza (olaparib)', indication: 'Oncology (BRCA+ ovarian/breast PARP)', revenue_usd: 2800000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Pfizer',
    name_variations: ['Pfizer Inc.', 'Pfizer Inc', 'Pfizer Oncology'],
    ticker: 'PFE',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'bispecific', 'mrna'],
    modalities_primary: ['adc', 'small_molecule'],
    indications_active: ['oncology', 'hematology', 'rare_disease', 'autoimmune'],
    indications_specific: ['breast', 'prostate', 'bladder', 'nsclc', 'head_neck', 'crc', 'lymphoma', 'multiple_myeloma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 8,
    deals_last_24mo: 15,
    active_trials_count: 85,
    avg_upfront_usd: 5000000000,
    median_upfront_usd: 2000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['adc_seagen_platform', 'breast_cancer_franchise', 'bladder_cancer', 'io_adc_combos', 'next_gen_adc_payloads'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Ibrance (palbociclib)', indication: 'Oncology (HR+/HER2- breast CDK4/6)', revenue_usd: 4800000000, expiry_year: 2027 },
      { drug_name: 'Padcev (enfortumab vedotin)', indication: 'Oncology (bladder/urothelial ADC)', revenue_usd: 2500000000, expiry_year: 2035 },
      { drug_name: 'Adcetris (brentuximab vedotin)', indication: 'Oncology/Hematology (Hodgkin lymphoma ADC)', revenue_usd: 1400000000, expiry_year: 2028 },
      { drug_name: 'Xtandi (enzalutamide)', indication: 'Oncology (prostate)', revenue_usd: 1800000000, expiry_year: 2027 },
    ],
  },
  {
    name: 'Eli Lilly',
    name_variations: ['Lilly', 'Eli Lilly and Company', 'Loxo Oncology', 'Loxo@Lilly'],
    ticker: 'LLY',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'bispecific', 'adc'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology', 'metabolic', 'autoimmune', 'neurology'],
    indications_specific: ['breast', 'nsclc', 'crc', 'ret_fusion', 'thyroid', 'cdk_driven'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 55,
    avg_upfront_usd: 2500000000,
    median_upfront_usd: 1200000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['precision_oncology', 'ret_franchise', 'cdk_inhibitors', 'targeted_therapies', 'tumor_agnostic'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Verzenio (abemaciclib)', indication: 'Oncology (HR+/HER2- breast CDK4/6)', revenue_usd: 3600000000, expiry_year: 2031 },
      { drug_name: 'Retevmo (selpercatinib)', indication: 'Oncology (RET-fusion NSCLC/thyroid)', revenue_usd: 700000000, expiry_year: 2036 },
      { drug_name: 'Jaypirca (pirtobrutinib)', indication: 'Oncology/Hematology (MCL/CLL)', revenue_usd: 800000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Novartis',
    name_variations: ['Novartis AG', 'Novartis Pharma', 'Novartis Oncology'],
    ticker: 'NVS',
    company_type: 'large_pharma',
    hq_country: 'Switzerland',
    modalities_active: ['small_molecule', 'antibody', 'radioligand', 'cell_therapy', 'adc'],
    modalities_primary: ['small_molecule', 'radioligand'],
    indications_active: ['oncology', 'hematology', 'cardiovascular', 'autoimmune'],
    indications_specific: ['breast', 'prostate', 'nsclc', 'melanoma', 'gist', 'net', 'cml', 'ph_plus_all'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 7,
    deals_last_24mo: 13,
    active_trials_count: 90,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['radioligand_therapy', 'breast_cancer', 'precision_oncology', 'ras_pathway', 'next_gen_rlt'],
    data_quality_score: 92,
    patent_cliffs: [
      { drug_name: 'Kisqali (ribociclib)', indication: 'Oncology (HR+/HER2- breast CDK4/6)', revenue_usd: 3400000000, expiry_year: 2033 },
      { drug_name: 'Pluvicto (lutetium-177 PSMA)', indication: 'Oncology (mCRPC radioligand)', revenue_usd: 1200000000, expiry_year: 2037 },
      { drug_name: 'Lutathera (lutetium-177 DOTA)', indication: 'Oncology (GEP-NET radioligand)', revenue_usd: 600000000, expiry_year: 2031 },
      { drug_name: 'Scemblix (asciminib)', indication: 'Oncology (CML)', revenue_usd: 800000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Johnson & Johnson (Janssen)',
    name_variations: ['J&J', 'Janssen', 'Janssen Pharmaceuticals', 'Janssen Biotech', 'Janssen Oncology'],
    ticker: 'JNJ',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['antibody', 'bispecific', 'adc', 'small_molecule', 'cell_therapy'],
    modalities_primary: ['bispecific', 'antibody'],
    indications_active: ['oncology', 'hematology', 'autoimmune'],
    indications_specific: ['multiple_myeloma', 'prostate', 'bladder', 'nsclc', 'lymphoma', 'egfr_mutant'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 75,
    avg_upfront_usd: 3500000000,
    median_upfront_usd: 2000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['bispecific_platform', 'egfr_met_bispecific', 'multiple_myeloma', 'prostate_cancer', 'adc_combinations'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Darzalex (daratumumab)', indication: 'Oncology/Hematology (multiple myeloma)', revenue_usd: 10000000000, expiry_year: 2031 },
      { drug_name: 'Erleada (apalutamide)', indication: 'Oncology (prostate)', revenue_usd: 2600000000, expiry_year: 2032 },
      { drug_name: 'Rybrevant (amivantamab)', indication: 'Oncology (EGFR-mutant NSCLC bispecific)', revenue_usd: 1200000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'AbbVie',
    name_variations: ['AbbVie Inc.', 'AbbVie Inc', 'AbbVie Oncology', 'ImmunoGen'],
    ticker: 'ABBV',
    company_type: 'large_pharma',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'bispecific'],
    modalities_primary: ['small_molecule', 'adc'],
    indications_active: ['oncology', 'hematology', 'autoimmune', 'neurology'],
    indications_specific: ['ovarian', 'breast', 'nsclc', 'aml', 'cll', 'lymphoma', 'solid_tumors'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 6,
    deals_last_24mo: 12,
    active_trials_count: 55,
    avg_upfront_usd: 3000000000,
    median_upfront_usd: 1500000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['adc_immunogen_platform', 'hematology_oncology', 'bcl2_franchise', 'solid_tumor_adc', 'next_gen_targeted'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Imbruvica (ibrutinib)', indication: 'Oncology/Hematology (CLL/MCL)', revenue_usd: 4200000000, expiry_year: 2027 },
      { drug_name: 'Venclexta (venetoclax)', indication: 'Oncology/Hematology (CLL/AML)', revenue_usd: 2400000000, expiry_year: 2030 },
      { drug_name: 'Elahere (mirvetuximab soravtansine)', indication: 'Oncology (FRa+ ovarian ADC)', revenue_usd: 600000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Sanofi',
    name_variations: ['Sanofi S.A.', 'Sanofi-Aventis', 'Sanofi Oncology'],
    ticker: 'SNY',
    company_type: 'large_pharma',
    hq_country: 'France',
    modalities_active: ['antibody', 'adc', 'bispecific', 'small_molecule'],
    modalities_primary: ['antibody', 'adc'],
    indications_active: ['oncology', 'hematology', 'autoimmune', 'rare_disease'],
    indications_specific: ['nsclc', 'skin_cancer', 'crc', 'solid_tumors', 'lymphoma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 40,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['io_combinations', 'adc_pipeline', 'pd1_ceacam5_bispecific', 'solid_tumor_io', 'next_gen_checkpoint'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Libtayo (cemiplimab)', indication: 'Oncology (CSCC/BCC/NSCLC PD-1)', revenue_usd: 1200000000, expiry_year: 2035 },
      { drug_name: 'Sarclisa (isatuximab)', indication: 'Oncology/Hematology (multiple myeloma)', revenue_usd: 800000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'GSK',
    name_variations: ['GlaxoSmithKline', 'GSK plc', 'GSK Oncology'],
    ticker: 'GSK',
    company_type: 'large_pharma',
    hq_country: 'UK',
    modalities_active: ['antibody', 'adc', 'small_molecule', 'cell_therapy'],
    modalities_primary: ['antibody', 'adc'],
    indications_active: ['oncology', 'hematology', 'infectious_disease'],
    indications_specific: ['endometrial', 'ovarian', 'cervical', 'multiple_myeloma', 'solid_tumors'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 35,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['gynecologic_oncology', 'bcma_multiple_myeloma', 'next_gen_adc', 'io_combinations'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Zejula (niraparib)', indication: 'Oncology (ovarian PARP)', revenue_usd: 800000000, expiry_year: 2030 },
      { drug_name: 'Jemperli (dostarlimab)', indication: 'Oncology (endometrial/MSI-H PD-1)', revenue_usd: 600000000, expiry_year: 2037 },
      { drug_name: 'Blenrep (belantamab mafodotin)', indication: 'Oncology/Hematology (multiple myeloma ADC)', revenue_usd: 500000000, expiry_year: 2035 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // MID-CAP ONCOLOGY BIOTECHS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Daiichi Sankyo',
    name_variations: ['Daiichi Sankyo Co.', 'Daiichi Sankyo Inc.', 'DXd Platform'],
    ticker: '4568.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['adc', 'antibody', 'small_molecule', 'bispecific'],
    modalities_primary: ['adc'],
    indications_active: ['oncology', 'hematology'],
    indications_specific: ['breast', 'her2_positive', 'her2_low', 'nsclc', 'gastric', 'crc', 'ovarian', 'aml'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'japan'],
    deals_last_12mo: 6,
    deals_last_24mo: 11,
    active_trials_count: 70,
    avg_upfront_usd: 2000000000,
    median_upfront_usd: 1000000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['dxd_adc_platform', 'her2_franchise', 'her3_adc', 'trop2_adc', 'next_gen_payloads'],
    data_quality_score: 90,
    patent_cliffs: [
      { drug_name: 'Enhertu (trastuzumab deruxtecan)', indication: 'Oncology (HER2+ breast/gastric/NSCLC ADC)', revenue_usd: 6000000000, expiry_year: 2035 },
      { drug_name: 'Dato-DXd (datopotamab deruxtecan)', indication: 'Oncology (NSCLC/TNBC TROP2 ADC)', revenue_usd: 2000000000, expiry_year: 2037 },
      { drug_name: 'HER3-DXd (patritumab deruxtecan)', indication: 'Oncology (EGFR-mutant NSCLC HER3 ADC)', revenue_usd: 1000000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Gilead Sciences',
    name_variations: ['Gilead', 'Gilead Sciences Inc', 'Immunomedics', 'Gilead Oncology'],
    ticker: 'GILD',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['adc', 'antibody', 'small_molecule', 'cell_therapy'],
    modalities_primary: ['adc', 'cell_therapy'],
    indications_active: ['oncology', 'hematology', 'infectious_disease'],
    indications_specific: ['triple_negative_breast', 'bladder', 'nsclc', 'hr_positive_breast', 'dlbcl', 'follicular_lymphoma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 55,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 700000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['trodelvy_expansion', 'trop2_adc', 'car_t_hematology', 'solid_tumor_cell_therapy', 'io_adc_combos'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Trodelvy (sacituzumab govitecan)', indication: 'Oncology (TNBC/bladder TROP2 ADC)', revenue_usd: 2000000000, expiry_year: 2034 },
      { drug_name: 'Yescarta (axicabtagene)', indication: 'Oncology/Hematology (DLBCL CAR-T)', revenue_usd: 1500000000, expiry_year: 2033 },
      { drug_name: 'Tecartus (brexucabtagene)', indication: 'Oncology/Hematology (MCL CAR-T)', revenue_usd: 400000000, expiry_year: 2034 },
    ],
  },
  {
    name: 'Regeneron',
    name_variations: ['Regeneron Pharmaceuticals', 'Regeneron Pharmaceuticals Inc'],
    ticker: 'REGN',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['antibody', 'bispecific', 'costimulatory_bispecific', 'adc'],
    modalities_primary: ['antibody', 'bispecific'],
    indications_active: ['oncology', 'autoimmune', 'ophthalmology', 'dermatology'],
    indications_specific: ['cscc', 'bcc', 'nsclc', 'crc', 'solid_tumors', 'lymphoma'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 40,
    avg_upfront_usd: 1000000000,
    median_upfront_usd: 500000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['costimulatory_bispecifics', 'pd1_combinations', 'next_gen_io', 'solid_tumor_bispecific', 'lat_therapy'],
    data_quality_score: 85,
    patent_cliffs: [
      { drug_name: 'Libtayo (cemiplimab)', indication: 'Oncology (CSCC/NSCLC PD-1)', revenue_usd: 1200000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Exelixis',
    name_variations: ['Exelixis Inc', 'Exelixis Inc.'],
    ticker: 'EXEL',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule', 'adc'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology'],
    indications_specific: ['rcc', 'hcc', 'thyroid', 'nsclc', 'castration_resistant_prostate'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 25,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['cabozantinib_expansion', 'next_gen_tki', 'adc_pipeline', 'io_tki_combos'],
    data_quality_score: 80,
    patent_cliffs: [
      { drug_name: 'Cabometyx/Cometriq (cabozantinib)', indication: 'Oncology (RCC/HCC/thyroid MET/VEGFR)', revenue_usd: 2200000000, expiry_year: 2030 },
    ],
  },
  {
    name: 'Blueprint Medicines',
    name_variations: ['Blueprint', 'Blueprint Medicines Corp'],
    ticker: 'BPMC',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology', 'hematology', 'rare_disease'],
    indications_specific: ['gist', 'systemic_mastocytosis', 'nsclc', 'egfr_exon20'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 15,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['precision_oncology', 'kinase_inhibitors', 'gist_franchise', 'egfr_exon20_insertion'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Ayvakit (avapritinib)', indication: 'Oncology (GIST/systemic mastocytosis KIT/PDGFRA)', revenue_usd: 600000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Mirati Therapeutics',
    name_variations: ['Mirati', 'Mirati Therapeutics Inc', 'BMS/Mirati'],
    ticker: null,
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology'],
    indications_specific: ['nsclc', 'crc', 'pancreatic', 'kras_g12c', 'kras_driven'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['kras_g12c', 'kras_combinations', 'ras_pathway', 'nsclc_precision'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Krazati (adagrasib)', indication: 'Oncology (KRAS G12C NSCLC)', revenue_usd: 500000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Revolution Medicines',
    name_variations: ['Revolution Medicines Inc', 'RevMed'],
    ticker: 'RVMD',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology'],
    indications_specific: ['nsclc', 'crc', 'pancreatic', 'kras_g12c', 'kras_g12d', 'kras_g12v', 'ras_driven'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 10,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['ras_on_inhibitors', 'pan_ras', 'kras_multi_mutant', 'ras_companion_dx', 'pancreatic_cancer'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'RMC-6236 (RAS(ON) multi-selective)', indication: 'Oncology (KRAS-mutant NSCLC/pancreatic)', revenue_usd: 1500000000, expiry_year: 2040 },
      { drug_name: 'RMC-6291 (RAS(ON) G12C)', indication: 'Oncology (KRAS G12C solid tumors)', revenue_usd: 500000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Relay Therapeutics',
    name_variations: ['Relay', 'Relay Therapeutics Inc'],
    ticker: 'RLAY',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology'],
    indications_specific: ['breast', 'gi_stromal', 'solid_tumors', 'pi3k_driven', 'fgfr_driven'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['motion_based_drug_design', 'pi3ka_mutant_selective', 'precision_oncology', 'fgfr2'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'RLY-2608 (PI3Ka mutant-selective)', indication: 'Oncology (PIK3CA-mutant breast)', revenue_usd: 800000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'SpringWorks Therapeutics',
    name_variations: ['SpringWorks', 'SpringWorks Therapeutics Inc'],
    ticker: 'SWTX',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['small_molecule'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology', 'rare_disease'],
    indications_specific: ['desmoid_tumor', 'schwannomatosis', 'nf1', 'solid_tumors'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['gamma_secretase_inhibition', 'desmoid_tumors', 'rare_oncology', 'combination_strategies'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Ogsiveo (nirogacestat)', indication: 'Oncology (desmoid tumors gamma-secretase)', revenue_usd: 600000000, expiry_year: 2037 },
    ],
  },
  {
    name: 'Seagen (Pfizer)',
    name_variations: ['Seagen Inc', 'Seattle Genetics', 'Seagen/Pfizer'],
    ticker: 'PFE',
    company_type: 'large_biotech',
    hq_country: 'US',
    modalities_active: ['adc', 'antibody'],
    modalities_primary: ['adc'],
    indications_active: ['oncology', 'hematology'],
    indications_specific: ['bladder', 'breast', 'cervical', 'nsclc', 'hodgkin_lymphoma', 'head_neck'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 45,
    avg_upfront_usd: 1500000000,
    median_upfront_usd: 800000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['adc_platform_expansion', 'next_gen_payloads', 'novel_targets_adc', 'io_adc_combos'],
    data_quality_score: 88,
    patent_cliffs: [
      { drug_name: 'Padcev (enfortumab vedotin)', indication: 'Oncology (bladder/urothelial ADC)', revenue_usd: 2500000000, expiry_year: 2035 },
      { drug_name: 'Adcetris (brentuximab vedotin)', indication: 'Oncology/Hematology (Hodgkin/ALCL ADC)', revenue_usd: 1400000000, expiry_year: 2028 },
      { drug_name: 'Tivdak (tisotumab vedotin)', indication: 'Oncology (cervical ADC)', revenue_usd: 400000000, expiry_year: 2036 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ADC / BISPECIFIC SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'ADC Therapeutics',
    name_variations: ['ADC Therapeutics SA', 'ADCT'],
    ticker: 'ADCT',
    company_type: 'mid_biotech',
    hq_country: 'Switzerland',
    modalities_active: ['adc'],
    modalities_primary: ['adc'],
    indications_active: ['oncology', 'hematology'],
    indications_specific: ['dlbcl', 'hodgkin_lymphoma', 'solid_tumors', 'nsclc'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 8,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['adc_solid_tumors', 'next_gen_payloads', 'pbd_adc', 'combination_io_adc'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Zynlonta (loncastuximab tesirine)', indication: 'Oncology/Hematology (DLBCL ADC)', revenue_usd: 200000000, expiry_year: 2035 },
    ],
  },
  {
    name: 'Zymeworks',
    name_variations: ['Zymeworks Inc', 'Zymeworks Biopharmaceuticals'],
    ticker: 'ZYME',
    company_type: 'mid_biotech',
    hq_country: 'Canada',
    modalities_active: ['bispecific', 'adc', 'antibody'],
    modalities_primary: ['bispecific', 'adc'],
    indications_active: ['oncology'],
    indications_specific: ['her2_positive', 'breast', 'gastric', 'biliary', 'solid_tumors'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 8,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['bispecific_adc_platform', 'her2_biparatopic', 'azymetric_bispecific', 'next_gen_adc'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Zanidatamab', indication: 'Oncology (HER2+ biliary/gastric biparatopic)', revenue_usd: 800000000, expiry_year: 2038 },
      { drug_name: 'ZW191', indication: 'Oncology (ADC)', revenue_usd: 300000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'Sutro Biopharma',
    name_variations: ['Sutro', 'Sutro Biopharma Inc'],
    ticker: 'STRO',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['adc'],
    modalities_primary: ['adc'],
    indications_active: ['oncology'],
    indications_specific: ['ovarian', 'nsclc', 'breast', 'solid_tumors'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 4,
    active_trials_count: 6,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['cell_free_adc_platform', 'site_specific_conjugation', 'novel_adc_targets', 'folr1_adc'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'STRO-002', indication: 'Oncology (ovarian FRa ADC)', revenue_usd: 300000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Mersana Therapeutics',
    name_variations: ['Mersana', 'Mersana Therapeutics Inc'],
    ticker: 'MRSN',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['adc'],
    modalities_primary: ['adc'],
    indications_active: ['oncology'],
    indications_specific: ['ovarian', 'nsclc', 'breast', 'solid_tumors', 'napi2b_tumors'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 3,
    active_trials_count: 5,
    avg_upfront_usd: 60000000,
    median_upfront_usd: 30000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['dolasynthen_platform', 'sting_adc', 'immunosynthen', 'novel_adc_payloads'],
    data_quality_score: 62,
    patent_cliffs: [
      { drug_name: 'XMT-1660', indication: 'Oncology (B7-H4+ solid tumor ADC)', revenue_usd: 400000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'RemeGen',
    name_variations: ['RemeGen Co.', 'RemeGen Biosciences'],
    ticker: '9995.HK',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['adc', 'antibody'],
    modalities_primary: ['adc'],
    indications_active: ['oncology'],
    indications_specific: ['breast', 'her2_positive', 'gastric', 'urothelial', 'nsclc'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 3,
    deals_last_24mo: 5,
    active_trials_count: 15,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['adc_her2', 'disitamab_vedotin_expansion', 'next_gen_adc', 'global_licensing'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Aidixi (disitamab vedotin)', indication: 'Oncology (HER2+ gastric/urothelial ADC)', revenue_usd: 600000000, expiry_year: 2035 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // CELL THERAPY / IMMUNO-ONCOLOGY SPECIALISTS
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Iovance Biotherapeutics',
    name_variations: ['Iovance', 'Iovance Biotherapeutics Inc'],
    ticker: 'IOVA',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['cell_therapy'],
    modalities_primary: ['cell_therapy'],
    indications_active: ['oncology'],
    indications_specific: ['melanoma', 'nsclc', 'cervical', 'head_neck', 'solid_tumors'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 2,
    deals_last_24mo: 3,
    active_trials_count: 12,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['til_therapy_melanoma', 'til_expansion_solid_tumors', 'nsclc_til', 'next_gen_til'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Amtagvi (lifileucel)', indication: 'Oncology (melanoma TIL therapy)', revenue_usd: 500000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Replimune',
    name_variations: ['Replimune Group', 'Replimune Group Inc'],
    ticker: 'REPL',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['oncolytic_virus', 'gene_therapy'],
    modalities_primary: ['oncolytic_virus'],
    indications_active: ['oncology'],
    indications_specific: ['melanoma', 'cscc', 'solid_tumors', 'bladder'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oncolytic_hsv', 'intratumoral_io', 'rp1_melanoma', 'combination_checkpoint'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'RP1 (vusolimogene oderparepvec)', indication: 'Oncology (melanoma/CSCC oncolytic virus)', revenue_usd: 400000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'CG Oncology',
    name_variations: ['CG Oncology Inc', 'Cold Genesys'],
    ticker: 'CGON',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['oncolytic_virus'],
    modalities_primary: ['oncolytic_virus'],
    indications_active: ['oncology'],
    indications_specific: ['bladder', 'nmibc', 'solid_tumors'],
    phase_preference_min: 'phase_2',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 5,
    avg_upfront_usd: 50000000,
    median_upfront_usd: 25000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['oncolytic_adenovirus', 'bladder_cancer', 'nmibc', 'intravesical_io'],
    data_quality_score: 65,
    patent_cliffs: [
      { drug_name: 'Cretostimogene grenadenorepvec', indication: 'Oncology (NMIBC oncolytic adenovirus)', revenue_usd: 500000000, expiry_year: 2039 },
    ],
  },
  {
    name: 'Instil Bio',
    name_variations: ['Instil Bio Inc'],
    ticker: 'TIL',
    company_type: 'mid_biotech',
    hq_country: 'US',
    modalities_active: ['cell_therapy'],
    modalities_primary: ['cell_therapy'],
    indications_active: ['oncology'],
    indications_specific: ['melanoma', 'nsclc', 'head_neck', 'solid_tumors'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_2',
    territory_focus: ['us'],
    deals_last_12mo: 1,
    deals_last_24mo: 1,
    active_trials_count: 3,
    avg_upfront_usd: 30000000,
    median_upfront_usd: 15000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['coisolation_til', 'next_gen_til', 'solid_tumor_cell_therapy', 'manufacturing_innovation'],
    data_quality_score: 58,
    patent_cliffs: [
      { drug_name: 'ITIL-306 (coisolation TIL)', indication: 'Oncology (solid tumors TIL therapy)', revenue_usd: 200000000, expiry_year: 2040 },
    ],
  },
  {
    name: 'Adaptimmune',
    name_variations: ['Adaptimmune Therapeutics', 'Adaptimmune Therapeutics plc'],
    ticker: 'ADAP',
    company_type: 'mid_biotech',
    hq_country: 'UK',
    modalities_active: ['cell_therapy'],
    modalities_primary: ['cell_therapy'],
    indications_active: ['oncology'],
    indications_specific: ['synovial_sarcoma', 'myxoid_round_cell_liposarcoma', 'solid_tumors', 'head_neck', 'nsclc'],
    phase_preference_min: 'preclinical',
    phase_preference_max: 'phase_3',
    territory_focus: ['us', 'global'],
    deals_last_12mo: 1,
    deals_last_24mo: 2,
    active_trials_count: 6,
    avg_upfront_usd: 80000000,
    median_upfront_usd: 40000000,
    actively_acquiring: false,
    acquisition_appetite: 'inactive',
    strategic_priorities: ['tcr_t_therapy', 'mage_a4', 'solid_tumor_cell_therapy', 'allogeneic_tcr_t'],
    data_quality_score: 68,
    patent_cliffs: [
      { drug_name: 'Tecelra (afamitresgene autoleucel)', indication: 'Oncology (synovial sarcoma TCR-T)', revenue_usd: 300000000, expiry_year: 2039 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // ASIAN PHARMA ONCOLOGY
  // ─────────────────────────────────────────────────────────────────
  {
    name: 'Hutchmed',
    name_variations: ['Hutchmed (China)', 'HUTCHMED', 'Hutchison MediPharma', 'Chi-Med'],
    ticker: 'HCM',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['small_molecule', 'antibody'],
    modalities_primary: ['small_molecule'],
    indications_active: ['oncology'],
    indications_specific: ['crc', 'net', 'thyroid', 'nsclc', 'biliary', 'solid_tumors'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'global', 'us'],
    deals_last_12mo: 2,
    deals_last_24mo: 5,
    active_trials_count: 20,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: false,
    acquisition_appetite: 'selective',
    strategic_priorities: ['vegfr_tki', 'fruquintinib_global', 'surufatinib_expansion', 'selective_kinase_inhibitors'],
    data_quality_score: 70,
    patent_cliffs: [
      { drug_name: 'Fruzaqla (fruquintinib)', indication: 'Oncology (CRC VEGFR1/2/3)', revenue_usd: 500000000, expiry_year: 2033 },
      { drug_name: 'Sulanda (surufatinib)', indication: 'Oncology (NET VEGFR/FGFR/CSF-1R)', revenue_usd: 300000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'BeiGene',
    name_variations: ['BeiGene Ltd', 'BeiGene Inc.', 'BeiGene Oncology'],
    ticker: 'BGNE',
    company_type: 'large_biotech',
    hq_country: 'China',
    modalities_active: ['small_molecule', 'antibody', 'bispecific', 'adc'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['oncology', 'hematology'],
    indications_specific: ['nsclc', 'gastric', 'esophageal', 'hcc', 'crc', 'lymphoma', 'cll'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['global', 'china', 'us'],
    deals_last_12mo: 5,
    deals_last_24mo: 10,
    active_trials_count: 60,
    avg_upfront_usd: 300000000,
    median_upfront_usd: 150000000,
    actively_acquiring: true,
    acquisition_appetite: 'aggressive',
    strategic_priorities: ['pd1_franchise', 'tislelizumab_global', 'btk_franchise', 'solid_tumor_io', 'china_oncology'],
    data_quality_score: 82,
    patent_cliffs: [
      { drug_name: 'Tevimbra (tislelizumab)', indication: 'Oncology (NSCLC/esophageal/gastric PD-1)', revenue_usd: 1200000000, expiry_year: 2034 },
      { drug_name: 'Brukinsa (zanubrutinib)', indication: 'Oncology/Hematology (CLL/MCL/WM)', revenue_usd: 3000000000, expiry_year: 2033 },
    ],
  },
  {
    name: 'Zai Lab',
    name_variations: ['Zai Lab Limited', 'Zai Lab Ltd'],
    ticker: 'ZLAB',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['antibody', 'small_molecule', 'adc', 'cell_therapy'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['oncology', 'autoimmune', 'neurology'],
    indications_specific: ['ovarian', 'nsclc', 'breast', 'hcc', 'gastric', 'glioblastoma'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'asia'],
    deals_last_12mo: 3,
    deals_last_24mo: 7,
    active_trials_count: 20,
    avg_upfront_usd: 100000000,
    median_upfront_usd: 50000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['china_in_licensing', 'oncology_china', 'tumor_treating_fields', 'io_combinations_china'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Zejula (niraparib, China)', indication: 'Oncology (ovarian PARP, China rights)', revenue_usd: 200000000, expiry_year: 2030 },
      { drug_name: 'Optune (tumor treating fields, China)', indication: 'Oncology (GBM, China rights)', revenue_usd: 100000000, expiry_year: 2032 },
    ],
  },
  {
    name: 'Ono Pharmaceutical',
    name_variations: ['Ono Pharma', 'Ono Pharmaceutical Co.'],
    ticker: '4528.T',
    company_type: 'large_pharma',
    hq_country: 'Japan',
    modalities_active: ['antibody', 'small_molecule', 'bispecific'],
    modalities_primary: ['antibody', 'small_molecule'],
    indications_active: ['oncology', 'hematology', 'autoimmune'],
    indications_specific: ['nsclc', 'gastric', 'melanoma', 'rcc', 'head_neck', 'esophageal'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['japan', 'asia'],
    deals_last_12mo: 3,
    deals_last_24mo: 6,
    active_trials_count: 30,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['opdivo_japan_expansion', 'io_combinations', 'next_gen_checkpoint', 'japan_oncology'],
    data_quality_score: 78,
    patent_cliffs: [
      { drug_name: 'Opdivo (nivolumab, Japan rights)', indication: 'Oncology (pan-tumor PD-1, Japan)', revenue_usd: 2000000000, expiry_year: 2028 },
    ],
  },
  {
    name: 'Innovent Biologics',
    name_variations: ['Innovent', 'Innovent Biologics Inc'],
    ticker: '1801.HK',
    company_type: 'mid_biotech',
    hq_country: 'China',
    modalities_active: ['antibody', 'bispecific', 'adc', 'cell_therapy'],
    modalities_primary: ['antibody', 'bispecific'],
    indications_active: ['oncology', 'autoimmune'],
    indications_specific: ['nsclc', 'hcc', 'gastric', 'crc', 'esophageal', 'lymphoma', 'breast'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 4,
    deals_last_24mo: 8,
    active_trials_count: 35,
    avg_upfront_usd: 150000000,
    median_upfront_usd: 80000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['sintilimab_expansion', 'bispecific_platform', 'pd1_vegf_bispecific', 'global_partnerships', 'china_io'],
    data_quality_score: 75,
    patent_cliffs: [
      { drug_name: 'Tyvyt (sintilimab)', indication: 'Oncology (NSCLC/HCC PD-1, China)', revenue_usd: 800000000, expiry_year: 2032 },
      { drug_name: 'IBI376 (pucotenlimab)', indication: 'Oncology (PD-1/VEGF bispecific)', revenue_usd: 400000000, expiry_year: 2038 },
    ],
  },
  {
    name: 'Hengrui Pharma',
    name_variations: ['Jiangsu Hengrui', 'Hengrui Medicine', 'Jiangsu Hengrui Pharmaceuticals'],
    ticker: '600276.SS',
    company_type: 'large_pharma',
    hq_country: 'China',
    modalities_active: ['small_molecule', 'antibody', 'adc', 'bispecific'],
    modalities_primary: ['small_molecule', 'antibody'],
    indications_active: ['oncology', 'autoimmune'],
    indications_specific: ['nsclc', 'breast', 'gastric', 'hcc', 'ovarian', 'crc', 'bladder'],
    phase_preference_min: 'phase_1',
    phase_preference_max: 'approved',
    territory_focus: ['china', 'global'],
    deals_last_12mo: 5,
    deals_last_24mo: 9,
    active_trials_count: 50,
    avg_upfront_usd: 200000000,
    median_upfront_usd: 100000000,
    actively_acquiring: true,
    acquisition_appetite: 'moderate',
    strategic_priorities: ['pd1_franchise', 'adc_pipeline', 'global_out_licensing', 'cdk_inhibitors', 'parp_inhibitors'],
    data_quality_score: 72,
    patent_cliffs: [
      { drug_name: 'Camrelizumab', indication: 'Oncology (NSCLC/HCC/NPC PD-1)', revenue_usd: 1000000000, expiry_year: 2031 },
      { drug_name: 'Fuzuloparib', indication: 'Oncology (ovarian PARP)', revenue_usd: 300000000, expiry_year: 2033 },
    ],
  },
];

// =============================================================================
// SEED FUNCTION
// =============================================================================

async function seedOncologyCompanies() {
  console.log('Starting oncology company seed...\n');
  console.log(`Seeding ${oncologyCompanies.length} companies...\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const company of oncologyCompanies) {
    const companyData = {
      name: company.name,
      name_variations: company.name_variations,
      ticker: company.ticker,
      company_type: company.company_type,
      hq_country: company.hq_country,
      modalities_active: company.modalities_active,
      modalities_primary: company.modalities_primary,
      indications_active: company.indications_active,
      indications_specific: company.indications_specific,
      phase_preference_min: company.phase_preference_min,
      phase_preference_max: company.phase_preference_max,
      territory_focus: company.territory_focus,
      deals_last_12mo: company.deals_last_12mo,
      deals_last_24mo: company.deals_last_24mo,
      active_trials_count: company.active_trials_count,
      avg_upfront_usd: company.avg_upfront_usd,
      median_upfront_usd: company.median_upfront_usd,
      actively_acquiring: company.actively_acquiring,
      acquisition_appetite: company.acquisition_appetite,
      strategic_priorities: company.strategic_priorities,
      data_quality_score: company.data_quality_score,
      patent_cliffs: company.patent_cliffs,
      data_sources: ['sec_filings', 'dealforma', 'company_ir', 'evaluate_pharma'],
      last_enriched_at: new Date().toISOString(),
    };

    const { error: insertError } = await supabase
      .from('companies')
      .insert(companyData);

    if (insertError) {
      if (insertError.code === '23505') {
        const { error: updateError } = await supabase
          .from('companies')
          .update({
            ...companyData,
            updated_at: new Date().toISOString(),
          })
          .eq('name', company.name);

        if (updateError) {
          console.error(`  ✗ ${company.name}: Update failed — ${updateError.message}`);
          errors++;
        } else {
          console.log(`  ↻ ${company.name}: Updated with oncology data (${company.company_type})`);
          updated++;
        }
      } else {
        console.error(`  ✗ ${company.name}: Insert failed — ${insertError.message}`);
        errors++;
      }
    } else {
      console.log(`  ✓ ${company.name}: Created (${company.company_type})`);
      created++;
    }
  }

  console.log(`\n${'='.repeat(50)}`);
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors:  ${errors}`);
  console.log(`Total:   ${oncologyCompanies.length}`);
  console.log(`${'='.repeat(50)}\n`);
}

seedOncologyCompanies().catch(console.error);
