-- SEO indexing queue: tracks pages submitted to Google Indexing API
CREATE TABLE IF NOT EXISTS seo_indexing_queue (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  url text NOT NULL UNIQUE,
  priority numeric(3,1) NOT NULL DEFAULT 0.5,
  submitted_at timestamptz,
  indexed_at timestamptz,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'submitted', 'indexed', 'failed')),
  error_message text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seo_indexing_queue_status ON seo_indexing_queue(status);
CREATE INDEX IF NOT EXISTS idx_seo_indexing_queue_priority ON seo_indexing_queue(priority DESC);

-- LinkedIn draft posts generated by the weekly cron
CREATE TABLE IF NOT EXISTS linkedin_drafts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL,
  link_url text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'skipped')),
  created_at timestamptz DEFAULT now(),
  scheduled_for timestamptz
);

CREATE INDEX IF NOT EXISTS idx_linkedin_drafts_status ON linkedin_drafts(status);
CREATE INDEX IF NOT EXISTS idx_linkedin_drafts_created ON linkedin_drafts(created_at DESC);
